### ISSUE TITLE
How to compile BVNC

### ISSUE THREAD

**Issue by Yeashin-Fu** [iiordanov/remote-desktop-clients#102]
When I was compiled:
activity.getConnection().Gen_update(activity.getDatabase().getWritableDatabase());
Describe the resource path location type
Cannot resolve type net. Sqlcipher. Database. SQLiteDatabase.From required. Class files indirectly cited it ConnectionBean. Java/bVNC/SRC/Java problem com/iiordanov bVNC line 1

**Comment by iiordanov** [comment]
Did you follow the instructions in the BUILDING file?

Did you use pre-built libraries or try to build them yourself from scratch?

Iordan
