### ISSUE TITLE
aSpice Broken menu button in 3.9.4

### ISSUE THREAD

**Issue by t0mcat1337** [iiordanov/remote-desktop-clients#104]
In the newest Version of aSpice (3.9.4) the three dot Menu Icon at the right border (next to the Keyboard icon) doesn't react on touch; when it is touched nothing happens. 

In the last Version (3.8.6) eveything works fine.

Perhaps this has the same cause as described in Issue 91, as it seems exactly the same in aRDP:
https://github.com/iiordanov/remote-desktop-clients/issues/91

Tested on a Samsung Galaxy Tab 10.1 2014 (SM-P600) Wifi Only, Stock Android 5.1.1

**Comment by iiordanov** [comment]
Closing since this appeared to be an issue with immersive mode. The plan is to remove immersive mode in the long-run at least when gesture system navigation is enabled.
