### ISSUE TITLE
Opaque : Cannot access menu while connected to a spice client on Proxmox

### ISSUE THREAD

**Issue by bapumpkin** [iiordanov/remote-desktop-clients#106]
Hello,
       Really find the app very useful 👍. Thanks for creating it.

Android 7.0
Opaque Version 1.4.3
On a Samsung Galaxy S2 Tab
Connected via a SSH tunnel to a Proxmox server
Swipe in from the right and see the keyboard icon and an icon with 3 dots. When I tap on the 3 dots, nothing happens, no menu appears.

Thanks for any assistance,
Cheers,
Everett

**Comment by iiordanov** [comment]
This should not be an issue anymore. Please reopen if it is, and update the OS and device you're seeing this on.
