### ISSUE TITLE
Hacker's Keyboard arrow keys move mouse (not cursor)

### ISSUE THREAD

**Issue by BlueMax** [iiordanov/remote-desktop-clients#111]
When using 'Hacker's Keyboard' arrow keys on Android6 with x11vnc it moves the mouse pointer by 1 pixel instead of moving the cursor. Using the '-debug_keyboard' option on x11vnc shows that no keyboard command arrives at the server indeed. The 'extra keys' arrow keys of bVNC do work properly though.

**Comment by iiordanov** [comment]
There is a setting to control this in Advanced Settings for each
connection. It is per-connection at present.

**Comment by BlueMax** [comment]
Thanks, works.
