### ISSUE TITLE
aRDP screen sharing

### ISSUE THREAD

**Issue by m-dp** [iiordanov/remote-desktop-clients#114]
Is it possible with aRDP to connect to the original, ongoing session of the RDP server? 
This would be meant to share keyboard and mouse of the server. It makes sense when you are duplicating the screen on a different physical display. 
This would be like using `mstsc /console` on older systems

**Comment by iiordanov** [comment]
You should install a VNC server and use bVNC for that. :)

Iordan

**Comment by m-dp** [comment]
Of course! But the entire matter is, my tests with VNC (chiefly `x11vnc` - I use a Linux XFCE desktop) show a very high delay between "remote" screen updates and "local" update. I am testing different solutions (and I am also trying to optimize a VNC configuration). 
RDP is in general faster, and it does support mirroring, but it does not do mirroring by default. This said, I reported for completeness - I do not really use Windows, so RDP is not a personal concern : )

**Comment by iiordanov** [comment]
Yes, x11vnc is not the fastest out there. I find Vino much more performant,
actually.

Iordan

**Comment by iiordanov** [comment]
Closing as this feature request is impossible with RDP.
