### ISSUE TITLE
Vibration on mouse-drag

### ISSUE THREAD

**Issue by Alloc86** [iiordanov/remote-desktop-clients#118]
Hi,

is there any way to disable the vibration feedback you get when you touch a position for a moment that indicates a mouse drag operation is starting? Especially during the night when other people are sleeping that little vibration noise can be very disturbing :)

Regards,
Chris

**Comment by iiordanov** [comment]
Hey, Chris, The latest version in production (v5.0.1_115019 in advanced settings) has a much-improved vibration that cannot wake up anybody in any room at any time of the day. Please test and reopen if you disagree :)
