### ISSUE TITLE
Android 4.4, aSPICE OOM issue

### ISSUE THREAD

**Issue by isavagee** [iiordanov/remote-desktop-clients#120]
Hi iiordanov,

I am working on porting aSPICE client into an Android 4.4 box.
The box has:
CPU - 4 cores A53
RAM - 1GB DDR3
The android box works as client, the server is X86 based virtual machin running Windows 7.

the whole build of aSPICE is not perfect but ok, now I'm testing it about video playing based on software decoded mjpeg. The codec works just fine, but as time goes by, the aSPICE apk will be killed by OOM, which I attach some log from TOP as follow, which can tell that the aSPICE's RSS/VSS is growing until it kill adbd first, then itself.

------------------------
 PID   PR CPU% S  #THR     VSS     RSS PCY UID      Name
 5438  3   0% S    16 554380K  42728K  fg u0_a25   com.iiordanov.aSPICE
 5438  1   3% R    18 538380K  43144K  fg u0_a25   com.iiordanov.aSPICE
 5438  0  17% S    29 698272K  88712K  fg u0_a25   com.iiordanov.aSPICE
 5438  3  30% S    29 707752K  99684K  fg u0_a25   com.iiordanov.aSPICE
 5438  3  29% S    29 708624K 100804K  fg u0_a25   com.iiordanov.aSPICE
 5438  2  27% R    29 710916K 103156K  fg u0_a25   com.iiordanov.aSPICE

....after a period of time, about 15 minutes in my case

 5809  0  28% R    27 1228728K 596328K  fg u0_a25   com.iiordanov.aSPICE
 5809  0  33% S    27 1230244K 595024K  fg u0_a25   com.iiordanov.aSPICE
 5809  0  34% R    27 1238788K 595180K  fg u0_a25   com.iiordanov.aSPICE
 5809  0  34% S    27 1231320K 596064K  fg u0_a25   com.iiordanov.aSPICE
 5809  3  30% S    27 1231840K 596468K  fg u0_a25   com.iiordanov.aSPICE
 5809  0  34% R    27 1233352K 598068K  fg u0_a25   com.iiordanov.aSPICE
 5809  3  34% S    27 1234528K 596128K  fg u0_a25   com.iiordanov.aSPICE
 5809  0  35% S    27 1233964K 594456K  fg u0_a25   com.iiordanov.aSPICE
 5809  0  33% R    27 1235408K 594692K  fg u0_a25   com.iiordanov.aSPICE

adbd is killed by OOM first
-------------------------

But the Android system and the virtual machine on the server side are both working, you can just re-connect and continue playing until next OOM.

Hope I express myself, if you need more detail just let me know.

Thanks

**Comment by isavagee** [comment]
i make a chart for the growth of memory usage
![android oom](https://user-images.githubusercontent.com/8478833/33070672-c92a5100-cef3-11e7-8062-d1ce481944a3.JPG)

**Comment by iiordanov** [comment]
Hello,

Do you have any indication whether the memory leak is in the Java layer or
in libspice?

Thanks!
Iordan

**Comment by isavagee** [comment]
Hi,

Thanks for your quick reply.

I am using "dumpsys meminfo com.iiordanov.aSPICE " and only see that the Navtive heap is regularly increasing, 

>  Uptime: 144638 Realtime: 144638
> 
> ** MEMINFO in pid 2705 [com.iiordanov.aSPICE] **
>                    Pss  Private  Private  Swapped     Heap     Heap     Heap
>                  Total    Dirty    Clean    Dirty     Size    Alloc     Free
>                 ------   ------   ------   ------   ------   ------   ------
>   Native Heap    92562    92520        0        0    94024    92697      806
> <omitted， after about half min>
>   Native Heap    92710    92668        0        0    94024    92761      886

  


![android oom1](https://user-images.githubusercontent.com/8478833/33109334-e0ad70c2-cf7b-11e7-8657-451c42d48c41.JPG)


thanks

**Comment by iiordanov** [comment]
Hey,

This probably means that we are up for an upgrade of libspice.

Thanks!
Iordan

**Comment by iiordanov** [comment]
There have been many updates to libspice since this issue was open. Please reopen if it's still a problem.
