### ISSUE TITLE
main channel closed

### ISSUE THREAD

**Issue by 123zzl321** [iiordanov/remote-desktop-clients#121]
Hi iiordanov,
what happens would cause  "main channel closed". 
when aspice is running succesfully,a few minutes later ,the aspice closed and show the log "main channel closed",i was confused about what you said :"this event is only sent if the channel was succesfully opened before". this event is sent by service or client.i was tormented by this for few days.Thank you very much.

**Comment by iiordanov** [comment]
Without looking too deeply into this it sounds like something interrupt
your network connection. Maybe your device momentarily disconnects and
reconnects?
