### ISSUE TITLE
bvnc video has sepia tone

### ISSUE THREAD

**Issue by AmritaTakken** [iiordanov/remote-desktop-clients#123]
Hi am using this library as a sample project and it has built ok and was able to stream video to android.
But the video seems to have a bit of sepia tone can anybody suggest what could be the issue 

![img_20171218_115530603](https://user-images.githubusercontent.com/2580985/34092835-66c92b00-e3eb-11e7-8e99-74d71058734f.jpg)
![img_20171218_115555087](https://user-images.githubusercontent.com/2580985/34092839-697b1fb6-e3eb-11e7-9c85-b9b855412a4e.jpg)

**Comment by iiordanov** [comment]
Are you sure it is not due to the Android device itself or even more
likely, due to monitor settings?
