### ISSUE TITLE
Pressure sensitivity

### ISSUE THREAD

**Issue by m-dp** [iiordanov/remote-desktop-clients#126]
I see that there is interest in having remote desktop clients recognize pressure sensitivity, by users that wish to use tablets as remote drawing devices but on desktop applications. 

Is that possible?

**Comment by iiordanov** [comment]
I don't believe VNC, RDP, or SPICE remote desktop protocols support sending
pressure to the remote computer.

If you have information to the contrary, please let me know.

Thanks!
Iordan

**Comment by m-dp** [comment]
Thank you Iordan, 
I read the relevant parts (I hope all) in RFC 6143; it seems to me that "Client-to-Server Messages" (§ 7.5) should be augmented with a new 'AdvancedPointerEvent' which can include Pressure sensitivity, to join the present "message number 5: PointerEvent". 
The document is from 2011, by Richardson and Levine, I suppose they could be contacted (very easily, at iesg 'at ietf.org) to inquiry about this. 
I think I probably will - please note that it started as an intellectual curiosity, not a personal need. But I will take the liberty to inform you in case I get a feedback that the RFC will be expanded (as I think it should).

**Comment by tamsky** [comment]
> I don't believe VNC, RDP, or SPICE remote desktop protocols support sending
> pressure to the remote computer.

I believe the protocol may now support it through the General Input Interface (gii) protocol extension.  @ https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#input-protocol

> The gii extension is used to provide a more powerful input protocol for cases where the standard input model is insufficient. It supports relative mouse movements, mouses with more than 8 buttons and mouses with more than three axes. It even supports joysticks and gamepads.

- https://vncdotool.readthedocs.io/en/0.8.0/rfbproto.html#gii-pseudo-encoding

and the device creation function would appear to support creating gii devices with both pressure and tilt unit values:

- https://vncdotool.readthedocs.io/en/0.8.0/rfbproto.html#device-creation

Number | SI-unit | Description
-- | -- | --
6 | rad | angle
13 | N/m^2 (Pa) | pressure

**Comment by tamsky** [comment]
Re-asking the question since more than 5 years have elapsed...

I'm curious if any of the clients in this repo have support for sending pressure/tilt from capable input devices (eg wacom pens)?
