### ISSUE TITLE
bVNC - Regression: Right mouse button behavior (back key, two-finger gesture)

### ISSUE THREAD

**Issue by BlueMax** [iiordanov/remote-desktop-clients#128]
Since last version the right-mouse-button behavior changed. When pressing the hardware "back" key the right mouse button will be triggered properly. But once you touch the screen (for moving the mouse) an unintended left click follows and context menus and such vanish. Proper operation is not possible.

When using two-finger gesture to trigger RMB the context menu pops up properly but when you try to move the mouse pointer afterwards nothing happens. You have to leave/untouch the display once more. Then it works. In other words, there is always a null operation after the two-finger RMB gesture.

bVNC v3.9.7 LOS13/Android6 (01/2018) Galaxy S4-LTE (I9506)
x11vnc v0.9.14 XFCE ArchLinux 4.14.15

**Comment by iiordanov** [comment]
Hi, I've released a fix for this in Beta. Can you please confirm that it works fine for you now?

Please reopen if not.

Thanks!
iordan

**Comment by iiordanov** [comment]
I realized I should add the link to opt into Beta:
https://play.google.com/apps/testing/com.iiordanov.freebVNC

Thanks!
iordan
