### ISSUE TITLE
Hardware menu button does not work anymore

### ISSUE THREAD

**Issue by m-dp** [iiordanov/remote-desktop-clients#129]
I just tried public 3.9.9: in the past version I was using (which should be 3.9.1, April 2017) the menu button (which on several of my devices equates to a long press on the "task switch" button) opened, as expected, the menu. With 3.9.9, the hardware menu does nothing and the menu only appears through the "three dots" icon at the right edge of the screen.

**Comment by iiordanov** [comment]
Does the on-screen three dots menu work for you, though?

**Comment by m-dp** [comment]
Yes, the overlayed button on the screen works. The hardware button (long press of the "Task Switch" capacitive button on my system) does not open anything.
