### ISSUE TITLE
Feature request - Negative colors

### ISSUE THREAD

**Issue by m-dp** [iiordanov/remote-desktop-clients#130]
I just found that the "quick invert" I use on my desktop ( `xcalib -i -a` ) does not reflect on the VNC client. 
I suppose that the VNC server (x11vnc) is not reacting to that - presumably the color inversion occurs "later". 

Maybe we could have the option to invert the colours on the remote desktop clients? 

It has its importance because it is something one changes both according to contextual eye preference, and because every display (your VNC terminal) has its preferential setting - for example, using OLED you in general want to have light foreground and black backgrounds.

**Comment by iiordanov** [comment]
Is there no app on Google Play that can invert colors? It somehow seems not
the immediate concern of a VNC client.

Iordan

**Comment by m-dp** [comment]
You are probably right Iordan, it is not fully clear where the feature should be and probably not in the VNC client. 
There are the two other solutions of 
-- the terminal (inverting colours on Android) and 
-- the server (it should be trivial to modify x11vnc). In fact, the server is not reflecting what is happening on the desktop. 

But there is one argument in favour of having it in the client: using the option on Android makes you leave the remote desktop environment, breaking the flow (but one adjusts colours in real time during operation), and having it in the server means having a control interface while the server is running, which I am not sure exists; on the other hand, the terminal is what you use for input - for control in general -, so that's where you would change a visualization. Food for thought. 

Nonetheless, it is not paramount, since the function on Android is already available.
