### ISSUE TITLE
Error when trying to connect to home vnc server

### ISSUE THREAD

**Issue by ngx3** [iiordanov/remote-desktop-clients#132]
Hello,

I get this error every time I try to connect to my home vnc server, I googled the errors with no findings of what they mean, so I'm guessing maybe it's the app?

![screenshot_20180326-093121](https://user-images.githubusercontent.com/16364958/37910368-596ea79a-30db-11e8-8d94-920b22e4648a.png)

**Comment by iiordanov** [comment]
Connection refused means that the host is reachable, but it is not possible
to connect to the VNC server on it.

This could be the result of a firewall blocking the connection or the VNC
server not running or listening on a different port.

Sincerely,
Iordan
