### ISSUE TITLE
12 is less than minimum platform for arm (14)

### ISSUE THREAD

**Issue by Mitaxing** [iiordanov/remote-desktop-clients#136]
Hi,Can you help me with this problem? I've been beating my brains out with it, but I just can't solve it.thanks!

**Comment by iiordanov** [comment]
It sounds like all you need to do is change a couple of Android target
parameters from 12 to 14.

Searching through the repository:

1) Opaque/jni/Application.mk
-->  APP_PLATFORM := android-12

2) Opaque/jni/libs/build-deps.conf
--> android_api="12"

Cheers!
iordan
