### ISSUE TITLE
bVNC 4.0.1 authentication failure on Bitvise ssh 7.44 

### ISSUE THREAD

**Issue by vradoslavov** [iiordanov/remote-desktop-clients#140]
Upgrading to "bVNC" client running on Android to version 4.0.1 makes it impossible to log on to the my home server. I use  Windows 10 , with "BvSshServer 7.44". Authentication is a user without password and with SSH key. With version 3.9.9 of "bVNC" works without problems without changing the key and the username.

**Comment by iiordanov** [comment]
Between 3.0.9 and 4.0.1 there was a major upgrade of the ssh library used
for tunneling. Many people reported the need to re-segup their connections
due to the library reporting the host key in a new format...

If you set up the connection again, does it not work?

Iordan
