### ISSUE TITLE
bVNC: scaling, allow fit to screen width/height

### ISSUE THREAD

**Issue by Gia90** [iiordanov/remote-desktop-clients#141]
Right now the scaling option "Fit to Screen" seems to automatically pick the longest dimension between width and height of the remote resolution to fit the remote screen in the viewer.

It would be useful to have a "Fit to Screen Width" and "Fit to Screen Height" option, for example when using the "-ncache" feature of x11vnc, which makes the original remote desktop taller and uses the extra framebuffer for caching pixel data (http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching).

In this specific use case, it would be also nice to be able to block the panning of the remote screen.

Thanks for your work :)

**Comment by iiordanov** [comment]
The option -ncache is not supported and there are no plans to do so.

The issue of fit-to-screen picking a dimension was fixed and the remote image is now centered.

Please let me know if I misunderstood the bug report and I'll reopen.
