### ISSUE TITLE
bVNC SD card access issue using Xiaomi Mi A1 (MDG2) running Android 8.1.0, kernel version: 3.18.71-perf-gb3363e5

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [iiordanov/remote-desktop-clients#142]
Despite the fact that bVNC does have all it's permissions allowed, every time I try to export configuration to my external SD card, bVNC refuses the valid and writable path with this message: 

"Error! 

I/O Exception exporting config:/storage/0556-C258/settings.xm| (Permission denied)"

**Comment by iiordanov** [comment]
This was certainly due to permissions.
