### ISSUE TITLE
some build error with

### ISSUE THREAD

**Issue by pkyesu** [iiordanov/remote-desktop-clients#144]
I follow the building instruction 
./build-deps.sh -j 4 -n /usr/android-ndk-r14b/ build

but there is some error like this:

root/workspace/bak/remote-desktop-clients-master/Opaque/jni/libs/deps/armeabi-v7a/toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/workspace/bak/remote-desktop-clients-master/bVNC/jni/libs/deps/armeabi-v7a/gstreamer/lib-fixed/libgobject-2.0.a(libgobject_2_0_la-gmarshal.o): multiple definition of 'g_cclosure_marshal_VOID__VOID'
/root/workspace/bak/remote-desktop-clients-master/Opaque/jni/libs/deps/armeabi-v7a/toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: ../libsoup/.libs/libsoup-2.4.a(soup-marshal.o): previous definition here
/root/workspace/bak/remote-desktop-clients-master/Opaque/jni/libs/deps/armeabi-v7a/toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/workspace/bak/remote-desktop-clients-master/bVNC/jni/libs/deps/armeabi-v7a/gstreamer/lib-fixed/libgobject-2.0.a(libgobject_2_0_la-gmarshal.o): multiple definition of 'g_cclosure_marshal_VOID__BOXED'
/root/workspace/bak/remote-desktop-clients-master/Opaque/jni/libs/deps/armeabi-v7a/toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: ../libsoup/.libs/libsoup-2.4.a(soup-marshal.o): previous definition here

It confuse me so long

**Comment by iiordanov** [comment]
This should now no longer be an issue due to updates in the build system.
