### ISSUE TITLE
question about dependecy handling reusability

### ISSUE THREAD

**Issue by Mis012** [iiordanov/remote-desktop-clients#145]
hi,
I'd like to ask about remote-desktop-clients/Opaque/jni/libs/. I can't find anywhere on the internet what the right way to integrate stuff like libsoup into and android application is. I can cross-compile library after library manually, and then make a script to automate that, but that doesn't seem suited for applications intended to be built using gradle etc.
Could you please tell me if your system is reasonably reusable, or what the *right* way is?
Thanks in advace

**Comment by iiordanov** [comment]
Please read the BUILDING file in the repository. It gives you instructions
on how to trigger a build of all dependencies.

It requires a Linux build environment.

Cheers!
Iordan

**Comment by Mis012** [comment]
What I am asking is if I can easily use your dependency handling in my own project, or what is the right way to use libsoup etc. in an android project.

**Comment by Mis012** [comment]
What I am asking is if I can easily use your dependency handling in my own project, or what is the right way to use libsoup etc. in an android project.

**Comment by iiordanov** [comment]
The new build system uses cerbero and scripts building of all remaining dependencies.
