### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by renatocan** [iiordanov/remote-desktop-clients#148]
Hi,

Great app! I think it should be included in [F-Droid](https://f-droid.org/) repo. I can submit it but I need your consent. Is it ok for me to submit the app?

Thanks,

Renato.

**Comment by colbycdev** [comment]
The free version is in f Droid. This issue should be closed

**Comment by DJCrashdummy** [comment]
@alexa-v2 no, it is unfortunately not!

...but this issue is a duplicate of #70.

**Comment by iiordanov** [comment]
Closed since it's a duplicate.
