### ISSUE TITLE
port-scan and auto connect from chromebooks

### ISSUE THREAD

**Issue by popebear** [iiordanov/remote-desktop-clients#149]
We're using this application on a chromebook in order to connect to a raspberry pi running vnc.
We'd really like to add a feature where bvnc runs in the background periodically scanning eth0 to check and see if there's a VNC server available on a certain network, and if it is, it launches vnc connected to the server. 

We're happy to pay for the development.  Would be prepared to discuss such a feature?

**Comment by iiordanov** [comment]
Hello, please get in touch with me by email for further discussion. iiordanov at gmail com.
