### ISSUE TITLE
bVNC SSH key authentication issue with OpenSSH 7.9 server

### ISSUE THREAD

**Issue by jcj83429** [iiordanov/remote-desktop-clients#153]
Hi,

I'm having trouble using SSH keys in bVNC to connecting to Arch Linux and Debian Testing servers running OpenSSH 7.9. The ssh server log is here: https://pastebin.com/H9HWkEwR

The problem seems to be this line:
debug3: mm_answer_keyverify: publickey 0x55f5fd9c9b10 signature unverified

On Ubuntu 18.04 running OpenSSH 7.6, the signature verifies successfully.

I looked around on the internet and it may be caused by a change done in OpenSSH 7.8 (https://www.openssh.com/txt/release-7.8)

 * ssh(1): ensure that the public key algorithm sent in a
   public key SSH_MSG_USERAUTH_REQUEST matches the content of the
   signature blob. Previously, these could be inconsistent when a
   legacy or non-OpenSSH ssh-agent returned a RSA/SHA1 signature
   when asked to make a RSA/SHA2 signature.

It looks like bVNC uses the connectbot SSH library version 2.2.6. Connectbot added support in https://github.com/connectbot/sshlib/commit/a80388878f7827751e2c3f5ec304102d472fe2ea, which is after 2.2.6. Maybe a sshlib update will fix this issue.

**Comment by iiordanov** [comment]
Please join the bVNC beta where the client is built with sshlib 2.2.9 and
let me know if it is fixed.
