### ISSUE TITLE
Cannot decrypt rsa key: rdp over ssh

### ISSUE THREAD

**Issue by linuxandria** [iiordanov/remote-desktop-clients#158]
I use a password protected key to rdp over ssh in aRDP pro, and when I click import after entering the correct passphrase, it insists it is wrong

I know I have the password right; it works in two other apps(termius and termux) and openssh on Windows 10

I'm using the latest beta from the play store

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by iiordanov** [comment]
Does generating a passphrase protected key on device work as expected?

Iordan

**Comment by colbycdev** [comment]
It works, but I can't get it onto my server (needs to be in .pub format)

**Comment by iiordanov** [comment]
Sure you can!

When you use the Copy to Clipboard or Share buttons, the format is OpenSSH
pub key format. All you need to do is paste it into authorized_keys.

**Comment by alexa-v2** [comment]
That'd require access to the server
Which requires my key lol

**Comment by alexa-v2** [comment]
BTW issue still present in latest beta

**Comment by alexa-v2** [comment]
Keys generated via ssh-keygen -t rsa in termux still not working

Haven't tested unencrypted keys but encrypted ones definitely don't work

**Comment by iiordanov** [comment]
This issue should be resolved in the newest version of the apps.
