### ISSUE TITLE
spice hd audio not supoort why? ac 97 can listen .

### ISSUE THREAD

**Issue by jaydon** [iiordanov/remote-desktop-clients#161]
spice hd audio not supoort why? ac 97 can listen .

**Comment by iiordanov** [comment]
I am not sure what you mean.

**Comment by jaydon** [comment]
Tanks for your answer.In coumputer audio setting, I chose Realtek AC'97 Audio ，I can listen music. but I chose High Definition Audio, I can not listen music. AC'97 will be eliminated by High Definition Audio .

**Comment by iiordanov** [comment]
If this is still an issue, I suggest contacting the spice-devel mailing list with your question. You can cc me on the communication at iiordanov at gmail.
