### ISSUE TITLE
Error after aRDP Disconnect

### ISSUE THREAD

**Issue by hjgode** [iiordanov/remote-desktop-clients#163]
Current aRDP build (used prebuild libs) shows an error after normal Logoff on Terminal Server (Windows 2016 R2) . The expected behavior is that aRDP just shows the activity as this was a normal logoff and no connection lost.
  
![Error_after_Logoff](https://user-images.githubusercontent.com/3365637/55220493-b10a4600-5207-11e9-9873-de76e74520ad.png)

**Comment by iiordanov** [comment]
Please reopen if this is still an issue, but from aRDP's perspective, the server closed the connection so it thinks the connection was interrupted.
