### ISSUE TITLE
Couldn't follow symbolic link.

### ISSUE THREAD

**Issue by maxifjaved** [iiordanov/remote-desktop-clients#164]
I am trying to build from prebuilt libraries but it shows the error but it throw the error 

ON LINUX
> Could not list contents of '/remote-desktop-clients/bVNC/src2/main/jniLibs/x86_64'. Couldn't follow symbolic link.

ON MAC
> Could not list contents of '/remote-desktop-clients/bVNC/src2/main/jniLibs/arm64-v8a'. Couldn't follow symbolic link.

**Comment by iiordanov** [comment]
Is this a build of the master branch?

What happens if you just delete these directories?

Iordan

**Comment by maxifjaved** [comment]
Yes it is master branch

**Comment by iiordanov** [comment]
Then just delete these directories, since there is no 64bit support in
master yet.

**Comment by maxifjaved** [comment]
Thanks. It running successfully, after deleting the directories.
