### ISSUE TITLE
Error while building the project

### ISSUE THREAD

**Issue by maxifjaved** [iiordanov/remote-desktop-clients#167]
![issues_screen_shot](https://res.cloudinary.com/maxifjaved/image/upload/v1557032992/issues_screen_shot/Screen_Shot_2019-05-05_at_9.58.47_AM.png)

I am trying to build the project from prebuilt dependency but it is throwing me the error. I am not sure why is it. Please help to run it on my machine. 

Thanks.

**Comment by iiordanov** [comment]
This should no longer be an issue with the latest prebuilt libraries. Please reopen if it is.
