### ISSUE TITLE
Pasting leaves out the last character

### ISSUE THREAD

**Issue by marnix409** [iiordanov/remote-desktop-clients#168]
Every time I paste something from other apps on my phone onto the rdp, it leaves out the last character.

To reproduce this issue: 
1. Copied "Water" from the android firefox app
2. Tried pasting it onto my rdp's browser/explorer (doesn't matter which app), but the last character never gets added. (Pastes "Wate")

This issue occured on my Samsung Galaxy S8+ and my Galaxy S10+, on the free version as well as the paid version.

Issue #2: I cannot copy any large text (i.e 100000 lines). It crashes the app, even though I have a 12GB ram phone

**Comment by iiordanov** [comment]
Is this still an issue?
