### ISSUE TITLE
access ubuntu machine when not yet logged in

### ISSUE THREAD

**Issue by adzweig** [iiordanov/remote-desktop-clients#170]
Hi

I would like to remotely control my ubuntu 18.04 from an Android 8.1 using bVNC via VNC over SSH. If I am logged in locally on the ubuntu machine, then bVNC works nicely. However when I am not logged in locally I cannot get the link to work. Can this be achieved at all, and if yes, how?

thanks for any advice on this topic

Adrian

**Comment by iiordanov** [comment]
Hey,

There are two options:

1) If you are a sudoer on the system, you can enable the AutoX feature
(Configure AutoX button) and select the "Find X Login" mode. You may need
to reconnect to get the session after login, I am not sure.

2) If that doesn't work for some reason,  or you want to use other VNC
clients too, you can do what the 2nd answer suggests here:

https://askubuntu.com/questions/1035598/ubuntu-18-04-lts-x11vnc-no-longer-works

I.e. run two x11vnc sessions, one for the login screen and one for the
session. You will need to have two separate connections for each.

Cheers,
Iordan

**Comment by bvandenbon** [comment]
> I would like to remotely control my ubuntu 18.04 from an Android 8.1 using bVNC via VNC over SSH. If I am logged in locally on the ubuntu machine, then bVNC works nicely. However when I am not logged in locally I cannot get the link to work. Can this be achieved at all, and if yes, how?

If your intention is to use it to study baduk using Lizzie on your android phone, then I really think that you may be better of with https://www.zbaduk.com
