### ISSUE TITLE
Back button holds right mouse button instead of clicking in bVNC

### ISSUE THREAD

**Issue by bpsib** [iiordanov/remote-desktop-clients#174]
Pressing the back button in bVNC for right-click holds it causing it to get "stuck" down. Pressing back should click rather than hold. It works if I 2 finger tap but response can be intermittent.

**Comment by pesa1234** [comment]
I have the same issue, how to solve?

**Comment by iiordanov** [comment]
I think I reproduced this issue, I'll add it to the list to look at.

**Comment by iiordanov** [comment]
Fixed in latest beta on Google Play (v4.1.0).

**Comment by pesa1234** [comment]
It works!
Thanks
