### ISSUE TITLE
Add the "Sign In" feature and "Natural Scrolling" feature in BVNC Free app

### ISSUE THREAD

**Issue by ammarraisafti** [iiordanov/remote-desktop-clients#177]
# Components
Bvnc free is an open source application that is safe to use, multi-touch VNC, free, client for Windows, Linux, Mac with SSH, and this is amazing and useful for users.  There are several important features that can be used by users, but unfortunately after using this application, I did not find the "Sign In" feature and the "Natural Schrolling" feature in the application.  So it aroused my interest to suggest both features to the BVNC Free application developer.  

<code>This suggestion comes because, I want to connect to the computer easily and quickly, also to improve the quality and functionality of the application in the future.</code>

The following are the feature components that I want to recommend:

- Sign In
- Natural Schrolling

# Proposal description
When users want to access their computers, users must first sign in using their free BVNC account.  For the sake of convenience and security, also to connect to the computer easily and quickly.  Therefore, I would like to propose the BVNC Free application developer to add the "Sign In" feature at the top of the app's main display, and provide notifications to users to enter a free BVNC account before accessing their computer. 

Also, so that this application is more functional when used, I would like to propose the BVNC Free application developer to add the "Natural Schrolling" feature in the Show Advanced Settings section, and provide information to users about the functionality of the feature.  After users activate this feature, they must be able to move content up, and deactivate upward movement to move content down.

# Mockups / Examples
The following is an example illustration after the developer adds two new features in the BVNC Free app.
![Screenshot_20180224-004646-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519408172/b1ktkzzibn4s9j0i21fc.png)

![Screenshot_20180224-004646-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519409900/ee1m5b0myacmpuhjazpp.png)

![Screenshot_20180224-004646-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519409946/qoyebe5moty4d7lhthpx.png)

![Screenshot_20180224-001745f.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519410180/fygwrjpkphfi3gtz4tte.png)

![Screenshot_20180224-001745kk.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519410642/uhm8xivzk5ph4beo6rvn.png)

# Benefits
After the developer adds the "Sign In" feature in the BVNC Free application, which is placed at the top of the main display of the BVNC Free application.  Users can connect to their computers easily and quickly, and get better security and comfort than before.  Users can access their computers only by using the "Sign In" feature provided by the developer, after the user enters their email and password, the computer will immediately be connected.  And that is a big advantage.

And after the developer added the "Natural Schrolling" feature in the Free BVNC application, users can activate that feature to move content, and deactivate the upward movement feature to move content down.  And that is a very interesting thing to do, so users feel very happy with the presence of these two features.  I am sure, after these features are implemented into the application, it will have a very large and significant effect on the progress of the application.  And users of this application will increase in the future.

**Comment by iiordanov** [comment]
Thank you for your feedback. The scroll mode is already "natural" in the sense that pulling up with two fingers causes the window content to scroll down (i.e. get pulled up) and pulling down with two fingers causes window content to scroll up (i.e. get pulled down).

The other feature is completely out of the scope of this application as it involves server infrastructure which would proxy connections to users' computers.
