### ISSUE TITLE
Add the "Shake" feature in the "BVNC Free" app to make it even more interesting to use

### ISSUE THREAD

**Issue by ammarraisafti** [iiordanov/remote-desktop-clients#178]
# Components
BVNC free is an open source application for android devices that works to connect users' computers with android devices securely. This app gives the user some choice of features in it, but after using this app, I do not find any interesting feature in BVNC Free app.

Because I use this application very often, and I really enjoy it.  So I will give a good suggestion for this application.

The following are the feature components that I want to recommend:

- Shake

# Proposal description
Propose interesting features in the "BVNC" Free app.

- Add the "Shake" feature in the BVNC Free app in the application toolbar's shortcut section.

- The developer must modify the "Shake" feature section to give users two feature options when the user accesses the shake feature, which is the "Shake" option and the "Shake Sensitive" feature.

- The developer must modify the two sections to provide some interesting options, which gives the user multiple options when the user accesses the "Shake" feature. Like disabled options, increase font size, decrease font size, close, hide, backspace, ESC, Enter, CTRL, ALT, Tab, Space, Ctrl + C, Ctrl + X, Ctrl + Z, Ctrl + L. 

- And developers should give users the option to set Shake Sensitive, such as minimum options, very insensitive, normal sensitivity, very sensitive, and maximum.

# Mockups / Examples
- An example image after the developer adds a "Shake" feature in the BVNC Free app in the toolbar shortcut section of the application.
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520238040/dqxi2vdr0zquodjljyad.png)

- An example of a picture when a user accesses the "Shake" feature and gets two options in that section.
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520238501/vpw2v0tmhqsowdu5upwf.png)

- An example of a picture when a user accesses the "Shake" feature to set up a command in shake. 
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520238665/cq2u2olkzypfporshcki.png)

- Example of a picture when the user accesses the "Shake Sensitive" feature to set sensitively during shake.
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520238812/jmxybhg4atpwe46oh5bb.png)

# Benefits
The presence of the "Shake" feature in the BVNC Free app will make this app even more interesting to use, as BVNC Free app users allow to give commands when users connect to their computers with just "Shake" android devices. Users can set the command as desired when "Shake", such as choose to Disabled, increase font size, decrease font size, close, hide, backspace, ESC, Enter, CTRL, ALT, Tab, Space, and many others can be done by the user. And that's amazing. Users can also adjust the level of sensitivity when "Shake" in accordance with the desired, such as choosing minimum shake levels, very insensitive, normal sensitivity, very sensitive, and maximum. And that's a big advantage for BVNC Free app users, so users will boast against other users, because the BVNC Free app they use, has great and interesting features in it.

**Comment by iiordanov** [comment]
Apologies, but I don't think I would want to add this capability! :)
