### ISSUE TITLE
Can only access PC in same network in LAN ..how to access PC which is out of network

### ISSUE THREAD

**Issue by HarshalShende** [iiordanov/remote-desktop-clients#194]

**Comment by iiordanov** [comment]
You generally have to forward a port from your router to the computer that
is running VNC or RDP (you didn't specify which client you are talking
about).

When connecting over the internet it is highly advisable to use an SSH
tunnel. For that purpose, you would install OpenSSH (available on Linux,
Windows and Mac OS), and would forward an external port to Port 22 of the
machine.

The description of each client has some links to possible setup choices.
Also I can point to a blog post if you indicate which client you are using.

Iordan

**Comment by HarshalShende** [comment]
I am using bVnc client  and tried the same client android vnc viewer but the same problem exists there suggest me steps or documentation to connect to pc out of network

**Comment by iiordanov** [comment]
I hope this answer I have given a while back helps.
https://groups.google.com/forum/#!topic/bvnc-ardp-aspice-opaque-remote-desktop-clients/lycZiJfyfGQ
