### ISSUE TITLE
Crash app on Android 8

### ISSUE THREAD

**Issue by Savory0** [iiordanov/remote-desktop-clients#195]
Hello,

The application crashes randomly with the following error, after opening several windows in VNC quickly.
APK Version : 4.8.0
Server Version : tigervnc-server-1.8.0-5.el7.x86_64

W/Bitmap: Called getHeight() on a recycle()'d bitmap! This is undefined behavior!
A/Bitmap: Error, cannot access an invalid/free'd bitmap here!
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7606 (.iiordanov.bVNC), pid 7606 (.iiordanov.bVNC)

Do you have an idea ?
Thanks.

**Comment by iiordanov** [comment]
You mean APK Version 4.0.8?

**Comment by iiordanov** [comment]
I tried to reproduce this on an emulator running Android 8 and I cannot.

Can you please get in touch by email and send me the text that you obtain when you tap "Copy Logcat" (at the bottom of the connection screen) after bVNC crashes and you relaunch it, please?

iiordanov _at_ gmail

Thanks!

**Comment by iiordanov** [comment]
Hey, I don't have an Android 8 device to test with, please try the latest 5.0.0 beta and reopen if this is still happening. Many changes were made that may or may not help with the issue.
