### ISSUE TITLE
how to build bVNC for iOS

### ISSUE THREAD

**Issue by tristan-k** [iiordanov/remote-desktop-clients#203]
I noticed you released a version of bVNC in the [AppStore](https://apps.apple.com/de/app/bvnc-pro/id1506461202), but there seems to be no documentation available on how to build it from source.

**Comment by iiordanov** [comment]
It's in a branch still.

Iordan

**Comment by tristan-k** [comment]
Thanks. My bad should have looked into branches before opening up an issue. Is there a testflight or free version available and will there be ports for rdp and spice?

**Comment by iiordanov** [comment]
Yeah, I can add you to test flight, of course. If there is interest in the
client, I may port RDP and SPICE as well, but no immediate plans.

**Comment by tristan-k** [comment]
Please add me to the testflight. There is only a [4 year old implementation](https://github.com/flexvdi/launcher-mobile) of a spice client available. I would certainly be interested 😗

**Comment by iiordanov** [comment]
Please get in touch by email with me at iiordanov gmail, as I need your
email address.
