### ISSUE TITLE
Volume buttons no longer scroll

### ISSUE THREAD

**Issue by bpsib** [iiordanov/remote-desktop-clients#205]
I have found in the latest bVNC beta (4.1.0) that the volume buttons no longer work to scroll. I can't be doing with using 2 fingers all the time to scroll.

**Comment by iiordanov** [comment]
Still scrolls for me in 5.0.0 beta. I'll need some much more extensive details on how to reproduce the issue. Closing for now - if it's still an issue for you, please reopen with details about your device.
