### ISSUE TITLE
what version of Android SDK can be used to build from scratch?

### ISSUE THREAD

**Issue by ligangcc** [iiordanov/remote-desktop-clients#206]
Does anyone can build successfully from scratch?

My compute is  CentOS 7.6,  I downloaded the newest Android SDK,  according to the  build instruction:

Accept all licenses (repeat if you see an error during build)
   ${ANDROID_SDK}/tools/bin/sdkmanager --license

but there is no sdkmanager , even no tools in SDK dir.

any suggestion is appreciated!!!

**Comment by iiordanov** [comment]
Hello, can you find some help on how to accept the licenses with:

https://stackoverflow.com/questions/38096225/automatically-accept-all-sdk-licences

Cheers!
iordan
