### ISSUE TITLE
Opaque project USB device cannot be redirected

### ISSUE THREAD

**Issue by bsle397** [iiordanov/remote-desktop-clients#211]
I run the opaque project on the arm development board, and the USB device cannot be redirected. Error reporting: File USB device manager. C: Line 1821 (probe_ isochronous_ endpoint): should not be reached。 How to deal with it?

**Comment by iiordanov** [comment]
Confirmed, this is because of selinux on newer Android versions. I've disabled the option as there is no plan to support USB redirection under the current tightly locked down conditions in modern Android.

**Comment by iiordanov** [comment]
Linking the fix for this issue here: https://github.com/iiordanov/remote-desktop-clients/issues/326
