### ISSUE TITLE
bVNC - Black border on top/bottom and blackout during use

### ISSUE THREAD

**Issue by tbjorheim** [iiordanov/remote-desktop-clients#219]
I have used bVNC on my older Samsung Galaxy Tablet (GT-P7320) for a long time, and it has worked very well. But after the last update (to v4.3.0), some problem has occured. First there is a black border on top and bottom when I use scaling mode "One to One". This is kind of annoying as the black border takes about 15% of the screen. Same issue when connecting both to two computers running Linux Mint and a Raspberry Pi running OSMC.

The other issue is that the screen suddenly turning black. I see the mouse pointer, but only move it around in the middle of the screen. If I reconnect, everything is okay again. But this issue only happens once in a while, not sure what causing it. Sometimes it happens right after I have connected (like 10-20 seconds), but other times it works for a longer period of time without the problem.

Have used bVNC a lot, and have never had this issue before, so I guess it must be related to the latest update to v4.3.0.

**Comment by iiordanov** [comment]
The black border is a feature that I do not plan to remove, as it is important for people with curved screens and allows one to tap the edges of the screen much more easily. In fact, I was thinking of allowing the screen to pan with a border to the left and right as well at some point. If you don't want borders taking up your space, why not use Fit-to-Screen scaling?

Thanks,
iordan

**Comment by tbjorheim** [comment]
I understand this is an important feature for people with curved screens, but is it possible to make an option in settings to turn this off, to make it work as before? I guess I'm not the only person who would like that. There is already an issue about it here:

https://github.com/iiordanov/remote-desktop-clients/issues/217

I have tried the Fit-to-screen scaling, but since the resolution on the computer I connect to is much larger than the screen on my tablet, the text gets very small, and is not usable for me this way.

If you are not planning to fix this, I think I will just need to stick to version v4.2 that works for me, and just ignoring the updates from Play Store. But is it possible to get an older version of the Pro version? For the free version I can just download from here, but I don't quite know how to downgrade the Pro version.

**Comment by iiordanov** [comment]
This not a bug report but a feature request. The feature request has been noted, and I'll close the bug report. Thanks!!
