### ISSUE TITLE
Number input generates special characters.

### ISSUE THREAD

**Issue by Fhugem** [iiordanov/remote-desktop-clients#220]
Number input generates special characters. 
Edit: I found out why it did that. My device keyboard is set to AZERTY, you should add support to change the input language.

Also removed my review on play store.

**Comment by iiordanov** [comment]
Hello,

I tried AZERTY soft-keyboard while connected to a Windows machine. On the Windows machine I tried both QWERTY and AZERTY layout just in case. In all cases, numbers produced numbers. You may have had Alt stuck or something else going on. If you still think this is an issue, please reopen and tell me how to reproduce this in more detail. Thanks!
