### ISSUE TITLE
Windows support Error

### ISSUE THREAD

**Issue by sword1202** [iiordanov/remote-desktop-clients#221]
HI
I tried to import the remote-desktop-clients on Android Studio of Windows 10.
And tried to run on emulator or physical device. But it says "Error running 'xxx-app': Default Activity Not found".
See this link.
https://prnt.sc/tmhwrv

Can I run it on windows system? or it does support on only Ubuntu?
Thanks

**Comment by sword1202** [comment]
Nobody comes here?

**Comment by iiordanov** [comment]
Hey, I come here :), but I've been busy working on v5.0.0 which is a major overhaul and took too long. The build system supports all OS's provided you do the docker-compose approach. Have you tried that?

https://github.com/iiordanov/remote-desktop-clients/blob/master/README.md
