### ISSUE TITLE
bVNC Pro / aSpice Pro lose password when put in the background

### ISSUE THREAD

**Issue by F-i-f** [iiordanov/remote-desktop-clients#231]
The most recent versions introduced a regression where the password is not remembered (and needs to be reentered) every time the app is put in the background.
aSpice Pro 5.0.1
bVNC Pro 5.0.1
Android Pie.

To reproduce:
- Start either apps.
- Make sure that the Master Password is not set.
- Connect to a session that needs password authentication.  I used:
  - Direct VNC Password for bVNC, Keep off.
  - No Spice password, Keep off, with SSH tunnel authenticated by ssh key, keep off.
- After the session is opened, open another app.
- Using Android's Recents, go back to to aSpice/bVNC.
- The password is asked again.

The 4.3.0 versions would keep the password in memory and wouldn't ask until the session was closed, or the app killed.

**Comment by iiordanov** [comment]
This is not because the password is lost but because there was a UI fragment left in the stack. You can just back out of this dialog without entering the password. There will be a fix out for this / is a fix already.

**Comment by iiordanov** [comment]
Fix is released in latest beta. In Advanced Settings at the bottom verify you have v5.0.3_115034 or later and there should be no more issues. @nkotixwolf
