### ISSUE TITLE
SpiceClientConnect

### ISSUE THREAD

**Issue by wqwqwqw3** [iiordanov/remote-desktop-clients#232]
No implementation found for int com.undatech.opaque.SpiceCommunicator.SpiceClientConnect

**Comment by wqwqwqw3** [comment]
I have spice.so.Does it need to be reprocessed

**Comment by iiordanov** [comment]
If you follow I-a, I-b, or I-c in the instructions here:
https://github.com/iiordanov/remote-desktop-clients/blob/master/README.md

 the file should be there.
