### ISSUE TITLE
Keyboard layout is forced to qwerty

### ISSUE THREAD

**Issue by Magissia** [iiordanov/remote-desktop-clients#238]
Hello, using an azerty keyboard, touching "a" produce "q" on remote host.

**Comment by iiordanov** [comment]
Hi Magissia,

Which app is this for? bVNC, aRDP, aSPICE or Opaque?

What are you using to produce this input? Hardware keyboard, soft-keyboard? If soft-keyboard, which keyboard app is it?

Thanks!

**Comment by iiordanov** [comment]
Closing since there were no details provided.
