### ISSUE TITLE
bvnc sometimes behaves badly with TurboVNC 

### ISSUE THREAD

**Issue by usama-makhzoum** [iiordanov/remote-desktop-clients#242]
i am using it wth android 5.1, it does double or even triple right clicks with single mouse click (using external mouse) , and sometimes crashes and closes connection.

testing it with x11vnc doesn't produce this bug, changing VNC client niether do.

i use debian unstable inside chroot running VNC server.

**Comment by iiordanov** [comment]
There were many improvements made to external mice support. Is this still an issue @usama-makhzoum or can we close this issue?
