### ISSUE TITLE
VNC Connections to pikvm fail with iOS bVNC client

### ISSUE THREAD

**Issue by iiordanov** [iiordanov/remote-desktop-clients#245]
https://mail.google.com/mail/u/0/#inbox/FMfcgxwKkRJRjfpXlrNRqvTcJTMTlWQX

kvmd.apps.vnc.server              INFO --- [entry] [::ffff:192.168.123.10]:49160: Connected client
kvmd.apps.vnc.rfb                 INFO --- [entry] [::ffff:192.168.123.10]:49160: Starting client tasks ...
kvmd.apps.vnc.rfb                 INFO --- [main] [::ffff:192.168.123.10]:49160: Using RFB version 3.8
kvmd.apps.vnc.rfb                 INFO --- [main] [::ffff:192.168.123.10]:49160: Using VeNCrypt security type
kvmd.apps.vnc.rfb                 INFO --- [main] [::ffff:192.168.123.10]:49160: Using VeNCrypt/TLSPlain auth type
kvmd.apps.vnc.rfb                ERROR --- [main] [::ffff:192.168.123.10]:49160: Error: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
kvmd.apps.vnc.rfb                 INFO --- [kvmd] [::ffff:192.168.123.10]:49160: Cancelling subtask ...
kvmd.apps.vnc.rfb                 INFO --- [streamer] [::ffff:192.168.123.10]:49160: Cancelling subtask ...
kvmd.apps.vnc.server              INFO --- [entry] [::ffff:192.168.123.10]:40992: Connected client
kvmd.apps.vnc.rfb                 INFO --- [entry] [::ffff:192.168.123.10]:40992: Starting client tasks ...

**Comment by mdevaev** [comment]
By the way, does bvnc support VeNCrypt/Plain authorization? I understand that this is not secure, but for a local network or use through a tunnel, this is acceptable.

**Comment by iiordanov** [comment]
Yes, it does support it. It is SSL encrypted, of course.

**Comment by mdevaev** [comment]
Please check it out. I don't have it working on my iPhone.

To disable TLS in the server, edit the file `testenv/v2-hdmi-rpi4.override.yaml`:
```yaml
vnc:
    keymap: /usr/share/kvmd/keymaps/ru

    auth:
        vncauth:
            enabled: true

    server:
        tls:
            ciphers: ""
```

Here what I got from bVNC:
```
Initializing VNC Session instance: 0
Ensuring buttons are initialized, and positioning them where they should be
Connecting VNC Session in the background...
VNC server supports protocol version 3.8 (viewer 3.8)
We have 2 security types to read
0) Received security type 19
Selecting security type 19 (0/2 in the list)
1) Received security type 2
Selected Security Scheme 19
OpenSSL version OpenSSL 1.1.1g  21 Apr 2020 initialized.
Got VeNCrypt version 0.2 from server.
We have 2 security types to read
0) Received security type 256
1) Received security type 2
Unknown VeNCrypt authentication scheme from VNC server: 256, 2
FAILED_TO_INIT_CONNECTION_TO_SERVER
Done initializing VNC session
Connection failure, showing error with title VNC_CONNECTION_FAILURE_TITLE.
Scheduling disconnect
Lazy disconnecting
wasDrawing(): true
Setting maintainConnection to false
Hiding keyboard.
```

**Comment by mdevaev** [comment]
The problem above occurs because vncauth is considered an invalid authorization method for vencrypt. This is a controversial point, because the vencrypt specification does not explicitly prohibit this and most clients support it. On the other hand, if the client is vinagre who made the decision not to support this, but personally I think they are wrong. The client must support all possible schemes.

Okay, we can disable vncauth (delete the corresponding lines), but it will still be impossible to connect:
```
Initializing VNC Session instance: 2
Ensuring buttons are initialized, and positioning them where they should be
Connecting VNC Session in the background...
Initializing VNC session.
VNC server supports protocol version 3.8 (viewer 3.8)
We have 1 security types to read
0) Received security type 19
Selecting security type 19 (0/1 in the list)
Selected Security Scheme 19
Got VeNCrypt version 0.2 from server.
We have 1 security types to read
0) Received security type 256
Unknown VeNCrypt authentication scheme from VNC server: 256
FAILED_TO_INIT_CONNECTION_TO_SERVER
Done initializing VNC session
Connection failure, showing error with title VNC_CONNECTION_FAILURE_TITLE.
Scheduling disconnect
Lazy disconnecting
wasDrawing(): true
Hiding keyboard.
Setting maintainConnection to false
```

256 is vencrypt/plain.

**Comment by iiordanov** [comment]
http://libvncserver.sourceforge.net/doc/html/rfbproto_8h_source.html

Specifically:

00270 /*-----------------------------------------------------------------------------
00271  * Authentication
00272  *
00273  * Once the protocol version has been decided, the server then sends a 32-bit
00274  * word indicating whether any authentication is needed on the connection.
00275  * The value of this word determines the authentication scheme in use.  For
00276  * version 3.0 of the protocol this may have one of the following values:
00277  */
00278 
00279 #define rfbConnFailed 0
00280 #define rfbNoAuth 1
00281 #define rfbVncAuth 2
00282 
00283 #define rfbRA2 5
00284 #define rfbRA2ne 6
00285 #define rfbSSPI 7
00286 #define rfbSSPIne 8
00287 #define rfbTight 16
00288 #define rfbUltra 17
00289 #define rfbTLS 18
00290 #define rfbVeNCrypt 19
00291 #define rfbARD 30
00292 #define rfbMSLogon 0xfffffffa
00293 
00294 #define rfbVeNCryptPlain 256
00295 #define rfbVeNCryptTLSNone 257
00296 #define rfbVeNCryptTLSVNC 258
00297 #define rfbVeNCryptTLSPlain 259
00298 #define rfbVeNCryptX509None 260
00299 #define rfbVeNCryptX509VNC 261
00300 #define rfbVeNCryptX509Plain 262
00301 #define rfbVeNCryptX509SASL 263
00302 #define rfbVeNCryptTLSSASL 264

shows that 256 is a supported scheme, so I am not sure what the issue is...

I take back what I said - the TLS encrypted Plain auth that I was thinking of is 262. The one your server advertises appears to be unencrypted.

**Comment by iiordanov** [comment]
Could it be because the server sends an old version of VeNCrypt?

Log line in question:
Got VeNCrypt version 0.2 from server.

**Comment by mdevaev** [comment]
We're a little confused :)
* pikvm implements vencrypt/plain, which is not supported by bvnc. This is unencrypted mode.
* 2 (vncauth) is also not supported INSIDE vencrypt. Not encrypted again.

The problem with bvnc/pikvm consists of two parts:
* Unable to handshake TLS for encrypted connections. Maybe it's my fault, we need to understand what ciphers we can use.
* Two unsupported unecrypted modes from bVNC side.

0.2 is an actual vencrypt version. It must work: https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#724vencrypt

**Comment by mdevaev** [comment]
I suggest dealing with unencrypted modes first, as tigervnc supports both. I think bvnc should too. Then we'll find out what's wrong with encryption.

**Comment by iiordanov** [comment]
Could you please open an issue request with libvncserver https://github.com/LibVNC/libvncserver for that support, since it is not bVNC that doesn't support it rather the library that it uses.

Remmina is also broken with the same issue since it uses the same library. Please @ me on the issue opened against libvncserver.

I am not sure what the comment above the defines in libvncserver refers to as the "protocol", but this:

00276 * version 3.0 of the protocol this may have one of the following values:

Suggests to me that one must advertise v3.0 for these defines to kick in. I could be wrong, of course.

**Comment by iiordanov** [comment]
>     * pikvm implements vencrypt/plain, which is not supported by bvnc. This is unencrypted mode.
> 
>     * 2 (vncauth) is also not supported INSIDE vencrypt. Not encrypted again.

A further suggestion - since VeNCrypt/plain does not provide a significant improvement in security over plain vncauth (2), may I suggest turning it off until we can fix libvncserver?

> The problem with bvnc/pikvm consists of two parts:
> 
>     * Unable to handshake TLS for encrypted connections. Maybe it's my fault, we need to understand what ciphers we can use.

As far as I know, the ciphers for the TLS auth modes of vencrypt are a set that may include Diffie Hellman (DH) anonymous ciphers. Whereas the ciphers for x509 auth modes may not include DH ciphers.

**Comment by mdevaev** [comment]
To be honest, I don't think this will be fixed quickly in the upstream. I'm sure that now there will be discussions like "why this combination, but some don't support it, and whether this is a security hole, and we can not break a ton of processing compatibility, blah-blah". Just look at how many big open source there are. Most likely, they will require a minimal test case or something like that. This will take a long time. Please don't get me wrong, I don't want to push the library's problems on you. It just seems to me that as end users, we can fix it faster. See how many open issues and prs they have. If you did a patch on libvncclient, it would significantly speed up the solution of the problem. If something is incorrect on the part of my server, I will fix it.

> A further suggestion - since VeNCrypt/plain does not provide a significant improvement in security over plain vncauth (2), may I suggest turning it off until we can fix libvncserver?

Alas, this is impossible. This is a critical functionality without which Pi-KVM authorization will not work. The backend uses user-password combinations, and plain auth just proxies this. The vast majority of my users use this together with tigervnc. If I disable this, they all stop working.

> As far as I know, the ciphers for the TLS auth modes of vencrypt are a set that may include Diffie Hellman (DH) anonymous ciphers. Whereas the ciphers for x509 auth modes may not include DH ciphers.

I don't know much about SSL magic. In my code, I just enabled support for all ciphers using `ALL:@SECLEVEL=0`. I thought it should work, but I don't know how to debug it further.

**Comment by iiordanov** [comment]
The libvncserver folks are extremely responsive and I've had a great history of communication with them. At the very least, they will provide valuable feedback. Let's give the project a chance to help us diagnose this. If it comes to nothing, then so be it.

As far as SSL certificates are concerned, how come the VNC server actually even uses ciphers when the authentication scheme is encrypted?

**Comment by mdevaev** [comment]
Okay! I'll trust your experience.

I didn't understand your question about ciphers.

**Comment by mdevaev** [comment]
https://github.com/LibVNC/libvncserver/issues/458

**Comment by mdevaev** [comment]
Hello?

**Comment by iiordanov** [comment]
Hey,

I had a chance to look at the code, and my preliminary fix with very little effort that makes bVNC on iOS work fine with your code is:

```
diff --git a/kvmd/apps/vnc/rfb/__init__.py b/kvmd/apps/vnc/rfb/__init__.py
index 8ca93c8..85adb1c 100644
--- a/kvmd/apps/vnc/rfb/__init__.py
+++ b/kvmd/apps/vnc/rfb/__init__.py
@@ -209,12 +209,13 @@ class RfbClient(RfbClientStream):  # pylint: disable=too-many-instance-attribute
 
     async def __handshake_security(self) -> None:
         sec_types: Dict[int, Tuple[str, Callable]] = {}
-        if self.__rfb_version > 3:
-            sec_types[19] = ("VeNCrypt", self.__handshake_security_vencrypt)
         if self.__none_auth_only:
             sec_types[1] = ("None", self.__handshake_security_none)
         elif self.__vnc_passwds:
             sec_types[2] = ("VNCAuth", self.__handshake_security_vnc_auth)
+        if self.__rfb_version > 3:
+            sec_types[19] = ("VeNCrypt", self.__handshake_security_vencrypt)
+
         if not sec_types:
             msg = "The client uses a very old protocol 3.3 and VNCAuth or NoneAuth is disabled"
             await self._write_struct("L", 0, drain=False)  # Refuse old clients using the invalid security type
```

to prioritize VeNCrypt below VNC auth, which makes libvncserver choose VNC Auth over VeNCrypt and all is well.

**Comment by iiordanov** [comment]
Of course, if you feel like this is not a good solution to this bug, reopen this issue.

**Comment by mdevaev** [comment]
No, this solution is not suitable. Most clients will prefer the first working connection method and this will change the behavior for the rest of the clients, not just for bVNC. For example, if TigerVNC has all supported authorization methods enabled, it will connect using passcode and without encryption. I can't fix the behavior for one client and break change/break the behavior for another, it needs to be fixed inside libvncclient. Moreover, I have already written that the existing behavior of libvncclient leads the protocol to a state from which it cannot exit itself and breaks the connection.

**Comment by mdevaev** [comment]
Reopen it please, for some reason I can't do this, I don't have a button.

**Comment by iiordanov** [comment]
I'll reopen it for the purposes of this discussion, but I don't necessarily agree that something needs to be fixed in libvncserver to support your server. I am using tigervnc server as a testbed for bVNC for both Android and iOS, and if they work with tigervnc I'd say the best solution is to align behavior and capability to tigervnc for pikvm. Do you agree with that?

Forst some tests and results:

Test 0 (X509Plain):
/usr/bin/x0tigervncserver -SecurityTypes "X509Plain" -rfbport 5902 -x509key /etc/ssl/certs/ssl-cert-snakeoil.key -x509cert /etc/ssl/certs/ssl-cert-snakeoil.pem -PlainUsers myusernamehere
Result: Success with bVNC for iOS

Test 1 (TLSPlain):
/usr/bin/x0tigervncserver -SecurityTypes "TLSPlain" -rfbport 5902 -PlainUsers myusernamehere
Result: Success with bVNC for iOS

Test 2: (VncAuth):
/usr/bin/x0tigervncserver -SecurityTypes "VncAuth" -rfbport 5902 PasswordFile=~/.vnc/passwd
Result: Success with bVNC for iOS

Test 3: (VncAuth, TLSPlain)
a) /usr/bin/x0tigervncserver -SecurityTypes "TLSPlain,VncAuth" -rfbport 5902 PasswordFile=~/.vnc/passwd -PlainUsers myusernamehere
b) /usr/bin/x0tigervncserver -SecurityTypes "VncAuth,TLSPlain" -rfbport 5902 PasswordFile=~/.vnc/passwd -PlainUsers myusernamehere
Result: Success with bVNC for iOS, but for both (a) and (b) the server offers Security type 19 first.

Test 4: (TLSNone)
/usr/bin/x0tigervncserver -SecurityTypes "TLSNone" -rfbport 5902
Result: Success with bVNC for iOS

Test 5: (None)
/usr/bin/x0tigervncserver -SecurityTypes "None" -rfbport 5902
Result: Success with bVNC for iOS

Test 6 (Plain)
/usr/bin/x0tigervncserver -SecurityTypes "Plain" -rfbport 5902 -PlainUsers myusernamehere
Result: Failed with bVNC for iOS, because libvncserver does not support auth scheme 256

Now for my proposals based on the above and my understanding.

- There is an incompatibility issue in the implementation of TLSPlain (no shared Cipher). We should fix that in pikvm.
- There is a missing implementation of X509Plain. We should fix that in pikvm.

- There is a missing feature in libvncserver (Plain auth). We can try to fix that in libvncserver, but if we fix the above two it's not critical and is also less secure.
- There is a potential missing feature in libvncserver which is not in the VeNCrypt standard (VeNCrypt with VncAuth authorization scheme).  We can try to fix that in libvncserver, but if we fix the above two it's not critical.
- There is an authorization ordering design choice in pikvm that puts VeNCrypt ahead of VncAuth mode. That aligns with TigerVNC so we can leave that alone.

Do you agree with the above?

**Comment by iiordanov** [comment]
So I propose the following fix, or something based on it. There are no Shared Ciphers issues when I simply change your code thus:

```
diff --git a/kvmd/apps/vnc/rfb/__init__.py b/kvmd/apps/vnc/rfb/__init__.py
index 8ca93c8..c82d26a 100644
--- a/kvmd/apps/vnc/rfb/__init__.py
+++ b/kvmd/apps/vnc/rfb/__init__.py
@@ -248,7 +248,7 @@ class RfbClient(RfbClientStream):  # pylint: disable=too-many-instance-attribute
         else:
             auth_types = {256: ("VeNCrypt/Plain", False, self.__handshake_security_vencrypt_userpass)}
             if self.__tls_ciphers:
-                auth_types[259] = ("VeNCrypt/TLSPlain", True, self.__handshake_security_vencrypt_userpass)
+                auth_types[262] = ("VeNCrypt/X509Plain", True, self.__handshake_security_vencrypt_userpass)
             if self.__vnc_passwds:
                 # Vinagre не умеет работать с VNC Auth через VeNCrypt, но это его проблемы,
                 # так как он своеобразно трактует рекомендации VeNCrypt.

```
essentially replacing TLSPlain (which should use Diffie Hellman ciphers only) with X509Plain which uses X509 certificates and does not depend on DH ciphers.

Does that work for you?

**Comment by mdevaev** [comment]
> but I don't necessarily agree that something needs to be fixed in libvncserver to support your server

We discussed this a month ago, I gave arguments and showed that the state machine of the protocol breaks down due to the ill-conceived behavior of vencrypt. [You even agreed with me.](https://github.com/LibVNC/libvncserver/issues/458#issuecomment-761971254) What has changed?

> if they work with tigervnc I'd say the best solution is to align behavior and capability to tigervnc for pikvm. Do you agree with that?

Yes. I believe that the TigerVNC client is a benchmark that is worth equating to. At the moment, TigerVNC works fine with my server, but libvncclient doesn't. We should not force the user to change the client settings to connect to different types of servers. Servers are not required to adjust to the order of authorization methods for a particular client. You just need to fix the dead state of the protocol, from which it cannot exit.

> There is an incompatibility issue in the implementation of TLSPlain (no shared Cipher). We should fix that in pikvm.

Yes.

> There is a missing implementation of X509Plain. We should fix that in pikvm.

Yes, but with a caveat: the server is not required to support this. This is an optional method.

> There is a missing feature in libvncserver (Plain auth). We can try to fix that in libvncserver, but if we fix the above two it's not critical and is also less secure.

Between an impossible connection and an insecure connection, we should choose an insecure one. Imagine that you are a system administrator who has his server frozen, and you only have an iPhone with bVNC in your hands. You will not care about security at the moment, you will change your passwords. Or (which is more common) you can use a VPN to access pikvm. Or it may even be a local network, and you want to access it from a tablet. In short, my opinion is that the person who uses it knows what they are doing. TigerVNC warns you that the connection is not secure, but still lets you connect. All clients should do the same, and not decide for the user what is safe and what is not.

I suggest starting by fixing libvncclient. This is the easiest one, because I couldn't figure out SSL in two approaches. Then we can solve the problem of ciphers.

Just for the record: I'm starting to sell my Pi-KVM devices and my customers are extremely interested in using VNC on iOS. I will be happy to recommend bVNC to them because it is a great product. We will both benefit from fixing this issue.

**Comment by iiordanov** [comment]
https://github.com/pikvm/kvmd/pull/28
