### ISSUE TITLE
bVNC times out a little too quickly

### ISSUE THREAD

**Issue by hippie68** [iiordanov/remote-desktop-clients#247]
I use bVNC to connect to an ARM board, which is not the fastest computer. When it's under sudden load, like closing a website or opening a program, sometimes bVNC immediately disconnects. It appears to me that one of bVNC's timeouts may be too low. I don't know anything more specific, but perhaps my description is enough to reveal the reason for those quick disconnects. If it matters, I connect from an Android TV, and on the other end there's TigerVNC server.

**Comment by iiordanov** [comment]
Could you please capture logcat with "Copy logcat" after you reproduce this issue and post it here?

Thanks!

**Comment by iiordanov** [comment]
Increased socket timeouts for a few sockets in bVNC. The improvement will be out in Beta today.

https://github.com/iiordanov/remote-desktop-clients/commit/f0c06510a1dda51dea15296132168867014a4f8a
