### ISSUE TITLE
how to use convert.py?

### ISSUE THREAD

**Issue by susemi99** [iiordanov/remote-desktop-clients#248]
OS: Ubuntu 20.04

1. `sudo apt install qemu` => not made `/usr/share/qemu/keymaps/` directory
2. `sudo apt install qemu-system-data` => made `/usr/share/qemu/keymaps/` directory
3. `python3 convert.py` => No such file or directory: '/usr/share/qemu/keymaps/common'
  ```
  Traceback (most recent call last):
  File "convert.py", line 144, in <module>
    loadKeyMap(nameToUnicode, layoutLocation + "common", keyMap)
  File "convert.py", line 54, in loadKeyMap
    f = open(keyMapFile)
  FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/qemu/keymaps/common'
  ```

**Q1. What package need to make for `/usr/share/qemu/keymaps/common` directory?**

---

4. comment L144 
5. `python3 convert.py` => made layouts. but different this [English (US)](https://github.com/iiordanov/remote-desktop-clients/tree/master/bVNC/src/main/assets/layouts) layout. 

**Q2. What is my mistake? Where can I get the `keymap/en-us` file?**
**Q3. Is there a way to add Korean?**

**Comment by susemi99** [comment]
I found how to make `/usr/share/qemu/keymaps/common`. 

1. [build with docker](https://github.com/iiordanov/remote-desktop-clients#i-b-from-scratch-with-docker)
2. `sudo apt install qemu-keymaps` inside docker image
3. copy `name_to_unicode.in, common_keycodes.in, convert.py` to docker image
4. `python3 convert.py`

but `made English(US)` and `bVNC/src/main/assets/layouts/English (US)` were different. I think I made a mistake somewhere.

**Comment by susemi99** [comment]
Finally, I Found how to add Korean.

input `깃`(git) --> split `ㄱ`, `ㅣ`, `ㅅ` --> send `19`, `38`, `20` 

---

this is Korean key map. 
||code|win keycode1|win keycode2|need ShiftKey?|
|---|---|---|---|---|
|ㄱ|1061169|19|||
|ㄲ|1061170|19||O|
|ㄳ|1061171|19|20||
|ㄴ|1061172|31|||
|ㄵ|1061173|31|17||
|ㄶ|1061174|31|34||
|ㄷ|1061175|18|||
|ㄸ|1061176|18||O|
|ㄹ|1061177|33|||
|ㄺ|1061178|33|19||
|ㄻ|1061179|33|30||
|ㄼ|1061180|33|16||
|ㄽ|1061181|33|20||
|ㄾ|1061182|33|45||
|ㄿ|1061183|33|47||
|ㅀ|1061184|33|34||
|ㅁ|1061185|30|||
|ㅂ|1061186|16|||
|ㅃ|1061187|16||O|
|ㅄ|1061188|16|20||
|ㅅ|1061189|20|||
|ㅆ|1061190|20||O|
|ㅇ|1061191|32|||
|ㅈ|1061192|17|||
|ㅉ|1061193|17||O|
|ㅊ|1061194|46|||
|ㅋ|1061195|44|||
|ㅌ|1061196|45|||
|ㅍ|1061197|47|||
|ㅎ|1061198|34|||
|ㅏ|1061199|37|||
|ㅐ|1061200|24|||
|ㅑ|1061201|23|||
|ㅒ|1061202|24||O|
|ㅓ|1061203|36|||
|ㅔ|1061204|25|||
|ㅕ|1061205|22|||
|ㅖ|1061206|25||O|
|ㅗ|1061207|35|||
|ㅘ|1061208|35|37||
|ㅙ|1061209|35|24||
|ㅚ|1061210|35|38||
|ㅛ|1061211|21|||
|ㅜ|1061212|49|||
|ㅝ|1061213|49|36||
|ㅞ|1061214|49|25||
|ㅟ|1061215|49|38||
|ㅠ|1061216|48|||
|ㅡ|1061217|50|||
|ㅢ|1061218|50|38||
|ㅣ|1061219|38|||

need loadKeymap `layout/Korean (Korea)`
```
1061169 19
1061170 19
1061171 19 20
1061172 31
1061173 31 17
1061174 31 34
1061175 18
1061176 18
1061177 33
1061178 33 19
1061179 33 30
1061180 33 16
1061181 33 20
1061182 33 45
1061183 33 47
1061184 33 34
1061185 30
1061186 16
1061187 16
1061188 16 20
1061189 20
1061190 20
1061191 32
1061192 17
1061193 17
1061194 46
1061195 44
1061196 45
1061197 47
1061198 34
1061199 37
1061200 24
1061201 23
1061202 24
1061203 36
1061204 25
1061205 22
1061206 25
1061207 35
1061208 35 37
1061209 35 24
1061210 35 38
1061211 21
1061212 49
1061213 49 36
1061214 49 25
1061215 49 38
1061216 48
1061217 50
1061218 50 38
1061219 38
```


---
split Korean word code

```kotlin
object HangulUtil {
  private val CHO_SUNG = charArrayOf(
    0x3131.toChar(), // ㄱ
    0x3132.toChar(), // ㄲ
    0x3134.toChar(), // ㄴ
    0x3137.toChar(), // ㄷ
    0x3138.toChar(), // ㄸ
    0x3139.toChar(), // ㄹ
    0x3141.toChar(), // ㅁ
    0x3142.toChar(), // ㅂ
    0x3143.toChar(), // ㅃ
    0x3145.toChar(), // ㅅ
    0x3146.toChar(), // ㅆ
    0x3147.toChar(), // ㅇ
    0x3148.toChar(), // ㅈ
    0x3149.toChar(), // ㅉ
    0x314a.toChar(), // ㅊ
    0x314b.toChar(), // ㅋ
    0x314c.toChar(), // ㅌ
    0x314d.toChar(), // ㅍ
    0x314e.toChar() // ㅎ
  )

  private val JUNG_SUNG = charArrayOf(
    0x314f.toChar(), // ㅏ
    0x3150.toChar(), // ㅐ
    0x3151.toChar(), // ㅑ
    0x3152.toChar(), // ㅒ
    0x3153.toChar(), // ㅓ
    0x3154.toChar(), // ㅔ
    0x3155.toChar(), // ㅕ
    0x3156.toChar(), // ㅖ
    0x3157.toChar(), // ㅗ
    0x3158.toChar(), // ㅘ
    0x3159.toChar(), // ㅙ
    0x315a.toChar(), // ㅚ
    0x315b.toChar(), // ㅛ
    0x315c.toChar(), // ㅜ
    0x315d.toChar(), // ㅝ
    0x315e.toChar(), // ㅞ
    0x315f.toChar(), // ㅟ
    0x3160.toChar(), // ㅠ
    0x3161.toChar(), // ㅡ
    0x3162.toChar(), // ㅢ
    0x3163.toChar() // ㅣ
  )

  private val JONG_SUNG =
    charArrayOf(
      0.toChar(),
      0x3131.toChar(), // ㄱ
      0x3132.toChar(), // ㄲ
      0x3133.toChar(), // ㄳ
      0x3134.toChar(), // ㄴ
      0x3135.toChar(), // ㄵ
      0x3136.toChar(), // ㄶ
      0x3137.toChar(), // ㄷ
      0x3139.toChar(), // ㄹ
      0x313a.toChar(), // ㄺ
      0x313b.toChar(), // ㄻ
      0x313c.toChar(), // ㄼ
      0x313d.toChar(), // ㄽ
      0x313e.toChar(), // ㄾ
      0x313f.toChar(), // ㄿ
      0x3140.toChar(), // ㅀ
      0x3141.toChar(), // ㅁ
      0x3142.toChar(), // ㅂ
      0x3144.toChar(), // ㅄ
      0x3145.toChar(), // ㅅ
      0x3146.toChar(), // ㅆ
      0x3147.toChar(), // ㅇ
      0x3148.toChar(), // ㅈ
      0x314a.toChar(), // ㅊ
      0x314b.toChar(), // ㅋ
      0x314c.toChar(), // ㅌ
      0x314d.toChar(), // ㅍ
      0x314e.toChar() // ㅎ
    )

  /**
   * 한글 자소 분리
   *
   * @param text 김태희
   * @return ㄱㅣㅁㅌㅐㅎㅢ
   */
  val String.toJaso: Array<Char>
    get() {
      val result = arrayListOf<Char>()

      toCharArray().forEach {
        if (it.toInt() in 0xAC00..0xD7A3) { // "AC00:가" ~ "D7A3:힣" 에 속한 글자면 분해
          var c = it.toInt() - 0xAC00
          val a = c / (21 * 28)
          c %= (21 * 28)
          val b = c / 28
          c %= 28
          result.add(CHO_SUNG[a])
          result.add(JUNG_SUNG[b])
          if (c != 0) result.add(JONG_SUNG[c]) // c가 0이 아니면, 즉 받침이 있으면
        } else {
          result.add(it)
        }
      }
      return result.toTypedArray()
    }

  /**
   * 시프트 키 눌린 걸로 처리해야 하는가?
   */
  val Char.needShiftKey: Boolean
    get() = arrayOf("ㄲ", "ㄸ", "ㅃ", "ㅆ", "ㅉ", "ㅒ", "ㅖ").contains(toString())
}
```

before 
```kotlin
// RemoteSpiceKeyboard.kt
if (action == KeyEvent.ACTION_MULTIPLE) {
  val s = event.characters
  if (s != null) {
    val numchars = s.length
    for (i in 0 until numchars) {
      if (!sendUnicode(s[i], additionalMetaState)) {
        writeKeyEvent(true, s[i].toInt(), metaState, true, true)
      }
    }
  }
}
```

after
```kotlin
// RemoteSpiceKeyboard.kt
if (action == KeyEvent.ACTION_MULTIPLE) {
  val s = event.characters
  if (!s.isNullOrBlank()) {
    s.toJaso.forEach {
      if (!sendUnicode(it, additionalMetaState)) {
        writeKeyEvent(true, it.toInt(), if (it.needShiftKey) metaState or KeyEvent.META_SHIFT_ON else metaState, true, true)
      }
    }
  }
}
```

**Comment by iiordanov** [comment]
Hey there,

I updated the README.md to indicate how to run convert.py. The "right" way would be to provide a "ko" keymap for qemu as an input file. Do you have or can you generate that input file?

See the new info on convert.py. The utility now reads all keymaps in /usr/share/qemu/keymaps/, and uses any custom
keymap names given in order to augment the automatically generated dictionary of keymaps.

https://github.com/iiordanov/remote-desktop-clients/blob/master/README.md

Thanks!
iordan

**Comment by susemi99** [comment]
Sorry. I only know keymap file I wrote above...

**Comment by iiordanov** [comment]
OK, I installed Ubuntu 20.04 on one of my systems and saw that the common keymap was removed from qemu between v3.1.1.1 and v4.0.0 of qemu. I've made convert.py skip common if it's not found.

Is it possible for you to create a qemu keymap for the qemu project at this location:
https://github.com/qemu/qemu/tree/master/pc-bios/keymaps

This would be the best solution.
