### ISSUE TITLE
can't trigger 2 finger scroll, very hard to trigger 2 finger zoom on bVNC Pro latest release

### ISSUE THREAD

**Issue by mzhou** [iiordanov/remote-desktop-clients#250]
All of this relates to direct swipe pan/single handed mode.

It seems since the latest update it's very hard to trigger zooming, unless the 2 fingers are almost perfectly diagonal from each other.
Scrolling seems to now be done by keeping one finger still and moving the other one, but I'm not entirely sure. I find it harder and less reliable than swiping both fingers together.

Would it be possible to revert to the old behaviour or add an option for it?

Thanks

**Comment by iiordanov** [comment]
Hey,

Thanks for your report!

There has been *no* change to the app as far as scrolling and zooming is
concerned. I did notice, however, that after the (mandatory) update to API
29 for Google Play, I found a similar side effect on my device, but it
doesn't bother me that much.

However if it's something that is bugging my users, I will look into how to
make zooming and scrolling behave as before. Unfortunately there is no
possibility of a "revert" for this issue.

**Comment by mzhou** [comment]
Thanks for your reply. Of course Google would make a non backwards compatible change mandatory.

Working great after downgrading to 115032.

**Comment by iiordanov** [comment]
Yes, you can install any version you like outside Google Play .. :)

Good move!

**Comment by iiordanov** [comment]
Hey, I've released a fix for this bug in v5.0.3_8.

Either join the beta on Google Play and make sure you have v5.0.3_115038 in Advanced Settings (preferred so you can get updates) or install:

https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.3/freebVNC-v5.0.3_8-final.apk

Thanks!
