### ISSUE TITLE
bVNC crashes on Chromebook when started on external monitor

### ISSUE THREAD

**Issue by brockamer** [iiordanov/remote-desktop-clients#251]
bVNC crashes on Chromebook when started on external monitor. It works fine if I launch bVNC on the Chromebook's built-in screen, then move the window to the external monitor using the hotkey (Alt+Launcher+m). This happens both with the free and Pro versions.

I haven't filed a bug on Github before, so please let me know if there is any other information I can provide to characterize this issue.

**Repro steps:**
1. Attach an external monitor via USB-C to the Chromebook
2. Configure monitor as extended display
3. Launch bVNC from shelf shortcut on external monitor
4. Observe bVNC briefly starts then immediately closes.

**Workaround steps:**
1. Attach an external monitor via USB-C to the Chromebook
2. Configure monitor as extended display
3. Launch bVNC from shelf shortcut **on built-in display**
4. Observe it starts normally
5. Click a saved connection to connect to remote machine
6. Move bVNC to external display using the hotkey (Alt+Launcher+m)
7. Observe bVNC remains stable & open, functioning normally now on the external monitor

Chromebook model C0A
88.0.4324.109 (Official Build) (64-bit)
External monitor is Asus ZenScreen 15.6" model MB16ACE

**Comment by iiordanov** [comment]
He there, thanks for your report!

The trouble with Chromebooks is that I don't have any hardware to reproduce issues with them. I will try to reproduce this with a phone - do you have a phone that supports HDMI out over USB-C to see if the issue can be reproduced on a phone as well?

Thanks!

**Comment by brockamer** [comment]
I don't have a phone that supports HDMI or DisplayPort over USB-C. Mine is a Pixel 4 XL. If you know of a way to get it to do that, please let me know. Maybe someone else will chime in on this thread eventually. 

My Chromebook belongs to my employer, but I can highly recommend it as a daily driver for most work tasks.

**Comment by iiordanov** [comment]
Hi @brockamer, I reproduced something along the lines of your report while working on some USB redirection for aSPICE and Opaque a few weeks ago.

I released a speculative fix into:
https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.6/freebVNC-v5.0.6_2-final.apk

Only if the above works, could you please also verify that this release still suffers from the issue?
https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.6/freebVNC-v5.0.6_1-final.apk

Thanks!
iordan

**Comment by iiordanov** [comment]
This issue is no longer present in recent versions. Please let me know if I should reopen.
