### ISSUE TITLE
On-Screen buttons difficult to see on iOS

### ISSUE THREAD

**Issue by iiordanov** [iiordanov/remote-desktop-clients#255]
https://groups.google.com/g/bvnc-ardp-aspice-opaque-remote-desktop-clients/c/ynMxlLWhbHc/m/vc2jHxICCAAJ?pli=1

**Comment by nibblerrick** [comment]
Do you need a screenshot? I encountered this problem and would love to see it fixed, because this way it's a bit difficult to use.

**Comment by iiordanov** [comment]
This issue has been fixed. Thanks!
