### ISSUE TITLE
Screen colors are washed out on ChromeOS and Opaque

### ISSUE THREAD

**Issue by edygert** [iiordanov/remote-desktop-clients#256]
Used the Proxmox android app to connect to the proxmox server then clicked Console to connect to a VM using Opaque. The VM screen is displayed but the colors are very washed out, as if there were a layer of fog over the screen. Tried this with two different Google Pixelbooks and with different VMs running different OSs with the same results.

**Comment by juergenalbert** [comment]
Same for me on my two Samsung Android 11 devices.

**Comment by iiordanov** [comment]
This issue has been fixed since your report. Please let me know if I should reopen it.
