### ISSUE TITLE
spice connection hangs when video playing

### ISSUE THREAD

**Issue by ligangcc** [iiordanov/remote-desktop-clients#257]
Every time I connect  to the VM(win7)  which is playing a video, such as  an online video in chrome , the connnection 
can't be established, always handshaking:

![spice](https://user-images.githubusercontent.com/5357175/111558140-28588c00-87c9-11eb-8118-fb96737f9354.jpg)

**Comment by iiordanov** [comment]
What version of the app is this? (Get the version from Advanced settings)

Iordan

**Comment by ligangcc** [comment]
aSPICE Pro v5.0.3

**Comment by iiordanov** [comment]
Hey, I came up with a workaround in v5.0.4_2. Please install this and let me know if that works for you.

https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.4/freeaSPICE-v5.0.4_2-final.apk

**Comment by iiordanov** [comment]
Alright, I fixed this too. Update to v5.0.4 either from here:

https://github.com/iiordanov/remote-desktop-clients/releases

or Google Play when the version is out (soon).

**Comment by ligangcc** [comment]
I tested v5.0.4 just now, it works well when playing.
Thansk!!!!

**Comment by iiordanov** [comment]
Thanks for confirming.

Cheers!
iordan
