### ISSUE TITLE
No uppercase letters in RDP session

### ISSUE THREAD

**Issue by Maxim-GG** [iiordanov/remote-desktop-clients#258]
After last update, I cannot switch to uppercase in an RDP session to Windows 7.
Everything was fine before the update.

The app is aRDP, OS is MIUI 12.0.3

**Comment by iiordanov** [comment]
Hey Max, thanks so much for putting this here so i can respond and give you a test link.

Please try this version and let me know:
https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.4/freeaRDP-v5.0.4_0-final.apk

Thanks!
iordan

**Comment by Maxim-GG** [comment]
Thank you! This version has no issues with the keyboard.

**Comment by iiordanov** [comment]
Thanks for testing!
