### ISSUE TITLE
Recipe 'liblz4' failed at the build step 'configure' on Ubuntu 20

### ISSUE THREAD

**Issue by makspiechota** [iiordanov/remote-desktop-clients#262]
Hi,

I'm following the build procedure from README and I'm getting error as in the title. What should I fix?

**Comment by makspiechota** [comment]
The issue was it couldn't find stdlib.h library for some reason. The library has built successfully when I went to the directory and ran make manually.
I haven't had much time to debug so I have chosen to use prebuilt libraries.

**Comment by iiordanov** [comment]
I fixed that nonetheless. Thanks for the report!
