### ISSUE TITLE
 Supporting display cutouts on edge-to-edge screens

### ISSUE THREAD

**Issue by 0xOGeek** [iiordanov/remote-desktop-clients#263]
Hello, first of all thanks for your work!
I have a new Android 9/10 phone with rounded corners and V-Notch in the screen, never thought it could be a problem.
When i run the App in full screen mode, i'm missing the Windows start button, windows decorations an parts of the tray area in windows.
As i found out there is an API for such cases but no idea if it can help.
https://android-developers.googleblog.com/2018/07/supporting-display-cutouts-on-edge-to.html
Maybe it is a better idea to swap back to, let's say, a fixed full HD resolution (or let the user set it fixed without scaling to the full screen). My screen resolution is bigger then full HD so the corners wouldn't be a problem anymore.
If i had the ability to use the mouse curser like in the Microsoft RPD app, on the other hand, it would be maybe possible to reach, as example, the Startbutton again.

PS: I'm using aRDP from Google Playstore

**Comment by iiordanov** [comment]
If you switch to "Simulated touchpad" mode, you can use the cursor like the MS app.

Furthermore the app should already allow for curved screens by panning the screen up/down in the other input modes (that's what the bar that appears at the top/bottom is for when you pan all the way and keep panning past the end of the image.

Please ask me to reopen if i didn't get your questions right.
