### ISSUE TITLE
what's the difference between freeaSPICE-v5.0.4_0-final and freeaSPICE-v5.0.4_2-final?

### ISSUE THREAD

**Issue by ligangcc** [iiordanov/remote-desktop-clients#269]
I installed freeaSPICE-v5.0.4_0-final on an android box, when connecting, it crashed without any notice. Then I installed reeaSPICE-v5.0.4_2-final, it works well.  So what's the difference of these two apks?  I can only see the apk sizes are not same.

**Comment by ligangcc** [comment]
I checked the adb output,  a signal triggered, but couldn't get any detail.

**Comment by iiordanov** [comment]
The only way to tell is to look in the source code for changes between the
commit that set the build code in aSPICE's  AndroidManifest.xml to 115040
and the subsequent commit that set it to 115042.

You can look at

git log aSPICE-app/src/main/AndroidManifest.xml

To see the list of commits associated with the file. I think this link will
also do the job:

https://github.com/iiordanov/remote-desktop-clients/commits/master/aSPICE-app/src/main/AndroidManifest.xml

Iordan
