### ISSUE TITLE
bvnc - back key (rmb) is bouncing/chattering

### ISSUE THREAD

**Issue by BlueMax** [iiordanov/remote-desktop-clients#273]
Hallo,
I'm using bvnc in 'simulated touchpad' mode and use the h/w 'back' key as right mouse button. It works properly most of the time in Firefox but nearly never in xfce (Thunar, desktop, bottom bar..). It seems to be a timing issue. The context menu flashes several times and probably a matter of luck in what state the context menu remains (open/closed). The main bug probably is that it sends several 'back' commands i guess. The two-finger rmb function seems to work properly though but it's quite uncomfortable.

ArchLinux/x11vnc 0.9.16
bvnc v5.0.4 
LOS18.1/Android 11
Galaxy S4 (I9506)

**Comment by iiordanov** [comment]
I've seen the same issue with a physical mouse in Firefox if the mouse does
not move between mouse button down and mouse button up. I didn't want to
introduce hacks in the code to workaround something which is an issue
already...

Am i off the mark?

**Comment by BlueMax** [comment]
Firefox was just one example where it behaves differently than my desktop environment (xfce). It actually happens everywhere (qt5, gtk apps, etc..). I don't think it's Firefox specific. It seems to always go open(/close) or maybe even open/close/open(/close).
Maybe we can log the commands sent to see what's actually going on?

**Comment by iiordanov** [comment]
Fixed in https://github.com/iiordanov/remote-desktop-clients/commit/2b829eb723e2ee796888eefd29b3c870a9e21600
