### ISSUE TITLE
[KEYBOARD ISSUE] - VNC client does not allow to select the keyboard layout pt-BR ABNT2

### ISSUE THREAD

**Issue by decofigueira** [iiordanov/remote-desktop-clients#275]
Hey,

I used your VNC client program on my Samsung Note 10+. The program is excellent, I used it for VNC connection, the program has a full screen option that works very well in DEX mode. The only problem is that my ABNT2 Brazilian Portuguese keyboard doesn't work properly, the special characters like "ê" or "ã" olu "ó" don't work, only the special character "ç" worked, I want to buy the paid version of your program , but if this need is not met, it will be very bad for me.

The problem is that I tested other VNC client programs and they all worked on my keyboard normally. Mocha VNC is a program that works perfectly on my keyboard, but it does not have a full screen mode that works on the Samsung DEX.

Any solution for configuring VNC keyboard?

Thanks

**Comment by iiordanov** [comment]
Hi there, you should try the "R-Alt as ISO L3 Shift" option in the default settings screen (the wrench on the main screen). Please let me know if this works for you. Thanks!
