### ISSUE TITLE
Bug on aSPICE: Can't type dot (.) key

### ISSUE THREAD

**Issue by leapofazzam123** [iiordanov/remote-desktop-clients#284]
I have a QEMU session running with SPICE display. When I connected to the session with aSPICE, all keyboard keys work fine, except the dot (.) key. The key should work. When i asked my friend how to fix this, my friend suggested to downgrade your aSPICE app

**Comment by nkotixwolf** [comment]
I have noted the bug in our development backlog.

Update will be posted here once resolved.

**Comment by iiordanov** [comment]
This issue is fixed and the fix released a while ago. Please let us know if it persists.
