### ISSUE TITLE
Floating menu triggers loss of immersive mode

### ISSUE THREAD

**Issue by nathaneltitane** [iiordanov/remote-desktop-clients#293]
When selecting an item from the floating menu, the window bar appears (even if momentarily) and pulls the vnc out of immersive/fullscreen mode.

See attached:

![Screenshot_20210801-120537_bVNC Free.png](https://user-images.githubusercontent.com/5674757/127777964-4f8847d2-1742-4543-8161-0e19963e7f14.png)

**Comment by iiordanov** [comment]
This is not something that can be controlled programmatically.
