### ISSUE TITLE
aSPICE-v5.0.5 crashed when connect

### ISSUE THREAD

**Issue by ligangcc** [iiordanov/remote-desktop-clients#297]
today, I installed aSPICE 115052 on my phone and connected to the remote computer, 
but unluckly,  there were two problems occurred:

1 connected failed
![image](https://user-images.githubusercontent.com/5357175/130355545-7e481d29-dbd4-4a2a-8cd6-70cab4ef4733.png)

but when I tried again, it connected successfully.

2 crashed
when I disconnected from the remote computer, the app always crashed.

below is the connection information I used:
![image](https://user-images.githubusercontent.com/5357175/130355533-80c3abc4-7a0a-4738-ba09-743647d1494c.png)

spice server:   ocloudware.vicp.io  5955
spice password: test123123

**Comment by nkotixwolf** [comment]
I think this is a bug that is occurs on v5.0.4 as well. Thanks for bringing it to our attention. Item is now in our backlog.

**Comment by ligangcc** [comment]
Thanks，if anything I can help, please let me know.

**Comment by iiordanov** [comment]
Hello, is this still an issue with the latest version? Thanks!

**Comment by iiordanov** [comment]
This should no longer be happening with the fix in https://github.com/iiordanov/remote-desktop-clients/commit/754495a64747e946aea6427730ace8031380e10e. Latest v5.0.9 in Beta on Google Play or https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.9/freeaSPICE-v5.0.9_9-final.apk should be stable. Please let me know if it's still an issue for you.
