### ISSUE TITLE
Building fails on a fresh Android Studio

### ISSUE THREAD

**Issue by daniellandau** [iiordanov/remote-desktop-clients#299]
I got errors in the freerdp lib that is downloaded in step Ia about the android support library not having the correct packages/classes, for example android.support.v4.util. I got past those by removing the import lines and letting the IDE find the new locations, mostly in androidx.

I don't have a diff of all the locations because it's not in a tracked directory, but I can manually generate one if that's helpful.

**Comment by iiordanov** [comment]
This was fixed in a more recent commit. Thanks for reporting!
