### ISSUE TITLE
alt tab on bVNC does not work correctly

### ISSUE THREAD

**Issue by Dan733** [iiordanov/remote-desktop-clients#304]
First off, let me say this application is fantastic. However, I have noticed I cannot alt tab correctly with it. Holding alt and pressing tab will immediately switch to the next application, instead of cycling through the windows in the alt-tab switcher. The switch should occur when releasing the alt key. Therefore, I'm assuming bVNC is telling the remote machine that both keys have been released when I have only released the tab key.

**Comment by iiordanov** [comment]
Please let me know if this issue persists in the latest version and if this bug-report should be reopened. There were many keyboard-related enhancements since this bug-report, especially with physical keyboards.
