### ISSUE TITLE
Shift key not working

### ISSUE THREAD

**Issue by dsunnerer** [iiordanov/remote-desktop-clients#306]
The special characters on the number row are translated into the number of the respective key instead of the special character.
This happens for me on virtual as well as hardware keyboards.
Tilde (~), Underscore (_) and Plus (+) are affected as well.

Update:
Just noticed the Shift key does not do anything at all.
Writing capital letters is not possible.
Just the keypress without Shift is entered.
"Send Text" behaves the same.

Tested app versions:
- bVNC Pro v5.0.4
- bVNC Pro v5.0.5 (Play Store beta)

Virtual keyboards tested:
- Hacker's Keyboard
- AnySoftKeyboard

Hardware keyboard (doubt it matters):
Durgod Taurus

VNC server:
x11vnc 0.9.16

VNC server command:
x11vnc -create -ncache -forever -display :0

Window manager used:
i3

**Comment by iiordanov** [comment]
Hi there,

This must be an issue with x11vnc, because I don't see these issues with vino or any other VNC server.

Does my suggestion to use TigerVNC here help?

https://github.com/iiordanov/remote-desktop-clients/issues/185

Thanks!

**Comment by iiordanov** [comment]
Please let me know if this issue persists and the bug-report should be reopened.

A lot of the time using setxkbmap with x11vnc helps.
https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Using_setxkbmap

In the worst case, switching to a different VNC server usually helps.
