### ISSUE TITLE
Keyboard Problem

### ISSUE THREAD

**Issue by emeraldservices** [iiordanov/remote-desktop-clients#310]
Please Help me 
I connected with aRDP App. any keypress keyboard shows me this Error:  
E/SHORT: SHORT
E/SHORT: SHORT
E/SHORT: SHORT

**Comment by iiordanov** [comment]
Hey, please let me know if this issue persists with the latest master branch and if I should reopen this issue. Please provide a detailed description how to reproduce the issue.
