### ISSUE TITLE
Send keys "delete" becomes "delete forward"

### ISSUE THREAD

**Issue by twiikker** [iiordanov/remote-desktop-clients#311]
Im using android 11 lineage os on oneplus 3t.
When using send keys feature on this app i cannot select key "delete".
When i press on "delete" it select key "delete forward".
Tried reinstalling app with no help.

**Comment by iiordanov** [comment]
I've combined these two duplicate entries into a single one. Delete and Delete Forward are the same key.

Thanks!
iordan
