### ISSUE TITLE
Can not input "." Or "|" using gboard on Android 11

### ISSUE THREAD

**Issue by siliconcreature** [iiordanov/remote-desktop-clients#313]
I can not input "." Or "|" using gboard, I do have Chinese language and keyboard input install , shall I change the locale?

**Comment by iiordanov** [comment]
Fixed in https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.5/freeaSPICE-v5.0.5_5-final.apk

I presume you're talking about aSPICE.

**Comment by siliconcreature** [comment]
This is awesome, thanks, I am a heavy user of your app, I almost downloaded
android studio to fix it myself, but it is beyond my capabilities.

**Comment by siliconcreature** [comment]
The key binding is not working again, please help , urgent.

**Comment by siliconcreature** [comment]
Sorry, I think it is the guest not forwarding keys to windows server
correctly

**Comment by iiordanov** [comment]
Could you please revert to https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.5/freeaSPICE-v5.0.5_5-final.apk for now, and please tell me how I can reproduce it? What layout is chosen on aSPICE? What layout is on the remote OS? What operating system is running on the remote?
