### ISSUE TITLE
hide the cursor mouse

### ISSUE THREAD

**Issue by rapido86** [iiordanov/remote-desktop-clients#315]
Hi,

In my setting, I selected "cursor mode = disable", but when I open my RDP session, I see alway the cursor mouse.

Can you said how I can hide this cursor ? 

Thanks,
François

**Comment by iiordanov** [comment]
What RDP server is this about? What version of OS?

What are you running aRDP on?

Thanks!

**Comment by iiordanov** [comment]
Fixed in latest Beta.
