### ISSUE TITLE
aRDP Pro  use with one DexStation Samsung - wrong keyboard in german - WIN10 PC

### ISSUE THREAD

**Issue by HzRDDex** [iiordanov/remote-desktop-clients#320]
Hello, I use the app to access an RD PC in my office with my Samsung S20 in a Samsung DexStation. A keyboard + mouse is connected to the DexStation via bluetooth. It works except for the keyboard layout. German is set on the PC. But only an English keyboard works (e.g. z is y). 
Resizing windows does not work. What is to be set here?
Thanks in advance.

Hallo, ich nutze die App um mit meinem Samsung S20 in einer Samsung DexStation auf einen RD PC in meinem Büro zuzugreifen. An der DexStation ist eine Tastatur+Maus über bluetooth angeschlossen. Es funktioniert bis auf das Tastaturlayout. Auf dem PC ist Deutsch eingestellt. Es funktioniert aber nur eine englische Tastatur (z.B. z ist y). Die Größe von Fenstern zu verändern funktioniert nicht. Was ist hier einzustellen?
Dank im Voraus.

**Comment by iiordanov** [comment]
This layout issue should be fixed with https://github.com/iiordanov/remote-desktop-clients/commit/11a9fe5956b6370007eb0e9cb55031bb7a0339a4. Please let me know if the issue needs to be reopened. Thanks!

**Comment by HzRDDex** [comment]
Hallo, Euere RD-App arbeit mit Samsung DEX nicht kompatibel. Was ist jetzt zu tun?

 

Mit freundlichen Grüßen

Uwe Heinze

Oberstadt 71A

35423 Lich

+491716200566

 

Von: iiordanov ***@***.***> 
Gesendet: Sonntag, 1. Mai 2022 18:13
An: iiordanov/remote-desktop-clients ***@***.***>
Cc: HzRDDex ***@***.***>; Author ***@***.***>
Betreff: Re: [iiordanov/remote-desktop-clients] aRDP Pro use with one DexStation Samsung - wrong keyboard in german - WIN10 PC (Issue #320)

 

Closed #320 <https://github.com/iiordanov/remote-desktop-clients/issues/320> .

**Comment by iiordanov** [comment]
Hello, I hope it's OK that I reply in English. I use aRDP in DEX on my Samsung Note 9 successfully - what do you mean that it is not compatible with DEX?
