### ISSUE TITLE
bVNC numpad Enter key is not captured

### ISSUE THREAD

**Issue by knyipab** [iiordanov/remote-desktop-clients#321]
In a bVNC session, the number-pad enter key is not captured by bVNC and not transfered to the remote OS.  

FYI, bVNC v5.0.5, Android 11, physical keyboard

**Comment by iiordanov** [comment]
https://github.com/iiordanov/remote-desktop-clients/commit/dcc1bb86387201ed15cec2ab8f857a027355c294 fixes this issue.
