### ISSUE TITLE
aSPICE: Symptom After a video is played, the client cannot be connected

### ISSUE THREAD

**Issue by lianbingbing** [iiordanov/remote-desktop-clients#322]
Hello!The master branch code is running, and the client cannot be connected after the server opens the video playback

**Comment by iiordanov** [comment]
Should have been fixed with https://github.com/iiordanov/remote-desktop-clients/commit/0a0e6308a9d8eb03509af7c4fafc547b52e1fbe2. The fix is out on Google Play. Please ask to reopen if it's still an issue. Thanks!
