### ISSUE TITLE
aSPICE : USB Redirection

### ISSUE THREAD

**Issue by mjuned47** [iiordanov/remote-desktop-clients#326]
USB Redirection can be enabled using this library
https://github.com/libusb/libusb

Source code includes seperate android folder , in which the method has been written in Readme.txt
https://github.com/libusb/libusb/blob/master/android/README

Even it has shown examples for usage in Android App 
https://github.com/libusb/libusb/tree/master/android/examples
Pull request for Android tells more about this :
https://github.com/libusb/libusb/pull/874

I hope this will consider in top priority. Thanks !

**Comment by iiordanov** [comment]
Quick prototype in https://github.com/iiordanov/remote-desktop-clients/tree/feature/usb_redirection_spice

A file descriptor is obtained and passed in, but it still remains to be seen how to pass that file descriptor on to the spice backend.

**Comment by iiordanov** [comment]
This got pretty interesting so I ended up working through the full implementation in one go. It's now merged to master tagged v5.0.6 and published to Beta for aSPICE Pro and Opaque @mjuned47.

**Comment by mjuned47** [comment]
That's really nice.

**Comment by iiordanov** [comment]
Did you have a chance to test this feature @mjuned47 ? Your feedback here is welcome. Thanks!

**Comment by mjuned47** [comment]
Yes, i would like to take a chance
