### ISSUE TITLE
Gtkmm button malfunction with bVNC 

### ISSUE THREAD

**Issue by NicolaPezzarossa** [iiordanov/remote-desktop-clients#332]
Client VNC device: Samsung Galaxy Tab S 10.5 LTE (Android 6.0.1)
Server VNC: x11vnc
Server VNC OS: Ubuntu 20.04.2.0
GUI library: Gtkmm-3.0  (C++11)
Compiler: g++(Ubuntu 9.3.0-17Ubuntu1~20.04) 9.3.0

Issue description: 
I'm using bVNC on a tablet to use the GUI of a C++ program that is running on a pc. I'm using the input mode "Direct, Swipe Pan". I've noticed that if I press on a button and, before releasing that button, I press on the screen with another finger, the button continue to be pressed even if I remove my fingers from the screen. I've tried with another VNC application and this does not happens, but I prefer to keep using bVNC because it is better for a lot of reasons.

I've wrote code to catch all the click done by the user: if I click or hold with a  mouse directly connected to the pc, the code catch the "click-event" and also if I push quickly with a finger on the tablet (even if another finger is on the screen). But if I hold with a finger and, before releasing, I hold with a second finger, then the "click-event" isn't detected on the second finger and when I release the screen, the button remains pressed.

**Comment by iiordanov** [comment]
Hi Nicola, tapping the screen with a second finger actually performs a right-click. If you long-tapped with the first finger before you tapped with the second, the output of xev looks like:

ButtonPress event, serial 37, synthetic NO, window 0x2c00001,
    root 0x7a6, subw 0x0, time 48852301, (164,199), root:(980,376),
    state 0x0, button 1, same_screen YES

ButtonRelease event, serial 37, synthetic NO, window 0x2c00001,
    root 0x7a6, subw 0x0, time 48855988, (168,201), root:(984,378),
    state 0x100, button 1, same_screen YES

ButtonPress event, serial 37, synthetic NO, window 0x2c00001,
    root 0x7a6, subw 0x0, time 48855988, (168,201), root:(984,378),
    state 0x0, button 3, same_screen YES

ButtonRelease event, serial 37, synthetic NO, window 0x2c00001,
    root 0x7a6, subw 0x0, time 48857715, (168,201), root:(984,378),
    state 0x400, button 3, same_screen YES

Notice the left click down / up and then then the right click down / up.

If you short-tap with the first index and then the second, the picture is like:

ButtonPress event, serial 37, synthetic NO, window 0x2c00001,
    root 0x7a6, subw 0x0, time 48969759, (151,292), root:(967,469),
    state 0x0, button 3, same_screen YES

ButtonRelease event, serial 37, synthetic NO, window 0x2c00001,
    root 0x7a6, subw 0x0, time 48969778, (148,291), root:(964,468),
    state 0x400, button 3, same_screen YES

indicating just a right-click.

Please let me know if you observe something different and I should reopen the issue.
