### ISSUE TITLE
remote-desktop-clients-libs-13.tar.gz do not contains *.so dependencies files

### ISSUE THREAD

**Issue by HONODA** [iiordanov/remote-desktop-clients#339]
hello,
   I had download the newest project ,  download remote-desktop-clients-libs-13.tar.gz by running 
`./download-prebuilt-dependencies.sh` .
I found that 
remote-desktop-clients-libs-13.tar.gz  not contains *.so dependencies files .
remote-desktop-clients-libs-12.tar.gz  contains *.so dependencies files
**the project generated normally**,but when I **try to connect the spice server,the error message showing like:** 
![Screenshot_20220204-204218](https://user-images.githubusercontent.com/19503005/152531173-12ba4955-882e-4a76-8cf8-6ba5461156a6.jpg)

and I **try to tar remote-desktop-clients-libs-12.tar.gz  *.so file into project . the other error showing like** :
![2022-02-04 20-47-31 的屏幕截图](https://user-images.githubusercontent.com/19503005/152532374-77b9c03d-bfe6-4aa7-a791-513945da162b.png)

                 THANK!

**Comment by iiordanov** [comment]
Thanks for reporting! Check now.
