### ISSUE TITLE
GPLv3 code in bVNC

### ISSUE THREAD

**Issue by bgilbert** [iiordanov/remote-desktop-clients#34]
According to `LICENSE-bVNC`, the entire bVNC codebase is GPLv2-compatible.  However, since commit iiordanov/remote-desktop-clients@10166068, several of its source files have had GPLv3 license blocks attached:

- `eclipse_projects/bVNC/jni/src/android/android-io.c`
- `eclipse_projects/bVNC/jni/src/android/android-io.h`
- `eclipse_projects/bVNC/jni/src/android/android-service.c`
- `eclipse_projects/bVNC/jni/src/android/android-service.h`

Is there any chance you could relicense those files back to GPLv2?

**Comment by iiordanov** [comment]
Hi @bgilbert, in fact I've had to update the license of the entire code-base to GPLv3 because of incompatibility with the Apache license. A previous author had included an Apache-licensed file with the application and it was necessary.
