### ISSUE TITLE
aSPICE USB Redirection : feature request

### ISSUE THREAD

**Issue by mjuned47** [iiordanov/remote-desktop-clients#340]
As USB Redirection is implemented, there is following things that can be enhanced :
1) There should be USB toggle botton after connected to server(VM), which shows list of usb devices connected and which one is redirected , basically it is manual usb redirecting.
2) there can be an option on server settings, to enable or disable usb redirection

**Comment by mjuned47** [comment]
@iiordanov also usb redirection is working perfectly. But one issue 
When spice is connected to vm, it doesn't recognise usb input ..we have to disconnect and reconnect to vm again to get usb input(spice ask to use bla usb device).
So there should be usb button when running vm which shows list of usb device connected. And from that we can redirect the one we wants

**Comment by iiordanov** [comment]
Could you please open two new issues with the enhancements you seek?

One to cover the UI work, and the second to cover any bugs you are
encountering.

My testing doesn't show the issue you describe where you need to
disconnect. What device are attaching? What is the oVirt version? What is
the host Android device?  Please make sure to include any and all steps we
would need to perform to reproduce this.

**Comment by mjuned47** [comment]
Will open new issue of bug or problem
