### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dstmath** [iiordanov/remote-desktop-clients#341]
remote-desktop-clients/remoteClientLib/jni/libs/cerbero/build/dist/android_universal/armv7/lib/libgdk_pixbuf-2.0.so: error: undefined reference to 'jpeg_destroy_decompress', version 'LIBJPEG_8.0'
....
....
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [rsvg-convert] Error 1
make[2]: Leaving directory `/project/spice/android/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/build/sources/android_universal/armv7/librsvg-2.40.20'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/project/spice/android/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/build/sources/android_universal/armv7/librsvg-2.40.20'
make: *** [all] Error 2

Recipe 'librsvg' failed at the build step 'compile'

**Comment by iiordanov** [comment]
What OS/distribution/Version is this?

What if you follow the Docker based build instructions instead?

**Comment by dstmath** [comment]
debian 11.
the docker build has the same error.

**Comment by dstmath** [comment]
here is the docker based build log, give me some help, thanks.
[librsvg-compile.log](https://github.com/iiordanov/remote-desktop-clients/files/8146709/librsvg-compile.log)

**Comment by dstmath** [comment]
solved,thx.

**Comment by iiordanov** [comment]
Hey, sorry I didn't have time to loon this weekend. Any suggestions on what
was wrong?

Thanks!
