### ISSUE TITLE
Key Up/Down as Events: a Feature Request

### ISSUE THREAD

**Issue by srjreid** [iiordanov/remote-desktop-clients#348]
My desired use for aRDP is to convert a high-end smartphone into a remote workstation.  My line of work is game development.  So my use-case is to connect to a high-end PC remotely, write C++ code in Visual Studio, and run the game in windowed mode.  The input events to the game are typically keyboard+mouse, which include the WASD keys, Escape Key, Left Shift key, Space key, and a few letter keys including F to interact, V for ability, Q, E, and R, for other actions.  For the UI, arrow cursor keys would be used, and the Enter key to go forward/accept, or Escape key to go back/cancel.

As you could already tell, I would be using a connected physical keyboard via Bluetooth, as well as a mouse.  The issue is that aRDP will send every key as a key up/down pair simultaneously.  This results in the D key of WASD producing a character "stutter step" to the right as though a person was rapidly tapping the D key in real life on a physical keyboard.  The desired behavior is that the D key will send a "Key Down" even to the remote desktop, and when the key is released, it sends a "Key Up" event.

Unfortunately the keyboard input mechanism of Android is treating "letter" inputs (including other keys like digits) as though they were tapped on the on-screen keyboard.  But there is good news about other keys: they can possibly be interpreted to have key up/down events.  This includes modifier keys like Ctrl, Alt, Shift, and other keys like the Arrow Cursor Keys, Escape, Return, Backspace.  I can alter my game project to use these keys instead of WASD while in "remote development mode".

I've already contacted the coder on this project, and they were able to create a draft beta which sends the modifier keys such as Ctrl, Alt, and Shift as key up/down events.  So, it is quite hopeful that this feature can be implemented.  Here is a full list of desired keys, which should be enough to at least cover the basic actions for players in most game projects:

- Escape
- Backspace
- Return
- Arrow Keys (Up, Down, Left, and Right)
- Tab

Most games today will support Up, Down, Left, and Right along with Enter/Return and Escape for UI navigation.  This coincides with the gamepad Dpad and forward + back buttons to navigate menus on console and PC games.  So it goes without saying that these 6 keys with full key up/down event support is at least 80% of the keyboard inputs to a game.

Here are some other keys that might be helpful from a development standpoint:

- Function Keys
- Page Up/Down
- Insert/Delete
- Home/End
- Numpad keys including math symbols and the Numpad Enter/Return key

These keys are not typically useful in keyboard+mouse games, but they might be helpful from a game developer standpoint.  For instance, F1 key could be used to toggle debug menus or spawn power-ups or enemies.  The Page Up/Down and nearby keys could be used for extended player actions.

**Comment by iiordanov** [comment]
Hey @srjreid, thanks for the detailed description. I thought I understood the whole feature request, but it appears I needed it restarted to really understand one aspect of the issue.

I hadn't understood that it was not the modifier being down, then the key down/up then the modifier up between each event. Rather even the keys going down/up still caused windows to stutter the input!

Now that I understood, here is a version that does everything we want, and it also fixes what appears to be a long-standing issue where RCTRL and RALT were being sent as LCTRL + Mode Change and RALT + Mode Change respectively.

https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.7/freeaRDP-v5.0.7_1-final.apk

Let me know if this works well now. Also, any additional testing you can perform to try to break it including:

- enabling unicode input in the advanced settings
- using the soft keyboard

would help me detect any regressions from this work. Your help is immensely appreciated!

Sincerely,
iordan

**Comment by srjreid** [comment]
Great news!

All keys appear to be working as described in the original post!  Here is a photo of the beta test working in action:

https://imgur.com/a/nRcl5RO

So what is happening here is that Meshlicous mini PC to the right is an Intel 12700k.  This will be the host PC I am connecting to.  The TV screen is displaying Samsung Dex from my new Galaxy S22 Ultra phone.  It is running the beta aRDP client in windowed mode.  The remote desktop -- i.e. the Meshlicous PC -- is running Visual Studio and debugging the game in windowed mode.  The keyboard is a wireless bluetooth keyboard connected to the phone.  The phone itself is being used as a camera to take a photo of the TV running Samsung Dex from the very same phone itself.

I am able to move the character via keyboard Cursor Arrow keys, and using the Right Shift key to perform the Dash action.  I currently do not have a Bluetooth mouse, so I was using the S-Pen instead on the S22 Ultra, which can act as a trackpad for Samsung Dex.  The mouse is used for aiming and shooting the gun.

This is quite an exciting use-case scenario.  I eagerly await for it to become available in the Pro version so I can test it with sound on the device, which actually becomes the TV in Dex Mode.  It is around that time where I've started looking around for a laptop upgrade, but I didn't feel like spending more money on a new laptop I never really wanted.  I am going to give this new setup via my phone a good go to see if I can get by in a remote setting.  So instead of buying let's say a Surface Pro with an i7 and 1 TB of storage which comes to over $2500 CAD, I can use my much, much faster mini PC without spending any extra money.

**Comment by iiordanov** [comment]
@srjreid The new version is up on Google Play in Beta. Give it a try, and also do test the on-screen keys if you have a chance because they were impacted by the change as well and needed regression fixes.

Let me know if I need to reopen this issue for some reason.

Thanks again!
iordan
