### ISSUE TITLE
aSpice The program crashes after multiple disconnections and reconnections

### ISSUE THREAD

**Issue by buhuixxx** [iiordanov/remote-desktop-clients#359]
aSpice The program crashes after multiple disconnections and reconnections

**Comment by mjuned47** [comment]
Yes this happens with me to
Android version : 7
Device : Redmi Note 4
aSPICE Version : 0.5.6(with free and pro both)

**Comment by iiordanov** [comment]
This is a known issue that I've been gradually improving. The newest version v5.0.8 has stability improvements that you should try.

**Comment by buhuixxx** [comment]
My last pull code was March 31, the version is v5.0.8 ,but the bug still exists

**Comment by buhuixxx** [comment]
My last pull code was March 31, the version is v5.0.8 ,but the bug still exists

**Comment by iiordanov** [comment]
https://github.com/iiordanov/remote-desktop-clients/commit/754495a64747e946aea6427730ace8031380e10e
