### ISSUE TITLE
mouse clicks in wrong spot on large monitor layout

### ISSUE THREAD

**Issue by justdave** [iiordanov/remote-desktop-clients#366]
I have a MacBook Pro with two 4K monitors hooked up to it, one to the left and one to the right of the laptop, so there are three total screens, all in a horizontal row. With bVNC Pro set to "Direct, Swipe Pan" for the input mode, tapping anywhere on the center or right-most displays causes the click event to happen at the border between the leftmost and center displays.  Clicking in the left-most display goes where it should.  Are the mouse controls from bVNC constrained to only the left-most monitor instead of the entire available desktop space?

bVNC Pro v5.0.8 (build 115084)
Can reproduce on both Android 12 on a Samsung Galaxy S10+ and Android 12 on a Samsung Galaxy Tab S6.

**Comment by iiordanov** [comment]
No it is not constrained. I was experiencing this issue with older Mac OS,
but I now have Catalina, Big Sur, and Monterrey on three different macs,
and connecting any number of monitors doesn't exhibit this issue.

What is running on your MacBook Pro?

By the way, have you tried bVNC on Mac OS X or iOS? It's available on the
App Store.

**Comment by justdave** [comment]
The MacBook Pro in question has Big Sur on it.

**Comment by justdave** [comment]
OK, I just played around with it a bit, and as long as I have the menu bar on the left or center screens in the Arrangement panel, then it all works fine. If I have the menu bar on the right-most screen, then the mouse clicks only work on the left-most screen.  That all just seems weird.....

**Comment by iiordanov** [comment]
Thanks for figuring that out, it's great (albeit weird).

I have Mission Control -> Displays have separate Spaces

which allows apps to show their menus on the monitor where they are in the foreground (much preferred for me).

Does that change anything?

**Comment by justdave** [comment]
> I have Mission Control -> Displays have separate Spaces

I already have that set as well.  By moving the menu bar around I meant the one that designates which display is primary in the Displays -> Arrangement panel.
