### ISSUE TITLE
I can set the resolution when starting a VM for the first time, when I disconnect and reconnect it, it couldn't work

### ISSUE THREAD

**Issue by buhuixxx** [iiordanov/remote-desktop-clients#368]
Guest OS:windows 10
Version:aSpice Free 5.0.9

**Comment by iiordanov** [comment]
What are you running this VM on? libvirtd, Proxmox, oVirt, something else?

**Comment by iiordanov** [comment]
In the absence of more information, closing this issue. Please let me know if it should be reopened and provide details on how to reproduce the issue.
