### ISSUE TITLE
 master branch Android4.4 still reported an error

### ISSUE THREAD

**Issue by lianbingbing** [iiordanov/remote-desktop-clients#369]
![image](https://user-images.githubusercontent.com/16917954/168859978-3a73f97a-0aa7-4562-bed8-93d6bbcbe4a2.png)

**Comment by iiordanov** [comment]
Hi there,

I am unable to support such old Android versions in part because the underlying libraries the app depends on no longer support them. Your fixes and contributions are welcome as always.
