### ISSUE TITLE
Send Ctrl+Alt+Delete key cause Android App crash

### ISSUE THREAD

**Issue by max32002** [iiordanov/remote-desktop-clients#37]
I download aSpice from Google Play, app terminated after I send Ctrl+Alt+Delete key to guest OS.

Crash source code:
keyboardMapper.processAndroidKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN, 112));
 
Root cause is system unable convert VK_DEL to correct key_code. There are another issue “Send key dialog” is unable to send “Delete” key due to unable convert “Delete” key to Unicode.

![image002](https://cloud.githubusercontent.com/assets/4498233/5660730/a31fa71e-975e-11e4-83d8-96646065cec9.jpg)

**Comment by chenqi0623** [comment]
I think the scan code of VK_DEL is 0x53~

**Comment by max32002** [comment]
\spice-gtk-0.26\gtk\vncdisplaykeymap_win322xtkbd.c
  [0x2c] = 0x54,       /* 44 (VK_SNAPSHOT ???) => 84 via 99 (KEY_SYSRQ) */
  [0x2d] = 0x152,      /* 45 (VK_INSERT) => 338 via 110 (KEY_INSERT) */
  [0x2e] = 0x153,      /* 46 (VK_DELETE) => 339 via 111 (KEY_DELETE) */

**Comment by iiordanov** [comment]
Hey guys,

The latest version of aSPICE should not suffer from this anymore. Please
confirm and close if so.

Cheers!
iordan

On Fri, Feb 13, 2015 at 6:24 AM, Max <notifications@github.com> wrote:

> \spice-gtk-0.26\gtk\vncdisplaykeymap_win322xtkbd.c
> [0x2c] = 0x54, /* 44 (VK_SNAPSHOT ???) => 84 via 99 (KEY_SYSRQ)
> */ [0x2d] = 0x152, /* 45 (VK_INSERT) => 338 via 110 (KEY_INSERT)
> */ [0x2e] = 0x153, /* 46 (VK_DELETE) => 339 via 111 (KEY_DELETE) */
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iiordanov/remote-desktop-clients/issues/37#issuecomment-74239910>
> .
>



-- 
The conscious mind has only one thread of execution.

**Comment by max32002** [comment]
Thank you very much.

Cheers!
Max
