### ISSUE TITLE
Master branch running on Android4.4 (19), connection error reported

### ISSUE THREAD

**Issue by lianbingbing** [iiordanov/remote-desktop-clients#370]
![image](https://user-images.githubusercontent.com/16917954/168860496-68cab957-4c03-48e1-a09b-552963210f13.png)

I modified the gradle.properties file and changed SDK_VERSION to 19 (Android4.4,armv7a), but after running successfully, the connection error was reported and the wrong picture was posted
![image](https://user-images.githubusercontent.com/16917954/168861780-388b04d2-1f46-4281-9b4a-c1e1e933997b.png)

**Comment by iiordanov** [comment]
Hi there,

I am unable to support such old Android versions in part because the underlying libraries the app depends on no longer support them. Your fixes and contributions are welcome as always.
