### ISSUE TITLE
Java Error when trying to connect...

### ISSUE THREAD

**Issue by Main-2022** [iiordanov/remote-desktop-clients#371]
Hi all,
I am new here and hope I post in the right area.
When I try to connect then I am getting an Error Message (attached at the end) on my Android 12 Cell Phone 
Can somebody please help?
Thanks in advance.
Regards.
...Manni

--------- beginning of system
05-19 13:45:48.106 21747 21747 I Quality : Skipped: false 2
05-19 13:45:48.128 21747 21747 I Quality : Skipped: false 2
05-19 13:45:49.304 21747 21747 I Quality : Skipped: false 2
05-19 13:45:49.617 21747 21747 V OplusZoomWindowDecorViewHelper: removeZoomView
--------- beginning of main
05-19 13:49:02.949 21747 21776 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@706eaec
05-19 13:49:02.967 21747 21747 D Utils   : Version of com.iiordanov.bVNC is v5.1.0_115103
05-19 13:49:02.967 21747 21747 I ConnectionGridActivity: onResume of version v5.1.0_115103
05-19 13:49:02.978 21747 21747 I ConnectionGridActivity: onResumeFragments called
05-19 13:49:02.984 21747 21747 I Quality : Skipped: false 1
05-19 13:49:02.984 21747 21747 D LabeledImageApapter: Now setting label at position: 0 to: Heizung
05-19 13:49:02.984 21747 21747 D LabeledImageApapter:xxxxxxxxxx
05-19 13:49:02.985 21747 21747 E ThemeUtils: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
05-19 13:49:02.997 21747 21747 D LabeledImageApapter: Now setting label at position: 0 to: Heizung
05-19 13:49:02.997 21747 21747 D LabeledImageApapter: xxxxxxxxxx
05-19 13:49:03.005 21747 21776 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
05-19 13:49:03.684 21747 21747 V AutofillManager: requestHideFillUi(null): anchor = null
05-19 13:49:03.743 21747 21747 I ConnectionGridActivity: Launch Connection
05-19 13:49:03.760 21747 21747 I Quality : Skipped: false 1
05-19 13:49:03.763 21747 21747 I ConnectionGridActivity: onPause
05-19 13:49:03.769 21747 21776 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@c8b0eed
05-19 13:49:03.772 21747 21747 D RemoteCanvasActivity: OnCreate called
05-19 13:49:03.773 21747 21747 W .iiordanov.bVN: Accessing hidden field Landroid/view/ViewConfiguration;->sHasPermanentMenuKey:Z (max-target-p, reflection, denied)
05-19 13:49:03.780 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.780 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.780 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.781 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.781 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.781 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.783 21747 21747 D WindowManager: Add to mViews: DecorView@76e95da[Connecting…],pkg= com.iiordanov.bVNC
05-19 13:49:03.787 21747 21747 D Vibrator: SystemVibrator Created
05-19 13:49:03.788 21747 21747 D RemoteCanvasActivity: Initializing classic connection from Serializeable.
05-19 13:49:03.788 21747 21747 D RemoteCanvasActivity: Initializing classic connection from Serializeable, loading values.
05-19 13:49:03.788 21747 21747 D ConnectionBean: loadFromSharedPreferences called
05-19 13:49:03.788 21747 21747 D RemoteCanvasActivity: Initializing classic connection from Serializeable, toolbar X coor 0
05-19 13:49:03.788 21747 21747 D RemoteCanvasActivity: Initializing classic connection from Serializeable, toolbar Y coor 0
05-19 13:49:03.791 21747 21747 I RemoteCanvas: Initializing connection to: xxxxxxxxxx
05-19 13:49:03.791 21747 21747 D RemoteKeyboard: debugLog: false
05-19 13:49:03.791 21747 21747 D RemoteCanvasActivity: continueConnecting
05-19 13:49:03.791 21747 25282 I RemoteCanvas: Establishing VNC session to: xxxxxxxxxx
05-19 13:49:03.791 21747 25282 V RfbProto: Connecting to server: xxxxxxxxxx
05-19 13:49:03.792 21747 25283 D OplusClipboardManager: getUserPathInfo size = 0
05-19 13:49:03.792 21747 25283 D ClipboardManagerExt: getUserPathInfo success
05-19 13:49:03.792 21747 21747 D RemoteCanvasActivity: OnCreate complete
05-19 13:49:03.793 21747 21747 I RemoteCanvasActivity: onResume called.
05-19 13:49:03.794 21747 21747 D WindowManager: Add to mViews: DecorView@7a40f83[RemoteCanvasActivity],pkg= com.iiordanov.bVNC
05-19 13:49:03.797 21747 21747 I Quality : Skipped: false 3
05-19 13:49:03.803 21747 21747 V OplusZoomWindowDecorViewHelper: setLastReportedMergedConfiguration mZoomDisplayHeight: 3216 getDecorView.124687834
05-19 13:49:03.812 21747 21775 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
05-19 13:49:03.815 21747 21747 V OplusZoomWindowDecorViewHelper: setLastReportedMergedConfiguration mZoomDisplayHeight: 3216 getDecorView.128192387
05-19 13:49:03.816 21747 21747 D RemoteCanvasActivity: onGlobalLayout: start
05-19 13:49:03.816 21747 21747 D RemoteCanvasActivity: onGlobalLayout: getWindowVisibleDisplayFrame: Rect(0, 128 - 1440, 3040)
05-19 13:49:03.816 21747 21747 D RemoteCanvasActivity: onGlobalLayout: canvas.myDrawable is null
05-19 13:49:03.816 21747 21747 D RemoteCanvasActivity: onGlobalLayout: before: r.bottom: 3040 rootViewHeight: 2912 re.top: 128 re.bottom: 3040 layoutKeysBottom: 0 rootViewBottom: 3088 toolbarBottom: 1568 diffLayoutKeysPosition: 2912 diffToolbarPosition: -176
05-19 13:49:03.816 21747 21747 D RemoteCanvasActivity: onGlobalLayout: Less than 19% of screen is covered
05-19 13:49:03.816 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting on-screen buttons down by: 2912
05-19 13:49:03.816 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting arrow keys by: 1440
05-19 13:49:03.816 21747 21747 D RemoteCanvasActivity: onGlobalLayout: after: r.bottom: 3040 rootViewHeight: 2912 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1568 diffLayoutKeysPosition: 2912 diffToolbarPosition: -176
05-19 13:49:03.826 21747 21747 I Quality : Skipped: false 2
05-19 13:49:03.827 21747 21747 D RemoteCanvasActivity: onGlobalLayout: start
05-19 13:49:03.827 21747 21747 D RemoteCanvasActivity: onGlobalLayout: getWindowVisibleDisplayFrame: Rect(0, 128 - 1440, 3040)
05-19 13:49:03.827 21747 21747 D RemoteCanvasActivity: onGlobalLayout: canvas.myDrawable is null
05-19 13:49:03.827 21747 21747 D RemoteCanvasActivity: onGlobalLayout: before: r.bottom: 3040 rootViewHeight: 2912 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1392 diffLayoutKeysPosition: 0 diffToolbarPosition: 0
05-19 13:49:03.827 21747 21747 D RemoteCanvasActivity: onGlobalLayout: Less than 19% of screen is covered
05-19 13:49:03.827 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting on-screen buttons down by: 0
05-19 13:49:03.827 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting arrow keys by: 0
05-19 13:49:03.827 21747 21747 D RemoteCanvasActivity: onGlobalLayout: after: r.bottom: 3040 rootViewHeight: 2912 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1392 diffLayoutKeysPosition: 0 diffToolbarPosition: 0
05-19 13:49:03.828 21747 21775 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
05-19 13:49:03.828 21747 21747 D RemoteCanvasActivity: OnCreateOptionsMenu called
05-19 13:49:03.829 21747 21747 D RemoteCanvasActivity: OnCreateOptionsMenu complete
05-19 13:49:03.834 21747 21747 D RemoteCanvasActivity: onGlobalLayout: start
05-19 13:49:03.834 21747 21747 D RemoteCanvasActivity: onGlobalLayout: getWindowVisibleDisplayFrame: Rect(0, 128 - 1440, 3040)
05-19 13:49:03.834 21747 21747 D RemoteCanvasActivity: onGlobalLayout: canvas.myDrawable is null
05-19 13:49:03.834 21747 21747 D RemoteCanvasActivity: onGlobalLayout: before: r.bottom: 3040 rootViewHeight: 2912 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1568 diffLayoutKeysPosition: 0 diffToolbarPosition: -176
05-19 13:49:03.834 21747 21747 D RemoteCanvasActivity: onGlobalLayout: Less than 19% of screen is covered
05-19 13:49:03.834 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting on-screen buttons down by: 0
05-19 13:49:03.834 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting arrow keys by: 0
05-19 13:49:03.834 21747 21747 D RemoteCanvasActivity: onGlobalLayout: after: r.bottom: 3040 rootViewHeight: 2912 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1568 diffLayoutKeysPosition: 0 diffToolbarPosition: -176
05-19 13:49:03.855 21747 21747 D RemoteCanvasActivity: onGlobalLayout: start
05-19 13:49:03.855 21747 21747 D RemoteCanvasActivity: onGlobalLayout: getWindowVisibleDisplayFrame: Rect(0, 128 - 1440, 3040)
05-19 13:49:03.855 21747 21747 D RemoteCanvasActivity: onGlobalLayout: canvas.myDrawable is null
05-19 13:49:03.855 21747 21747 D RemoteCanvasActivity: onGlobalLayout: before: r.bottom: 3040 rootViewHeight: 2912 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1392 diffLayoutKeysPosition: 0 diffToolbarPosition: 0
05-19 13:49:03.855 21747 21747 D RemoteCanvasActivity: onGlobalLayout: Less than 19% of screen is covered
05-19 13:49:03.855 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting on-screen buttons down by: 0
05-19 13:49:03.855 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting arrow keys by: 0
05-19 13:49:03.855 21747 21747 D RemoteCanvasActivity: onGlobalLayout: after: r.bottom: 3040 rootViewHeight: 2912 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1392 diffLayoutKeysPosition: 0 diffToolbarPosition: 0
05-19 13:49:03.856 21747 21747 D RemoteCanvasActivity: correctAfterRotation
05-19 13:49:03.858 21747 25282 I RfbProto: Negotiating repeater/proxy connection
05-19 13:49:03.931 21747 25282 W System.err: java.io.EOFException
05-19 13:49:03.931 21747 25282 W System.err: 	at java.io.DataInputStream.readFully(DataInputStream.java:200)
05-19 13:49:03.931 21747 25282 W System.err: 	at com.iiordanov.bVNC.RfbProto.readFully(RfbProto.java:1685)
05-19 13:49:03.931 21747 25282 W System.err: 	at com.iiordanov.bVNC.RfbProto.readFully(RfbProto.java:1672)
05-19 13:49:03.931 21747 25282 W System.err: 	at com.iiordanov.bVNC.RfbProto.readVersionMsg(RfbProto.java:564)
05-19 13:49:03.931 21747 25282 W System.err: 	at com.iiordanov.bVNC.RfbProto.initializeAndAuthenticate(RfbProto.java:468)
05-19 13:49:03.931 21747 25282 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.startVncConnection(RemoteCanvas.java:600)
05-19 13:49:03.931 21747 25282 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.access$200(RemoteCanvas.java:111)
05-19 13:49:03.931 21747 25282 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas$5.run(RemoteCanvas.java:408)
05-19 13:49:03.932 21747 25282 E RemoteCanvas: java.lang.Exception: Connection to VNC server failed with reason: 
05-19 13:49:03.932 21747 25282 E RemoteCanvas: 
05-19 13:49:03.932 21747 25282 E RemoteCanvas: java.io.EOFException
05-19 13:49:03.932 21747 25282 E RemoteCanvas: 	at java.io.DataInputStream.readFully(DataInputStream.java:200)
05-19 13:49:03.932 21747 25282 E RemoteCanvas: 	at com.iiordanov.bVNC.RfbProto.readFully(RfbProto.java:1685)
05-19 13:49:03.932 21747 25282 E RemoteCanvas: 	at com.iiordanov.bVNC.RfbProto.readFully(RfbProto.java:1672)
05-19 13:49:03.932 21747 25282 E RemoteCanvas: 	at com.iiordanov.bVNC.RfbProto.readVersionMsg(RfbProto.java:564)
05-19 13:49:03.932 21747 25282 E RemoteCanvas: 	at com.iiordanov.bVNC.RfbProto.initializeAndAuthenticate(RfbProto.java:468)
05-19 13:49:03.932 21747 25282 E RemoteCanvas: 	at com.iiordanov.bVNC.RemoteCanvas.startVncConnection(RemoteCanvas.java:600)
05-19 13:49:03.932 21747 25282 E RemoteCanvas: 	at com.iiordanov.bVNC.RemoteCanvas.access$200(RemoteCanvas.java:111)
05-19 13:49:03.932 21747 25282 E RemoteCanvas: 	at com.iiordanov.bVNC.RemoteCanvas$5.run(RemoteCanvas.java:408)
05-19 13:49:03.932 21747 25282 W System.err: java.lang.Exception: Connection to VNC server failed with reason: 
05-19 13:49:03.932 21747 25282 W System.err: 
05-19 13:49:03.932 21747 25282 W System.err: java.io.EOFException
05-19 13:49:03.932 21747 25282 W System.err: 	at java.io.DataInputStream.readFully(DataInputStream.java:200)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RfbProto.readFully(RfbProto.java:1685)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RfbProto.readFully(RfbProto.java:1672)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RfbProto.readVersionMsg(RfbProto.java:564)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RfbProto.initializeAndAuthenticate(RfbProto.java:468)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.startVncConnection(RemoteCanvas.java:600)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.access$200(RemoteCanvas.java:111)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas$5.run(RemoteCanvas.java:408)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.startVncConnection(RemoteCanvas.java:617)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.access$200(RemoteCanvas.java:111)
05-19 13:49:03.932 21747 25282 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas$5.run(RemoteCanvas.java:408)
05-19 13:49:03.933 21747 25282 V RfbProto: RFB socket closed
05-19 13:49:03.933 21747 25282 D RemoteCanvas: Saving screenshot to /data/user/0/com.iiordanov.bVNC/files/b6cc0206-b29f-4238-831c-758da0554198.png
05-19 13:49:03.933 21747 25282 V RemoteCanvas: Cleaning up resources
05-19 13:49:03.933 21747 21747 V OplusZoomWindowDecorViewHelper: removeZoomView
05-19 13:49:03.950 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.950 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.950 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.950 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.950 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.950 21747 21747 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
05-19 13:49:03.953 21747 21747 D WindowManager: Add to mViews: DecorView@3f17742[RemoteCanvasActivity],pkg= com.iiordanov.bVNC
05-19 13:49:03.970 21747 21747 V OplusZoomWindowDecorViewHelper: setLastReportedMergedConfiguration mZoomDisplayHeight: 3216 getDecorView.66156354
05-19 13:49:03.978 21747 21779 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
05-19 13:49:03.986 21747 21747 I Quality : Skipped: false 1
05-19 13:49:04.200 21747 21747 D RemoteCanvasActivity: onGlobalLayout: start
05-19 13:49:04.200 21747 21747 D RemoteCanvasActivity: onGlobalLayout: getWindowVisibleDisplayFrame: Rect(0, 128 - 1440, 3040)
05-19 13:49:04.200 21747 21747 D RemoteCanvasActivity: onGlobalLayout: canvas.myDrawable is null
05-19 13:49:04.200 21747 21747 D RemoteCanvasActivity: onGlobalLayout: before: r.bottom: 3040 rootViewHeight: 3088 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1656 diffLayoutKeysPosition: 0 diffToolbarPosition: -264
05-19 13:49:04.200 21747 21747 D RemoteCanvasActivity: onGlobalLayout: Less than 19% of screen is covered
05-19 13:49:04.200 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting on-screen buttons down by: 0
05-19 13:49:04.200 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting arrow keys by: 0
05-19 13:49:04.200 21747 21747 D RemoteCanvasActivity: onGlobalLayout: after: r.bottom: 3040 rootViewHeight: 3088 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1656 diffLayoutKeysPosition: 0 diffToolbarPosition: -264
05-19 13:49:04.201 21747 21747 D RemoteCanvasActivity: onGlobalLayout: start
05-19 13:49:04.201 21747 21747 D RemoteCanvasActivity: onGlobalLayout: getWindowVisibleDisplayFrame: Rect(0, 128 - 1440, 3040)
05-19 13:49:04.201 21747 21747 D RemoteCanvasActivity: onGlobalLayout: canvas.myDrawable is null
05-19 13:49:04.201 21747 21747 D RemoteCanvasActivity: onGlobalLayout: before: r.bottom: 3040 rootViewHeight: 3088 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1392 diffLayoutKeysPosition: 0 diffToolbarPosition: 0
05-19 13:49:04.201 21747 21747 D RemoteCanvasActivity: onGlobalLayout: Less than 19% of screen is covered
05-19 13:49:04.201 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting on-screen buttons down by: 0
05-19 13:49:04.201 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting arrow keys by: 0
05-19 13:49:04.201 21747 21747 D RemoteCanvasActivity: onGlobalLayout: after: r.bottom: 3040 rootViewHeight: 3088 re.top: 128 re.bottom: 3040 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1392 diffLayoutKeysPosition: 0 diffToolbarPosition: 0
05-19 13:49:04.258 21747 22112 D OpenGLRenderer: endAllActiveAnimators on 0xb40000787ba3e800 (GridView) with handle 0xb40000786cc924c0
05-19 13:49:04.912 21747 21747 V AutofillManager: requestHideFillUi(null): anchor = null
05-19 13:49:04.993 21747 21747 V OplusZoomWindowDecorViewHelper: removeZoomView
05-19 13:49:05.000 21747 22112 D OpenGLRenderer: endAllActiveAnimators on 0xb40000786cd25e00 (RippleDrawable) with handle 0xb400007897bff080
05-19 13:49:05.024 21747 21747 I Quality : Skipped: true 3
05-19 13:49:05.036 21747 21775 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@706eaec
05-19 13:49:05.039 21747 21747 D RemoteCanvasActivity: onGlobalLayout: start
05-19 13:49:05.039 21747 21747 D RemoteCanvasActivity: onGlobalLayout: getWindowVisibleDisplayFrame: Rect(0, 128 - 1440, 3216)
05-19 13:49:05.039 21747 21747 D RemoteCanvasActivity: onGlobalLayout: canvas.myDrawable is null
05-19 13:49:05.039 21747 21747 D RemoteCanvasActivity: onGlobalLayout: before: r.bottom: 3216 rootViewHeight: 3088 re.top: 128 re.bottom: 3216 layoutKeysBottom: 2912 rootViewBottom: 3088 toolbarBottom: 1392 diffLayoutKeysPosition: 176 diffToolbarPosition: 88
05-19 13:49:05.039 21747 21747 D RemoteCanvasActivity: onGlobalLayout: Less than 19% of screen is covered
05-19 13:49:05.039 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting on-screen buttons down by: 176
05-19 13:49:05.039 21747 21747 D RemoteCanvasActivity: onGlobalLayout: shifting arrow keys by: 0
05-19 13:49:05.039 21747 21747 D RemoteCanvasActivity: onGlobalLayout: after: r.bottom: 3216 rootViewHeight: 3088 re.top: 128 re.bottom: 3216 layoutKeysBottom: 3088 rootViewBottom: 3088 toolbarBottom: 1392 diffLayoutKeysPosition: 176 diffToolbarPosition: 88
05-19 13:49:05.039 21747 21747 D RemoteCanvasActivity: correctAfterRotation
05-19 13:49:05.041 21747 21747 D Utils   : Version of com.iiordanov.bVNC is v5.1.0_115103
05-19 13:49:05.041 21747 21747 I ConnectionGridActivity: onResume of version v5.1.0_115103
05-19 13:49:05.045 21747 21747 I ConnectionGridActivity: onResumeFragments called
05-19 13:49:05.047 21747 21747 D LabeledImageApapter: Now setting label at position: 0 to: Heizung
05-19 13:49:05.047 21747 21747 D LabeledImageApapter: xxxxxxxxxx
05-19 13:49:05.048 21747 21747 E ThemeUtils: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
05-19 13:49:05.057 21747 21747 D LabeledImageApapter: Now setting label at position: 0 to: Heizung
05-19 13:49:05.057 21747 21747 D LabeledImageApapter: xxxxxxxxxx
05-19 13:49:05.058 21747 21747 D LabeledImageApapter: Now setting label at position: 0 to: Heizung
05-19 13:49:05.058 21747 21747 D LabeledImageApapter: xx
 13:49:05.069 21747 21775 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
05-19 13:49:05.498 21747 21747 V RfbProto: RFB socket closed
05-19 13:49:05.498 21747 21747 D RemoteCanvas: Saving screenshot to /data/user/0/com.iiordanov.bVNC/files/b6cc0206-b29f-4238-831c-758da0554198.png
05-19 13:49:05.498 21747 21747 V RemoteCanvas: Cleaning up resources
05-19 13:49:05.498 21747 21747 V OplusZoomWindowDecorViewHelper: removeZoomView
05-19 13:49:06.356 21747 21747 V AutofillManager: requestHideFillUi(null): anchor = null
05-19 13:49:06.467 21747 21747 D ConnectionGridActivity: onMenuOpened
05-19 13:49:06.472 21747 21747 D ConnectionGridActivity: onMenuOpened
05-19 13:49:06.472 21747 21747 D ConnectionGridActivity: Default Input Mode Item: TOUCH_ZOOM_MODE
05-19 13:49:06.472 21747 21747 D ConnectionGridActivity: Input Mode Item: TOUCHPAD_MODE
05-19 13:49:06.472 21747 21747 D ConnectionGridActivity: Input Mode Item: TOUCH_ZOOM_MODE
05-19 13:49:06.472 21747 21747 D ConnectionGridActivity: Input Mode Item: TOUCH_ZOOM_MODE_DRAG_PAN
05-19 13:49:06.472 21747 21747 D ConnectionGridActivity: Input Mode Item: SINGLE_HANDED_MODE
05-19 13:49:06.480 21747 21747 V TextView: notifyAutoFillManagerAfterTextChanged
05-19 13:49:06.480 21747 21747 V AutofillManager: notifyValueChanged(1073741862): ignoring on state UNKNOWN
05-19 13:49:06.487 21747 21747 V TextView: notifyAutoFillManagerAfterTextChanged
05-19 13:49:06.487 21747 21747 V AutofillManager: notifyValueChanged(1073741863): ignoring on state UNKNOWN
05-19 13:49:06.490 21747 21747 D WindowManager: Add to mViews: android.widget.PopupWindow$PopupDecorView{c6009bf V.E...... R.....I. 0,0-0,0},pkg= com.iiordanov.bVNC
05-19 13:49:06.493 21747 21747 I Quality : Skipped: false 1
05-19 13:49:06.502 21747 21747 V TextView: notifyAutoFillManagerAfterTextChanged
05-19 13:49:06.502 21747 21747 V AutofillManager: notifyValueChanged(1073741870): ignoring on state UNKNOWN
05-19 13:49:06.516 21747 21747 I Quality : Skipped: false 2
05-19 13:49:06.519 21747 21779 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
05-19 13:49:08.531 21747 21747 V AutofillManager: requestHideFillUi(null): anchor = null

**Comment by iiordanov** [comment]
Hey,

Sure, the bug tracker is a great place to ask a question. I'll need some additional details to try to help you:
- What is the remote OS?
- What VNC server (or built in desktop sharing) is this?
- Are you using SSH tunneling?
- It looks as though the VNC server fails to even read the RFB server version by the stacktrace you posted above - are you sure you're connecting to the correct VNC server port?

Share any config you think is relevant and you're comfortable sharing.

**Comment by choeng1** [comment]
Yes i.m conet ok all 
En err
