### ISSUE TITLE
freeardp cannot support enter key with physical keyboard

### ISSUE THREAD

**Issue by artjourney** [iiordanov/remote-desktop-clients#372]
Freeardp cannot support `enter` key with physical keyboard, and cannot select words correctly with physical mouse. The server is windows 10.

**Comment by iiordanov** [comment]
Hello, could you please provide some additional information:

- Scaling mode used
- input mode used
- Android or Chromebook device
- type of physical keyboard and how it is connected
- type of physical mouse

Thanks!

**Comment by artjourney** [comment]
Some information is：

System: Slimbox TV 11.5
Android Version: Android TV 9
physical Keybord：RAPOO 5G wireless Device.
physical mouse: IPASON ps-m001，wire mouse.

I have used Mircosoft Remote Desktop for Android(version 8 & version 10), and real VNC client, the `enter` key works OK.

Both  aRDP and bVNC are not work with `enter` key(keycode=13),  only work with the NUMPAD_ENTER key.

**Comment by artjourney** [comment]
I know what's the problem. The normal `enter` key map to `KEYCODE_DPAD_CENTER`, which key code is 23, not 13. 

When I add keymap in `RdpKeyboardMapper.java` and rebuild the project, it works.

```
keymapAndroid[KeyEvent.KEYCODE_DPAD_CENTER ] = VK_RETURN | VK_EXT_KEY;
```

![2022-05-21_083930](https://user-images.githubusercontent.com/8003780/169627622-d0d45cd4-0c00-483f-b59d-143c8802e9e0.png)

**Comment by iiordanov** [comment]
Hi,

Is the enter key and mouse working correctly in this version?

https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.1.0/freeaRDP-v5.1.0_4-final.apk

Thanks!
