### ISSUE TITLE
Using Super, Alt-Tab, Alt-F4 in other apps...

### ISSUE THREAD

**Issue by twaik** [iiordanov/remote-desktop-clients#373]
Hi. I am very satisfied using this app.
I am developing something like X11 server for Android and I need to know how I can use hardware key intercepting in my own app.
I tried to find out how it is done in bVNC but failed. Everything I know is that after uninstalling bVNC I can use my own app with the same package name and activity `RemoteCanvasActivity` with my own `View.OnKeyListener` code intercepts all key events I need. 
Can you please tell me how you achieved this?

**Comment by iiordanov** [comment]
What Android device are you running this on? The only special sauce for intercepting Alt-Tab and Super is for Samsung devices.

See:
bVNC/src/main/java/com/iiordanov/util/SamsungDexUtils.kt

For the extra special sauce.

**Comment by twaik** [comment]
Thank you very much
