### ISSUE TITLE
bVNC scrolls too fast and requires two fingers

### ISSUE THREAD

**Issue by freebrowser1** [iiordanov/remote-desktop-clients#375]
Using bVNC viewer 5.1.0 on Android 10 works awesome, but there are two disadvantages:
* scrolling is way too fast in any input mode. 
* I have to use two fingers.

I tested it on various VNC servers and all have the same issue.

Can the scroll speed be user set to a (mostly slower) speed ?

When using 'Direct swipe / pan' one finger scrolls just the screen up and down which can be useful in some cases, but scrolling within the desktop screen requiring two fingers is used more often. 
Can there be made a user option to swap these one and two fingered operation ?

**Comment by niemeyer** [comment]
Hello there,

I'm finding the same issue with aRDP accessing Ubuntu's (22.04) xrdp: the scrolling is extremely fast on a large tablet, whether using the finger or a bluetooth mouse wheel. It's a bit of a deal breaker unfortunately, as there's no way to scroll the content in a usable fashion. Could not find any option to tune it.

**Comment by brunobernardnh** [comment]
Yes, I am also using aRDP and the scrolling is way too fast. It often jumps right away to the beginning or the end of the page. I could not find any settings that caused it.
Using a Galaxy Tab S7

**Comment by brunobernardnh** [comment]
I could not find any settings to fix it either. It makes aRDP very hard to use using touch. Microsoft RDP Client does not have this issue. Would love to get this fixed. Would make aRDP perfect. Note I paid for the pro version hoping it would have an option.
Using a Galaxy Tab S7

**Comment by brunobernardnh** [comment]
Just wondering would it be fixed by https://github.com/iiordanov/remote-desktop-clients/pull/487 ?
@iiordanov if this is the solution and wondering if it can be intergrated?

**Comment by iiordanov** [comment]
Yes, still working on this PR with the author - it will definitely get integrated, hopefully quite soon!

On the one-finger scrolling front, if you use fit-to-screen mode (i.e. no need to pan with swiping), and you are in the Direct, Swipe Pan input mode, you will get single-finger scrolling for a while now.

**Comment by iiordanov** [comment]
The latest beta v5.5.8 has the scroll adjustment option in General settings (see the wrench button).
