### ISSUE TITLE
bVNC on iOS cannot connect to UltraVNC with MSLogon configured

### ISSUE THREAD

**Issue by iiordanov** [iiordanov/remote-desktop-clients#377]

**Comment by AndrzejMilewski** [comment]
I paste log from my device. My vnc server is UltraVNC on MS Logon, new method. I buy another application https://remoterlabs.com/ Remoter Pro and application works fine.
bVNC on android also works fine.

Initializing Remote Session instance: 6
Ensuring buttons are initialized, and positioning them where they should be
Connecting VNC Session in the background...
Initializing VNC session.

VNC server supports protocol version 3.8 (viewer 3.8)

We have 2 security types to read

0) Received security type 17

1) Received security type 113

Selecting security type 113 (1/2 in the list)

Selected Security Scheme 113

WARNING! MSLogon security type has very low password encryption! Use it only with SSH tunnel or trusted network.

VeNCrypt authentication callback called


Username and password requested for authentication, initializing now

VNC connection failed: authentication rejected

FAILED_TO_INIT_CONNECTION_TO_SERVER

Done initializing VNC session

Connection failure, showing error with title VNC_CONNECTION_FAILURE_TITLE.
Scheduling disconnect
Lazy disconnecting
disconnect(sender:) called
wasDrawing(): true
Hiding keyboard.

**Comment by iiordanov** [comment]
Hi there, I released a version of bVNC with the bug fixed a while ago - could you please confirm whether you were able to connect now? Thank you!

**Comment by iiordanov** [comment]
Please let me know if this is still an issue and this bug-report needs to be reopened.
