### ISSUE TITLE
Naming convention strange for "Direct, pan mode"

### ISSUE THREAD

**Issue by hjgode** [iiordanov/remote-desktop-clients#378]
In strings.xml we see

    <string name="input_method_direct_drag_pan">Direct, Hold Pan</string>

which is never used. Instead 

    <string name="**input_mode_drag_pan_zoom_mouse**">Direct, Hold Pan</string>

is used from code. The following name usage is irritating in RemoteCanvasActivity.java:

    	    	<group android:checkableBehavior="single">
                <item android:id="@+id/itemInputTouchPanZoomMouse" android:title="@string/input_mode_touch_pan_zoom_mouse"/>
                <item android:id="@+id/itemInputDragPanZoomMouse" android:title="@string/**input_mode_drag_pan_zoom_mouse**"/>
                
                <item android:id="@+id/itemInputTouchpad" android:title="@string/input_mode_touchpad"/>
                <item android:id="@+id/itemInputSingleHanded" android:title="@string/input_mode_single_handed"/>
and

    public static final int[] inputModeIds = { R.id.itemInputTouchpad,
                                                R.id.itemInputTouchPanZoomMouse,
                                                R.id.itemInputDragPanZoomMouse, // this is InputHandlerDirectDragPan
                                                R.id.itemInputSingleHanded };

and

    public static final Map<Integer, String> inputModeMap;
    static {
        Map<Integer, String> temp = new HashMap<>();
        temp.put(R.id.itemInputTouchpad, InputHandlerTouchpad.ID);
        temp.put(R.id.itemInputDragPanZoomMouse, InputHandlerDirectDragPan.ID); // this R.id.itemInputDragPanZoomMouse !!!!!
        temp.put(R.id.itemInputTouchPanZoomMouse, InputHandlerDirectSwipePan.ID);
        temp.put(R.id.itemInputSingleHanded, InputHandlerSingleHanded.ID);
        inputModeMap = Collections.unmodifiableMap(temp);
    }

itemInputDragPanZoomMouse should be itemInputDirectPanMode

input_mode_drag_pan_zoom_mouse should be input_method_direct_drag_pan

**Comment by iiordanov** [comment]
@hjgode please check and let me know if this is still an issue after my fix.

**Comment by hjgode** [comment]
Hi

in which branch or commit hash did you change this?

**Comment by iiordanov** [comment]
Hey, sorry, it was auto-referenced above: 

https://github.com/iiordanov/remote-desktop-clients/commit/849dbf8bcbf62bdf6e56a8713e7df98c814e195c

**Comment by iiordanov** [comment]
Please let me know if this is still an issue and I'll reopen the bug-report. Thanks!
