### ISSUE TITLE
Open manager viewer 

### ISSUE THREAD

**Issue by Ofabiojvalentim** [iiordanov/remote-desktop-clients#380]
When we choose to launch app control through open manager , screen gets scrambled

**Comment by iiordanov** [comment]
Hi Fabio, could you please confirm - is this Dell Open Manage that you're referring to? Thank you!

**Comment by iiordanov** [comment]
If so, could you please also add details such as which Dell Server model you're trying to connect to?

**Comment by Ofabiojvalentim** [comment]
Yes , OpenManager Mobile.

Em qua., 20 de jul. de 2022 21:02, iiordanov ***@***.***>
escreveu:

**Comment by Ofabiojvalentim** [comment]
Dell XL R620

Em qua., 20 de jul. de 2022 21:03, iiordanov ***@***.***>
escreveu:

**Comment by iiordanov** [comment]
Thanks!

**Comment by iiordanov** [comment]
I could get no help from Dell open-manage support regarding this issue. Closing this for now.
