### ISSUE TITLE
bVNC userland and landscape mode enhancement request

### ISSUE THREAD

**Issue by improvisor40** [iiordanov/remote-desktop-clients#383]
First of all I just want to say, great app.
It's the best of its kind.
But I have a feature request, if you don't mind.
I want an option to set landscape mode by default, in userland, as it automatically launches the app, and I can't seem to find its port number or whatsoever, I don't even know what to write in the search box, maybe,  port number or ip or userid, I don't know but I think an option to set it as default in all session will be nice, after all no one wants a portrait view of their PC in an android phone, except tablets.
Thanks

**Comment by iiordanov** [comment]
Hi there, is the remote desktop's resolution in portrait mode?

What happens if you rotate your device to landscape before launching userland?

**Comment by iiordanov** [comment]
Revisiting this issue to see what needs doing.

For force landscape mode, select the Default Settings wrench on the main screen and turn on Force Landscape Orientation.

For Default input mode, hit the menu and it's a submenu called Default Input Mode (I should look into moving it to the default settings).

I guess this leaves default scaling, but the app starts with the screen fit to the screen of the device, and you can zoom in/out from there if you need. Is this really necessary?

**Comment by improvisor40** [comment]
Yeah, it's really necessary!.

**Comment by improvisor40** [comment]
I've closed, thanks for the info!
Sorry I'm kinda busy.
