### ISSUE TITLE
Opaque mouse event not work

### ISSUE THREAD

**Issue by lzycn987** [iiordanov/remote-desktop-clients#385]
Use the latest version of Opaque, running in the emulator Tablet.
Android Studio->tools->AVD manager->Create Virtual Device->Tablet (13.5 Freeform, Android11.0,x86_64)
Using the Proxmox protocol, the server OS is win10.
When Opaque is connected to the server, the left mouse button is normal, but the right mouse button and scroll wheel events do not respond.

When using the same Opaque APK on a physical mobile phone, when using a Bluetooth mouse, the left and right buttons and scroll wheel of the mouse can respond normally on the server side.

**Comment by iiordanov** [comment]
So the mouse does not work correctly when you run Opaque in an emulator, but works correctly with physical devices?

**Comment by lzycn987** [comment]
> 

Opaque mouse works correctly with mobile phone.
But on tablet devices (arm 64 system), the same apk, the left mouse button does not work, the right mouse button and scroll wheel events are normal.
Therefore, opaque's mouse events behave differently in mobile phones, emulators, and tablets. Only the left and right mouse and scroll wheel events on the mobile phone can be received and worked normally on the server side.

**Comment by lzycn987** [comment]
Opaque mouse works correctly with mobile phone.

But on tablet devices (arm 64 system), the same apk, the left mouse button does not work, the right mouse button and scroll wheel events are normal.
Therefore, opaque's mouse events behave differently in mobile phones, emulators, and tablets. Only the left and right mouse and scroll wheel events on the mobile phone can be received and worked normally on the server side.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iiordanov/remote-desktop-clients"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iiordanov/remote-desktop-clients] Opaque mouse event not work (Issue #385)





 
So the mouse does not work correctly when you run Opaque in an emulator, but works correctly with physical devices?

**Comment by iiordanov** [comment]
Hi, I borrowed a tablet with USB host mode and could not reproduce the issue on it.

The reason this happens on the emulator, on the other hand is that mouse events are sent as touch events to Opaque when running in an emulator. As a result, there is no "scroll button event" or "right click event" at all.
