### ISSUE TITLE
IPv6 Problem

### ISSUE THREAD

**Issue by emeraldservices** [iiordanov/remote-desktop-clients#386]
IPv6 how can I connect? show me this error 
could not connect to RDP server! please ensure RDP server setting is correct the server is turned on RDP is enabled and that the server is on the same network as this device.

**Comment by iiordanov** [comment]
How did you enter the ipv6 address?

**Comment by emeraldservices** [comment]
Connection type : RDP
IP:  2001:XXX:XXXX:XXX:5400:XXXX:XXX:XXe0
RDP UserNAme:  Admin
RDP Password:    xxxxxxxx

Save

**Comment by iiordanov** [comment]
Hello, I read through the FreeRDP library source code, and it looks like they only treat the string as ipv6 if it's enclosed in square brackets. Write the address as:

[2001:XXX:XXXX:XXX:5400:XXXX:XXX:XXe0]

I'll look at whether I can remove this limitation by modifying the FreeRDP library, but it'll only go away if my change is accepted. I'll update this bug-report.

**Comment by iiordanov** [comment]
OK, the latest version, build 115109 in Beta has a fix for the above. You can leave the brackets out in that version.
