### ISSUE TITLE
Dragging stop mouse on touchpad mode

### ISSUE THREAD

**Issue by Ghplayer2000** [iiordanov/remote-desktop-clients#388]
When i try to drag in touchpad mode, the mouse cannot be moved until i stop dragging.

**Comment by Ghplayer2000** [comment]
Version 5.1.0_115108 (Free Version)

**Comment by remcolam** [comment]
I will give a +1 on this. I have the same issue, both on tablet (android 12) and phone (android 13 (pixel 5)). Same version on both (5.1.0_115108)

**Comment by iiordanov** [comment]
The issue is fixed in v5.1.1. Thanks for reporting!
