### ISSUE TITLE
aSpice - Touchpad simulation shows no mouse cursor

### ISSUE THREAD

**Issue by birdra73** [iiordanov/remote-desktop-clients#393]
Touchpad simulation shows no mouse cursor. This is can be resolved by manually selecting the mouse cursor - suggesting the auto feature is not working?

**Comment by iiordanov** [comment]
Fixed in https://github.com/iiordanov/remote-desktop-clients/commit/e8eacba060abbaa4b9a7ef72851dce350be49a48, should be out in Beta shortly.
