### ISSUE TITLE
IPad app crashes when opening a .vv file

### ISSUE THREAD

**Issue by lalcaraz** [iiordanov/remote-desktop-clients#395]
I exported my SPICE file from proxmox and when opening it from Files, the app crashes.
I cannot get an error or crash log.

**Comment by iiordanov** [comment]
Hi @lalcaraz, I tried and cannot reproduce a crash when opening console.vv directly from Safari (the dropdown for downloads) and from Files by hitting the magnifying glass.

1) Could you please make sure that you have SPICE selected as the console type and not VNC? The app does not currently support VNC sessions and it makes sense to actually support that or at least report to the user that they are starting a VNC session.

2) What version of Proxmox are you running, so I can get closer to your environment?

3) What is the remote OS?

4) What is the remote resolution?

5) Is it a container or a VM you're establishing a connection to?

Anything else special in your setup that you can think of?

**Comment by iiordanov** [comment]
Hey there, since I have not heard back from you, I am going to assume that the issue was that you were trying to open a VNC session with the app, please let me know if that's not correct!

**Comment by lalcaraz** [comment]
I am sorry, my friend. Forgot to come back and report my findings.

After doing some trial and error decided to uninstall the app, restart the iPad, reinstalled and it worked. It just worked. Not sure what was the issue but it works now.
