### ISSUE TITLE
[aRDP] add scale support for windows

### ISSUE THREAD

**Issue by XQDD** [iiordanov/remote-desktop-clients#396]
![4fac2d8e23060e86c317d17fbebbfda](https://user-images.githubusercontent.com/20871761/203332993-02bb0f0d-65d7-4c75-855d-b414cacccd97.jpg)

**Comment by iiordanov** [comment]
@XQDD Please check the Advanced Settings while creating a new connection or editing an existing one. There is a way to specify a fixed resolution there. Please let me know if that's not what you were requesting and I'll reopen the issue.
