### ISSUE TITLE
usbredirhost.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by max32002** [iiordanov/remote-desktop-clients#40]
Unable to build v3.7.6 version, lost file: usbredirhost.h
======================================
[armeabi] Compile arm    : spice <= spice-audio.c
[armeabi] Compile arm    : spice <= spice-gstaudio.c
[armeabi] Compile arm    : spice <= channel-usbredir.c
jni/src/gtk/channel-usbredir.c:26:26: fatal error: usbredirhost.h: No such file or directory
compilation terminated.
make: *** [obj/local/armeabi/objs/spice/gtk/channel-usbredir.o] Error 1
make: *** Waiting for unfinished jobs....
root@max-VirtualBox:/home/max/git/remote-desktop-clients/eclipse_projects/bVNC# 

======================================
eclipse_projects/Opaque/jni/src/gtk/channel-usbredir.c 

24	#ifdef USE_USBREDIR
25	#include <glib/gi18n.h>
26	#include <usbredirhost.h>
27	#if USE_POLKIT

======================================
eclipse_projects/Opaque/jni/src/gtk/usb-device-manager.c 

42	#include "channel-usbredir-priv.h"
43	#include "usbredirhost.h"
44	#include "usbutil.h"
45	#endif

======================================
eclipse_projects/Opaque/jni/src/android/android-config.h 

156	/* Define if supporting usbredir proxying */
157	#define USE_USBREDIR 1
158	
159	/* Version number of package */
160	#define VERSION "0.22"

**Comment by iiordanov** [comment]
Sorry, I had these .h files installed in /opt/gstreamer. I've now added them to master and pushed them up.
