### ISSUE TITLE
bVNC 

### ISSUE THREAD

**Issue by ms8sm** [iiordanov/remote-desktop-clients#401]
Unable to create desktop gadget.

**Comment by iiordanov** [comment]
I tested it out on my Android 13 device, and I can make widgets without issue. Long-tap on the screen, select Widgets, find the app, and long-tap and drag the icon to the desktop. If it doesn't work, please update this bug report with detailed instructions what doesn't work and how, what device, what OS, versions for everything so i can try to reproduce the issue.

**Comment by ms8sm** [comment]
![Screenshot_2022-12-18-07-49-11-387_com android settings](https://user-images.githubusercontent.com/120615038/208270531-8b0a498b-eec9-403b-81f8-b7eafd287513.jpg)
![Screenshot_2022-12-18-07-48-52-820_com android settings](https://user-images.githubusercontent.com/120615038/208270536-c1d33ebf-9a53-4ede-97a8-b95fd328b332.jpg)

https://user-images.githubusercontent.com/120615038/208270540-2d2ae3d3-afcc-4e4b-9ce5-0b6d8dba2881.mp4

![Screenshot_2022-12-18-07-46-33-485_com android settings](https://user-images.githubusercontent.com/120615038/208270544-28a5c5d4-dfa9-4333-a8cb-8719f36c2cab.jpg)

**Comment by ms8sm** [comment]
![Uploading Screenshot_2022-12-18-08-00-24-902_com.miui.securitycenter.jpg…]()

**Comment by ms8sm** [comment]
![Screenshot_2022-12-18-08-00-24-902_com miui securitycenter](https://user-images.githubusercontent.com/120615038/208270681-b1d15149-6a78-41c1-b09e-93b1fea6bcca.jpg)

**Comment by iiordanov** [comment]
The video is unplayable, and the screenshots do not tell me anything!

**Comment by ms8sm** [comment]
This is the screen when I was working.[](https://drive.google.com/file/d/10ZNlb9pKo5khwusl6LmIzQX9H29251RG/view?usp=drivesdk) 

https://drive.google.com/file/d/10ZNlb9pKo5khwusl6LmIzQX9H29251RG/view?usp=drivesdk

**Comment by ms8sm** [comment]
![Screenshot_2022-12-19-08-21-26-987_com miui home](https://user-images.githubusercontent.com/120615038/208327286-f1dedcdb-cc81-41f2-8bfb-d246a96acb55.jpg)
![Screenshot_2022-12-19-08-21-30-108_com iiordanov freebVNC](https://user-images.githubusercontent.com/120615038/208327315-193d8eff-a2c9-44a6-9008-a574cf2a81aa.jpg)

**Comment by iiordanov** [comment]
Yes, you need to select one of the two connections that are shown in the
second screen!

**Comment by ms8sm** [comment]
I have a choice, but he will not produce desktop gadgets,

He will not appear in the second screen.
[](https://drive.google.com/file/d/10eaNFG15JDoTCnvZNjvyCTROZZw3HlT4/view?usp=drivesdk)

**Comment by iiordanov** [comment]
Could you make the problem happen, then immediately start the app from its
normal icon and use the "Copy Logcat" option from the menu to try to get a
log of what happened and send it to me?

Thanks!

**Comment by ms8sm** [comment]
--------- beginning of system
12-19 08:21:28.196 12595 12595 I ForceDarkHelperStubImpl: initialize for com.iiordanov.freebVNC , ForceDarkOrigin
12-19 10:25:22.926 25487 25487 I ForceDarkHelperStubImpl: initialize for com.iiordanov.freebVNC , ForceDarkOrigin
12-19 12:15:43.733 21101 21101 I ForceDarkHelperStubImpl: initialize for com.iiordanov.freebVNC , ForceDarkOrigin
--------- beginning of main
12-19 12:17:49.168 21101 21101 D ConnectionGridActivity: onMenuOpened
12-19 12:17:49.178 21101 21101 D ConnectionGridActivity: onMenuOpened
12-19 12:17:49.178 21101 21101 D ConnectionGridActivity: Default Input Mode Item: TOUCH_ZOOM_MODE
12-19 12:17:49.178 21101 21101 D ConnectionGridActivity: Input Mode Item: TOUCHPAD_MODE
12-19 12:17:49.178 21101 21101 D ConnectionGridActivity: Input Mode Item: TOUCH_ZOOM_MODE
12-19 12:17:49.178 21101 21101 D ConnectionGridActivity: Input Mode Item: TOUCH_ZOOM_MODE_DRAG_PAN
12-19 12:17:49.178 21101 21101 D ConnectionGridActivity: Input Mode Item: SINGLE_HANDED_MODE
12-19 12:17:49.285 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus false
12-19 12:17:53.915 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus true
12-19 12:17:55.001 21101 21101 D ConnectionGridActivity: Showing main screen help.
12-19 12:17:55.007 21101 21101 D IS_CTS_MODE: false
12-19 12:17:55.007 21101 21101 D MULTI_WINDOW_SWITCH_ENABLED: false
12-19 12:17:55.100 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus false
12-19 12:17:55.113 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus true
12-19 12:17:56.673 21101 21115 I OpenGLRenderer: Davey! duration=9223285186585ms; Flags=0, FrameTimelineVsyncId=5458491, IntendedVsync=86850269243189, Vsync=86850269243189, InputEventId=0, HandleInputStart=86850275531709, AnimationStart=86850275540980, PerformTraversalsStart=86850275543220, DrawStart=86850276163792, FrameDeadline=86850285909855, FrameInterval=86850275452386, FrameStartTime=16666666, SyncQueued=86850277377282, SyncStart=86850277827803, IssueDrawCommandsStart=86850277924157, SwapBuffers=86850278996292, FrameCompleted=9223372036854775807, DequeueBufferDuration=46197, QueueBufferDuration=2697396, GpuCompleted=9223372036854775807, SwapBuffersCompleted=86850282611605, DisplayPresentTime=-4294966639, 
12-19 12:17:58.180 21101 21121 D OpenGLRenderer: endAllActiveAnimators on 0xb400007d8127ab00 (RippleDrawable) with handle 0xb400007d80e4cc20
12-19 12:17:58.228 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus true
12-19 12:17:58.864 21101 21101 D ConnectionGridActivity: onMenuOpened
12-19 12:17:58.865 21101 21101 D ConnectionGridActivity: onMenuOpened
12-19 12:17:58.865 21101 21101 D ConnectionGridActivity: Default Input Mode Item: TOUCH_ZOOM_MODE
12-19 12:17:58.865 21101 21101 D ConnectionGridActivity: Input Mode Item: TOUCHPAD_MODE
12-19 12:17:58.865 21101 21101 D ConnectionGridActivity: Input Mode Item: TOUCH_ZOOM_MODE
12-19 12:17:58.865 21101 21101 D ConnectionGridActivity: Input Mode Item: TOUCH_ZOOM_MODE_DRAG_PAN
12-19 12:17:58.865 21101 21101 D ConnectionGridActivity: Input Mode Item: SINGLE_HANDED_MODE
12-19 12:17:58.970 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus false
12-19 12:18:06.544 21101 21101 I ConnectionGridActivity: onPause
12-19 12:18:26.631 21101 22374 D AppScoutStateMachine: 21101-ScoutStateMachinecreated
12-19 12:18:26.644 21101 21101 D IS_CTS_MODE: false
12-19 12:18:26.644 21101 21101 D MULTI_WINDOW_SWITCH_ENABLED: false
12-19 12:18:26.646 21101 21101 D DecorView[]: getWindowModeFromSystem  windowmode is 1
12-19 12:18:26.654 21101 21101 D IconCustomizer: Generate customized icon for sym_def_app_icon.png
12-19 12:18:26.709 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus true
12-19 12:18:28.598 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus false
12-19 12:18:28.950 21101 21121 D OpenGLRenderer: endAllActiveAnimators on 0xb400007e03740f00 (ListView) with handle 0xb400007d81538840
12-19 12:18:31.266 21101 21116 D AppScoutStateMachine: 21101-ScoutStateMachinecreated
12-19 12:18:31.294 21101 21101 D Utils   : Version of com.iiordanov.freebVNC is v5.1.0_115111
12-19 12:18:31.294 21101 21101 I ConnectionGridActivity: onResume of version v5.1.0_115111
12-19 12:18:31.298 21101 21101 I ConnectionGridActivity: onResumeFragments called
12-19 12:18:31.307 21101 21101 D LabeledImageApapter: Now setting label at position: 0 to: DellG5
12-19 12:18:31.307 21101 21101 D LabeledImageApapter: 122.117.32.229:5788
12-19 12:18:31.310 21101 21101 E ThemeUtils: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
12-19 12:18:31.311 21101 21101 D LabeledImageApapter: Setting screenshot from file /data/user/0/com.iiordanov.freebVNC/files/aceb3958-2aee-41b7-b4dc-d7ac9b28c9ef.png
12-19 12:18:31.323 21101 21101 D LabeledImageApapter: Now setting label at position: 0 to: DellG5
12-19 12:18:31.323 21101 21101 D LabeledImageApapter: 122.117.32.229:5788
12-19 12:18:31.323 21101 21101 D LabeledImageApapter: Setting screenshot from file /data/user/0/com.iiordanov.freebVNC/files/aceb3958-2aee-41b7-b4dc-d7ac9b28c9ef.png
12-19 12:18:31.331 21101 21101 D LabeledImageApapter: Now setting label at position: 1 to: X230
12-19 12:18:31.331 21101 21101 D LabeledImageApapter: 122.117.32.229:5989
12-19 12:18:31.331 21101 21101 E ThemeUtils: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
12-19 12:18:31.332 21101 21101 D LabeledImageApapter: Setting screenshot from file /data/user/0/com.iiordanov.freebVNC/files/52f869f4-e505-405d-b89b-ffad9d823329.png
12-19 12:18:31.360 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus true
12-19 12:18:32.776 21101 21101 D ConnectionGridActivity: onMenuOpened
12-19 12:18:32.782 21101 21101 D ConnectionGridActivity: onMenuOpened
12-19 12:18:32.782 21101 21101 D ConnectionGridActivity: Default Input Mode Item: TOUCH_ZOOM_MODE
12-19 12:18:32.782 21101 21101 D ConnectionGridActivity: Input Mode Item: TOUCHPAD_MODE
12-19 12:18:32.782 21101 21101 D ConnectionGridActivity: Input Mode Item: TOUCH_ZOOM_MODE
12-19 12:18:32.783 21101 21101 D ConnectionGridActivity: Input Mode Item: TOUCH_ZOOM_MODE_DRAG_PAN
12-19 12:18:32.783 21101 21101 D ConnectionGridActivity: Input Mode Item: SINGLE_HANDED_MODE
12-19 12:18:32.784 21101 21116 I OpenGLRenderer: Davey! duration=9223285150469ms; Flags=0, FrameTimelineVsyncId=5461495, IntendedVsync=86886383893221, Vsync=86886383893221, InputEventId=481440010, HandleInputStart=86886388346331, AnimationStart=86886388356747, PerformTraversalsStart=86886388358779, DrawStart=86886388931956, FrameDeadline=86886400559887, FrameInterval=86886388273727, FrameStartTime=16666666, SyncQueued=86886392696487, SyncStart=86886393961331, IssueDrawCommandsStart=86886394211956, SwapBuffers=86886396534664, FrameCompleted=9223372036854775807, DequeueBufferDuration=51771, QueueBufferDuration=994271, GpuCompleted=9223372036854775807, SwapBuffersCompleted=86886398324300, DisplayPresentTime=0, 
12-19 12:18:32.882 21101 21101 D DecorView[]: onWindowFocusChanged hasWindowFocus false

**Comment by iiordanov** [comment]
What OS do you use on your computer?

**Comment by ms8sm** [comment]
Windows 10

**Comment by iiordanov** [comment]
https://www.hexnode.com/mobile-device-management/help/obtain-android-device-logs-using-windows-and-mac/#using-windows

**Comment by ms8sm** [comment]
Did you find the problem?  Is there a way to solve?

**Comment by iiordanov** [comment]
I looked very closely at your log and there isn't a single line of stacktrace related to com.iiordanov.freebVNC. However, there are quite a number of entries about a widgetProvider process being killed by the system. Could you try installing another Home Launcher like Pixel Rootless Launcher, and seeing if you can make widgets with that launcher? I suspect something in your launcher is not working quite right for creating widgets with bVNC, but I can't see what causes it to attempt a workaround.

**Comment by iiordanov** [comment]
Please let me know if this continues to be an issue with another launcher like the Pixel Rootless Launcher, and I'll reopen the bug-report and keep trying to reproduce the issue.

**Comment by ms8sm** [comment]
I tested this desktop software and there is no problem, but
The BVNC app still has problems on the original desktop of Xiaomi miui, and the others can be used as gadgets.

**Comment by iiordanov** [comment]
Thanks for confirming this is an issue specific with Xiaomi miui. Hopefully
I can reproduce this with the Xiaomi launcher installed on my device.

**Comment by ms8sm** [comment]
Hi,
Now even your main program desktop shortcut is gone (can't find it),

 I have to go to Google Play to open it.  

None of the other apps happened.

**Comment by iiordanov** [comment]
Well, apps themselves definitely don't have control over how the launcher
shows them.

Try exporting the app settings, uninstall/reinstalling and importing the
settings again.

**Comment by ms8sm** [comment]
I tested it, but it didn't work.
