### ISSUE TITLE
export connections from free to pro

### ISSUE THREAD

**Issue by alexbodn** [iiordanov/remote-desktop-clients#404]
Hello Iordan,
It's a pleasure for me to finally give you back after trying ardp and bvnc.
However as my connection in the free version is quite complex, with saved ssh keys and passwords (to access xrdp), I'd like to transfer/ export it to my new pro installation.
Well, this represents me a little spoiled, but consider the secret fields are hidden with *****.
Please instruct. Thanks in advance,
alex

**Comment by iiordanov** [comment]
Ssh passwords and passphrase are not exported, but there does exist a way
to export everything else via the main menu when you launch the app - just
hit Import/Export there and follow the prompts.

Cheers!
Iordan

**Comment by alexbodn** [comment]
thank you very much.
i have overlooked this menu entry.
I wish you a Merry Christmas and Happy New Year.

alex

**Comment by iiordanov** [comment]
Thank you, you as well!
