### ISSUE TITLE
[macOS Ventura / aSpice Pro / Proxmox] Window goes blank after resizing, until screen outputs

### ISSUE THREAD

**Issue by b-** [iiordanov/remote-desktop-clients#421]
Hi there,

When I resize the window at all on my Mac, it doesn't "live resize," but rather the entire window contents disappear. It seems that the video feed refreshing fixes the output. See the attached screen capture:

https://user-images.githubusercontent.com/284789/216751842-aaa704bf-4402-436b-a007-f59d02707e43.mp4

**Comment by iiordanov** [comment]
This behaviour is expected, but I can see how it is a usability issue. I'll look into whether it can be improved. Thanks!

**Comment by iiordanov** [comment]
Fixed in https://gitlab.com/iiordanov/remote-desktop-clients-ios/-/commit/a0641b001014631c12e4c8c7e9e0da355f4d4735.

Please get in touch by email with support _at_ morpheusly _dot_ com if you'd like to beta test this and the other changes.
