### ISSUE TITLE
[macOS Ventura / aSpice Pro] a ton of empty space exists on the settings screens

### ISSUE THREAD

**Issue by b-** [iiordanov/remote-desktop-clients#422]
Hi,

I'm not sure if this is a layout bug or if there is an entire page of settings that aren't showing, but this is what I see on both the default settings and any individual connection's settings:

https://user-images.githubusercontent.com/284789/216752600-5267e378-6903-42be-9af9-71456b80a293.mp4

**Comment by iiordanov** [comment]
There are no settings missing, this is what the page actually looks like. I'll look into why the space is there but rest assured the UI is actually functional as it is.

**Comment by iiordanov** [comment]
Fixed in https://gitlab.com/iiordanov/remote-desktop-clients-ios/-/commit/26f75897916bc84dc763a1a6cd1eada4830cf636
