### ISSUE TITLE
MacroDroid Log

### ISSUE THREAD

**Issue by Kerazb88** [iiordanov/remote-desktop-clients#449]
Here is the MacroDroid log file.![MacroDroidLog.txt](https://github.com/iiordanov/remote-desktop-clients/files/11244867/MacroDroidLog.txt)

**Comment by iiordanov** [comment]
What is the issue you are reporting @Kerazb88 ? What is broken?

**Comment by iiordanov** [comment]
Hey, not sure why you posted this log here. Closing issue unless you think there is something to look at.
