### ISSUE TITLE
cannot run my aSPICE.apk

### ISSUE THREAD

**Issue by a1154043439** [iiordanov/remote-desktop-clients#45]
when I run bVNC ,console output :
[2015-04-01 12:28:40 - ZoomerWithKeys] Could not find ZoomerWithKeys.apk!
[2015-04-01 12:28:40 - PubkeyGenerator] Could not find PubkeyGenerator.apk!
[2015-04-01 12:28:40 - FreeRDPCore] Could not find FreeRDPCore.apk!
I notice there is someone else has the same issue，and I go through my eclipse according his advice,but not resolve it 
(I have sqlitegen_0.1.19 in my eclipse ,I have checked SQlitgen annotation processing in bVNC　project, and select the "Android private libraries" entry in  Project Properties,also add the ZoomerWithKeys, PubkeyGenerator, and FreeRDPCore projects as Library References to bVNC)
if anyone can give me some advice to resolve it ,I shall be very grateful

**Comment by a1154043439** [comment]
this is my LogCat:
com.iiordanov.bVNC AndroidRuntime   FATAL EXCEPTION:main
com.iiordanov.bVNC AndroidRuntime   process:com.iiordanov.bVNC,PID:1943
com.iiordanov.bVNC AndroidRuntime
java.lang.UnsatisifiedLinkError:dalvik.system.PathClassLoader[DexPathList[[zip file:data/app/com.iiordanov.bVNC-1/base.apk"],nativeLibraryDirecories=[/vendor/lib,/system/lib]]]]couldn't find"libstlport_shared.so"

**Comment by iiordanov** [comment]
Sounds like ndk-build destroyed the libraries that are distributed with the repository. The libraries should look like this:

$ ls -1  ./eclipse_projects/bVNC/libs/armeabi*
./eclipse_projects/bVNC/libs/armeabi:
libdatabase_sqlcipher.so
libgstreamer_android.so
libspice.so
libsqlcipher_android.so
libstlport_shared.so

./eclipse_projects/bVNC/libs/armeabi-v7a:
libdatabase_sqlcipher.so
libgstreamer_android.so
libspice.so
libsqlcipher_android.so
libstlport_shared.so

$ ls -1  ./eclipse_projects/bVNC/libs/x86/
libdatabase_sqlcipher.so
libsqlcipher_android.so
libstlport_shared.so

The two files: libgstreamer_android.so and libspice.so are built with ndk-build, but the rest of the files should be available in the repo. Use "git checkout" to check all those files back out into the above armeabi, armeabi-v7a and x86 directories if they've gone missing. You can easily see what files went missing with "git status".
