### ISSUE TITLE
building "I-a With Prebuilt Libraries"

### ISSUE THREAD

**Issue by paweljasinski** [iiordanov/remote-desktop-clients#458]
I am trying to use the "I-a With Prebuilt Libraries" path from the readme.
When trying to build it using newest version of  Android Studio there are errors.

First problem generates different errors, in one of the tests, I got:
```
Cause: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x4c83b62e) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x4c83b62e
```
The internet suggested replacing gradle jdk version from default jet brains embedded 17 to 11.
It fixed the problem.

Second problem:
```
No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
```
The internet suggested to update version of the gradle plugin from 3.5.4 to 4.0.x. This also matched the android studio suggestion when opening the project and fixed it.

**Comment by iiordanov** [comment]
@paweljasinski Thanks for your report. I upgraded to the latest Android Studio and updated the project to work with it in 06db9ae72d3dce28d1df0c0fdfc80aa102ff5eb1. Please let me know if it still causes issues with the above.

**Comment by paweljasinski** [comment]
Works like a charm, thanks.
I checked debug and release builds on command line and in android studio.
However, I had to increase memory limit and max perm size, otherwise I was getting out of memory error.
Probably this is just my environment (more cores?).
```
diff --git a/gradle.properties b/gradle.properties
index 774071ee..41428dee 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -1,4 +1,4 @@
-org.gradle.jvmargs=-Xmx2g -XX:MaxPermSize=512m -XX:-HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
+org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=1g -XX:-HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
 #org.gradle.daemon=false
 SDK_VERSION=21
 CUSTOM_VNC_APP_NAME=Custom VNC Viewer
```
