### ISSUE TITLE
aRDP Simulated touchpad drift

### ISSUE THREAD

**Issue by xpordoubler** [iiordanov/remote-desktop-clients#470]
When using aRDP on Android to connect to a Windows 10 host, there is a leftwards drift while inputting any mouse movements using the Simulated Touchpad input mode.

For example, when swiping straight up and down repeatedly, the cursor will move up and down with your swipe inputs, but also move left while moving up or down, eventually reaching the edge of the screen. When attempting to move the cursor right at the slowest possible rate the leftward drift causes the movement to cancel out and the cursor remains stationary while you swipe right.

The drift appears to be moving the cursor by a set amount of pixels each input, as when setting a higher resolution for the rdp connection the cursor approaches the left side of the screen at a slower rate than than on a very low resolution, thus making the issue less noticable.

**Comment by iiordanov** [comment]
Does this release help? https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.1.2/freeaRDP-v5.1.3_0-final.apk

**Comment by iiordanov** [comment]
@xpordoubler :point_up:

**Comment by xpordoubler** [comment]
Yes it does, thank you!

**Comment by iiordanov** [comment]
Thanks! I've published v5.1.3 to beta. When you get the upgrade, could you please let me know if the beta version also works fine? Thanks!!

**Comment by iiordanov** [comment]
@xpordoubler

**Comment by xpordoubler** [comment]
Sorry, I didn't get the update until recently. Yes, the issue does appear to be fixed in 5.1.3 for me as well.
