### ISSUE TITLE
bought and Installed aSpice and it keeps crashing. Macbook Air M1. Rosetta 2 is installed

### ISSUE THREAD

**Issue by Luda83** [iiordanov/remote-desktop-clients#482]
I bought aSpice last night and it would crash every time i tried to open it. I rebooted and it mostly open without crashing. Today its back to crashing every time i try to open it. I removed and reinstalled it, still crashing. I saw in another post and verified i have Rosetta 2 installed. I am on a Macbook Air M1.

**Comment by iiordanov** [comment]
Hi Louis,

This is the first such case I've seen. Is there a crash log you can collect
and send my way?

Have you tried uninstalling and reinstalling in case it is a bad
installation?

Also, would you like to try the beta?

Thanks!
Iordan

**Comment by Luda83** [comment]
Someone on May 18 had the sames issue as me with a M1 Pro. Below is their post. I replied to your email with my crash log.

https://groups.google.com/g/bvnc-ardp-aspice-opaque-remote-desktop-clients/c/P-taYPd599g****

**Comment by iiordanov** [comment]
Fixed by https://gitlab.com/iiordanov/remote-desktop-clients-ios/-/commit/dbbdaec472ac48b3ec1f0b8d5c9b13efcab79dca
