### ISSUE TITLE
Whether hard decoding is supported

### ISSUE THREAD

**Issue by l617447706** [iiordanov/remote-desktop-clients#483]
Whether hard decoding is supported

**Comment by iiordanov** [comment]
Which app is your question about?

**Comment by l617447706** [comment]
> Which app is your question about?

At present, all apps seem to be loaded with pictures, so the loading speed will be slower

**Comment by iiordanov** [comment]
Neither bVNC, nor aRDP or aSPICE support hardware decoding. Which of those were you asking about?
