### ISSUE TITLE
opaque not working after upgrade proxmox 8.0

### ISSUE THREAD

**Issue by teledong** [iiordanov/remote-desktop-clients#488]
when i type wrong password at opaque,
`Sep 05 23:18:58 proxmox pvedaemon[983]: authentication failure; rhost=::ffff:192.168.00.000(hide ip) user=root@pam msg=Authentication failure`

but when i type correct password at opaque...
`Sep 05 23:22:26 proxmox pvedaemon[985]: authentication failure; rhost=::ffff:192.168.00.000(hide ip) user=root@pam msg=no such challenge`

same result: Authenticaion faulure. Retype Credentials...

**Comment by iiordanov** [comment]
Fixed in 5d6ed185590a6135dd4da6f99610c3b28f59efd4
