### ISSUE TITLE
bVNC: Display issue with Ubuntu 22.04 Vino VNC Server

### ISSUE THREAD

**Issue by nkotixwolf** [iiordanov/remote-desktop-clients#493]
Currently tracking an issue with the default Vino VNC Server on Ubuntu 22.04:

1) Create a VNC connection leaving under Advanced Options "Remote Desktop Size (wxh), Extended Desktop Size Support" set to "disabled" as shown in the screenshot
2) Start connection and it will render a fraction of the actual display

Temporary workaround:
1) Under Advanced Options "Remote Desktop Size (wxh), Extended Desktop Size Support" set to "automatic" as shown in the screenshot
2) Start connection and you will get the full display

Issue:
![Issue-1](https://github.com/iiordanov/remote-desktop-clients/assets/65995863/9971fadb-e4d3-4836-bfc9-242c9820afed)
![Issue-2](https://github.com/iiordanov/remote-desktop-clients/assets/65995863/456a6e20-26d1-4049-900a-5fc92aeac1d1)

WorkAround:
![WorkAround-1](https://github.com/iiordanov/remote-desktop-clients/assets/65995863/1d47db72-a3b0-4b82-a8dd-b51b939780e2)
![WorkAround-2](https://github.com/iiordanov/remote-desktop-clients/assets/65995863/c8279500-601b-4fd0-8b6a-a4460a76d80d)

**Comment by iiordanov** [comment]
Fixed in https://github.com/iiordanov/remote-desktop-clients/commit/b7e89fdb9ac3f7f0226c2658cb5bd91a054ecdc8, please let me know if there is still an issue.
