### ISSUE TITLE
Add an "Update Host Key" option

### ISSUE THREAD

**Issue by JimHeedles** [iiordanov/remote-desktop-clients#496]
When a host key changes, as happens when flashing new router firmware, you currently have to delete and recreate any connection to that host.

Providing an option (ala PuTTY) to cancel, accept once, or update host key would avoid having to recreate multiple connections whenever there are updates that change host keys.

**Comment by iiordanov** [comment]
Fixed in https://github.com/iiordanov/remote-desktop-clients/commit/1232fe85274c55fddc1869a3433c977334996511 and rolled out into beta in v5.1.3_3
