### ISSUE TITLE
Opaque:If the keyboard and mouse are used at the same time, the right mouse click cannot be used

### ISSUE THREAD

**Issue by l617447706** [iiordanov/remote-desktop-clients#506]
If the keyboard and mouse are used at the same time, the right click of the mouse cannot be used. After restarting the device, only the mouse can be connected to the device.

**Comment by iiordanov** [comment]
Hey, are you passing a USB mouse and USB keyboard through to the remote VM
over the SPICE protocol?

Why not leave them connected to your mobile device and select an
appropriate keyboard layout in settings? Maybe your layout is not supported?

**Comment by iiordanov** [comment]
I assume my comments helped since I didn't hear back. Please comment to reopen with a response.
