### ISSUE TITLE
Import SSH passwords from XML / not only export

### ISSUE THREAD

**Issue by tds4u** [iiordanov/remote-desktop-clients#51]
Hello,
I exported connections for VNC over SSH as XML. Than I edited some entries and changed SSH password which was clear text. After importing all SSH passwords are empty but it should use the ones from the imported XML (like it was in export).
With many connections editing is much easier in an external editor as for each item in bVNC.

**Comment by iiordanov** [comment]
Hey,

I've created a support group / forum for bVNC, aRDP, aSPICE, and Opaque, my
remote desktop clients. Please add it to your favourites (click the star
under the title) and join by clicking the "Join group to post" button if
you would like to participate.

Cheers!
iordan

On Mon, Jul 6, 2015 at 6:49 AM, M. Martin <notifications@github.com> wrote:

> Hello,
> I exported connections for VNC over SSH as XML. Than I edited some entries
> and changed SSH password which was clear text. After importing all SSH
> passwords are empty but it should use the ones from the imported XML (like
> it was in export).
> With many connections editing is much easier in an external editor as for
> each item in bVNC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iiordanov/remote-desktop-clients/issues/51>.
>



-- 
The conscious mind has only one thread of execution.

**Comment by iiordanov** [comment]
Hey,

I've created a support group / forum for bVNC, aRDP, aSPICE, and
Opaque, my remote desktop clients. Please add it to your favourites
(click the star under the title) and join by clicking the "Join group
to post" button if you would like to participate.

The link to the forum:
https://groups.google.com/forum/#!forum/bvnc-ardp-aspice-opaque-android-bb10-clients

Cheers!
iordan

On Sun, Sep 6, 2015 at 2:36 PM, i iordanov <iiordanov@gmail.com> wrote:

> Hey,
>
> I've created a support group / forum for bVNC, aRDP, aSPICE, and Opaque,
> my remote desktop clients. Please add it to your favourites (click the star
> under the title) and join by clicking the "Join group to post" button if
> you would like to participate.
>
> Cheers!
> iordan
>
> On Mon, Jul 6, 2015 at 6:49 AM, M. Martin <notifications@github.com>
> wrote:
>
>> Hello,
>> I exported connections for VNC over SSH as XML. Than I edited some
>> entries and changed SSH password which was clear text. After importing all
>> SSH passwords are empty but it should use the ones from the imported XML
>> (like it was in export).
>> With many connections editing is much easier in an external editor as for
>> each item in bVNC.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/iiordanov/remote-desktop-clients/issues/51>.
>>
>
>
>
> --
> The conscious mind has only one thread of execution.
>



-- 
The conscious mind has only one thread of execution.

**Comment by iiordanov** [comment]
SSH Passwords are not saved for the moment. Please use SSH keys if you would like to login without a password.
