### ISSUE TITLE
bVNC v5.1.4 build 115149 - Zoomable scaling very slow on Android 5 phone

### ISSUE THREAD

**Issue by drghughes** [iiordanov/remote-desktop-clients#512]
Now that I've got the new version working on my Android 5 phone - see #507 - I've found that bVNC is very slow to respond when I try to change the scaling by "pinching" the screen.  Previously, while I had to give bVNC a little time at the beginning of a session, once I had done that, changing the scaling was very responsive.

This is with the scaling set to zoomable.  I'm connecting to a Raspberry Pi with a basic VNC connection.

Thanks!

**Comment by iiordanov** [comment]
If this is a side-effect of the SDK upgrade to 34, it spells doom to
Android 5 device support... Maybe it's better if you downgrade the app from
/releases, because there is no way I can downgrade SDK and continue to be
on Google Play past their cut-off in a few months!

**Comment by drghughes** [comment]
Thanks iordan.  I guess that I was expecting that it would be something like that.

Is the new SDK version used in all the v5.1.4 builds, i.e. I need to go back to v5.1.3?

**Comment by iiordanov** [comment]
Looking at commits, things should work up to 5.1.4_6 for you. Icons are
PNG, and SDK is 33.

Iordan

**Comment by drghughes** [comment]
Thanks Iordan!
