### ISSUE TITLE
Change desktop thumnails scale type to ScaleType.CENTER_CROP

### ISSUE THREAD

**Issue by seflerZ** [iiordanov/remote-desktop-clients#513]
In the source code "LabeledImageAdapter.java" the desktop thumnails were placed into the home page list imageView with default "ScaleType.CENTER_INSIDE".

If you have a foldable or large screen device, you'll notice the image thumbnail for each connection entry does not full fill the imageView. No good experience as I thought.

Just change it to "ScaleType.CENTER_CROP" or "ScaleType.FIT_CENTER" solves the problem. I can make the PR. But is any known reason for that default setting?
![Screenshot_20231230_192930](https://github.com/iiordanov/remote-desktop-clients/assets/2093588/c1c86765-bef7-4391-84f0-68208fce99f5)

**Comment by iiordanov** [comment]
Yeah, it's because I wanted the whole screen to be visible in the
thumbnail, it gives you context like orientation of the remote screen, etc.
I felt like with center crop, even though it looks all uniform, it's a lot
less useful.

**Comment by seflerZ** [comment]
Acknowledged.
