### ISSUE TITLE
Opaque build

### ISSUE THREAD

**Issue by lzulife1977** [iiordanov/remote-desktop-clients#52]
NDK-r9d
GSTREAMER-1.0

when I build, I get the following errors, could you tell me the reason. thanks.

[armeabi-v7a] Install        : libgstreamer_android.so => libs/armeabi-v7a/libgstreamer_android.so
[armeabi] SharedLibrary  : libspice.so
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/gtk/spice-gstaudio.o: in function record_bus_cb:jni/src/gtk/spice-gstaudio.c:159: error: undefined reference to 'gst_app_sink_pull_buffer'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/gtk/spice-gstaudio.o: in function record_bus_cb:jni/src/gtk/spice-gstaudio.c:169: error: undefined reference to 'GST_BUFFER_DATA'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/gtk/spice-gstaudio.o: in function record_bus_cb:jni/src/gtk/spice-gstaudio.c:169: error: undefined reference to 'GST_BUFFER_SIZE'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/gtk/spice-gstaudio.o: in function playback_data:jni/src/gtk/spice-gstaudio.c:357: error: undefined reference to 'gst_app_buffer_new'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/virt-viewer/virt-viewer-util.o: in function virt_viewer_util_extract_host:jni/src/virt-viewer/virt-viewer-util.c:65: error: undefined reference to 'xmlParseURI'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/virt-viewer/virt-viewer-util.o: in function virt_viewer_util_extract_host:jni/src/virt-viewer/virt-viewer-util.c:110: error: undefined reference to 'xmlFreeURI'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/virt-viewer/virt-viewer-util.o: in function virt_viewer_util_extract_host:jni/src/virt-viewer/virt-viewer-util.c:65: error: undefined reference to 'xmlParseURI'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/virt-viewer/virt-viewer-util.o: in function virt_viewer_util_extract_host:jni/src/virt-viewer/virt-viewer-util.c:110: error: undefined reference to 'xmlFreeURI'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/android/android-service.o: in function connectSession:jni/src/android/android-service.c:278: error: undefined reference to 'g_thread_init'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/android/android-service.o: in function CreateOvirtSession:jni/src/android/android-service.c:324: error: undefined reference to 'xmlParseURI'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/android/android-service.o: in function CreateOvirtSession:jni/src/android/android-service.c:344: error: undefined reference to 'xmlFreeURI'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/spice/android/android-service.o: in function CreateOvirtSession:jni/src/android/android-service.c:357: error: undefined reference to 'xmlFreeURI'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/libgovirt.a(libgovirt_la-ovirt-resource-rest-call.o): in function append_params:ovirt-resource-rest-call.c(.text+0x434): error: undefined reference to 'soup_form_encode_hash'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function authenticate:rest-proxy.c(.text+0x7d4): error: undefined reference to 'soup_auth_authenticate'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function rest_proxy_constructed:rest-proxy.c(.text+0x83c): error: undefined reference to 'soup_cookie_jar_new'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function rest_proxy_constructed:rest-proxy.c(.text+0x854): error: undefined reference to 'soup_session_add_feature'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function rest_proxy_constructed:rest-proxy.c(.text+0x868): error: undefined reference to 'soup_session_add_feature'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function rest_proxy_constructed:rest-proxy.c(.text+0x894): error: undefined reference to 'soup_logger_new'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function rest_proxy_constructed:rest-proxy.c(.text+0x8ac): error: undefined reference to 'soup_session_add_feature'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function rest_proxy_constructed:rest-proxy.c(.text+0x8c0): error: undefined reference to 'soup_logger_new'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function rest_proxy_constructed:rest-proxy.c(.text+0x8d8): error: undefined reference to 'soup_session_add_feature'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function rest_proxy_init:rest-proxy.c(.text+0xe98): error: undefined reference to 'soup_session_async_new'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function rest_proxy_init:rest-proxy.c(.text+0xea8): error: undefined reference to 'soup_session_sync_new'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function _rest_proxy_queue_message:rest-proxy.c(.text+0x1bf4): error: undefined reference to 'soup_message_get_type'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function _rest_proxy_queue_message:rest-proxy.c(.text+0x1cc0): error: undefined reference to 'soup_session_queue_message'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function _rest_proxy_cancel_message:rest-proxy.c(.text+0x1da4): error: undefined reference to 'soup_message_get_type'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function _rest_proxy_cancel_message:rest-proxy.c(.text+0x1e6c): error: undefined reference to 'soup_session_cancel_message'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function _rest_proxy_send_message:rest-proxy.c(.text+0x1f54): error: undefined reference to 'soup_message_get_type'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy.o): in function _rest_proxy_send_message:rest-proxy.c(.text+0x201c): error: undefined reference to 'soup_session_send_message'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-auth.o): in function rest_proxy_auth_new:rest-proxy-auth.c(.text+0x438): error: undefined reference to 'soup_session_get_type'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-auth.o): in function rest_proxy_auth_new:rest-proxy-auth.c(.text+0x4e0): error: undefined reference to 'soup_message_get_type'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-auth.o): in function rest_proxy_auth_new:rest-proxy-auth.c(.text+0x588): error: undefined reference to 'soup_auth_get_type'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-auth.o): in function rest_proxy_auth_pause:rest-proxy-auth.c(.text+0x7f0): error: undefined reference to 'soup_session_pause_message'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-auth.o): in function rest_proxy_auth_unpause:rest-proxy-auth.c(.text+0x988): error: undefined reference to 'soup_auth_authenticate'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-auth.o): in function rest_proxy_auth_unpause:rest-proxy-auth.c(.text+0x9c4): error: undefined reference to 'soup_session_unpause_message'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function finish_call:rest-proxy-call.c(.text+0x1a08): error: undefined reference to 'soup_message_headers_foreach'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function set_header:rest-proxy-call.c(.text+0x1d6c): error: undefined reference to 'soup_message_headers_replace'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x1fbc): error: undefined reference to 'soup_message_new'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x1fe0): error: undefined reference to 'soup_message_set_request'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x2040): error: undefined reference to 'soup_form_request_new_from_hash'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x2060): error: undefined reference to 'soup_multipart_new'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x20bc): error: undefined reference to 'soup_multipart_append_form_string'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x2108): error: undefined reference to 'soup_buffer_new_with_owner'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x2148): error: undefined reference to 'soup_multipart_append_form_file'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x2150): error: undefined reference to 'soup_buffer_free'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x218c): error: undefined reference to 'soup_form_request_new_from_multipart'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x2198): error: undefined reference to 'soup_multipart_free'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function prepare_message:rest-proxy-call.c(.text+0x21d8): error: undefined reference to 'soup_message_headers_append'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-proxy-call.o): in function rest_proxy_call_continuous:rest-proxy-call.c(.text+0x2c44): error: undefined reference to 'soup_message_body_set_accumulate'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x304): error: undefined reference to 'xmlReaderForMemory'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x314): error: undefined reference to 'xmlTextReaderNodeType'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x338): error: undefined reference to 'xmlTextReaderConstName'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x4b8): error: undefined reference to 'xmlTextReaderIsEmptyElement'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x560): error: undefined reference to 'xmlTextReaderHasAttributes'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x574): error: undefined reference to 'xmlTextReaderMoveToFirstAttribute'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x57c): error: undefined reference to 'xmlTextReaderConstLocalName'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x588): error: undefined reference to 'xmlTextReaderConstValue'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x610): error: undefined reference to 'xmlTextReaderMoveToNextAttribute'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x644): error: undefined reference to 'xmlTextReaderConstLocalName'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x770): error: undefined reference to 'xmlTextReaderConstValue'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x7f8): error: undefined reference to 'xmlTextReaderNodeType'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x840): error: undefined reference to 'xmlTextReaderRead'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x854): error: undefined reference to 'xmlTextReaderClose'
/root/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: jni/src/../libs/deps/lib/librest-0.7.a(librest_0.7_la-rest-xml-parser.o): in function rest_xml_parser_parse_from_data:rest-xml-parser.c(.text+0x85c): error: undefined reference to 'xmlFreeTextReader'
collect2: ld returned 1 exit status
make: *** [obj/local/armeabi/libspice.so] Error 1
make: *** Waiting for unfinished jobs....

**Comment by iiordanov** [comment]
This is because of the switch from gstreamer-0.10 to gstreamer-1.0. I'm looking into porting to gstreamer-1.0 at the moment, in the meanwhile you'd have to use an old distribution of the gstreamer library versioned 0.10.

**Comment by iiordanov** [comment]
Take a look at the gstreamer-1.0 branch and see whether it works for you. I found that for now, only gstreamer 1.4.5 works (see the BUILDING file).
