### ISSUE TITLE
USB redirect in Opaque - android 13 - possible regression introduced in version 5.1.7

### ISSUE THREAD

**Issue by paweljasinski** [iiordanov/remote-desktop-clients#526]
When I build version 5.1.6 forwarding of usb device in opaque **works as expected**.
When I build version 5.1.7 forwarding of usb device **doesn't work**.
When I build version 5.2.5 forwarding **doesn't work**.
When I build version 5.2.5 and revert commit 3681e2d4ba03795, it **works as expected**.

I am building using latest and greatest android studio (Android Studio Hedgehog | 2023.1.1 Patch 2), os is up to date arch linux.
The android sdk has both Tiramisu (13) and UpsideDownCake (14) installed. The only modifications I do is increase memory limit for gradle and disable custom vnc app.
The target is device running **android 13**.
When things don't work, I don't get the prompt to allow forwarding for a specific connected device and the [logcat.txt](https://github.com/iiordanov/remote-desktop-clients/files/14285141/logcat.txt) is spammed with USB permission messages

**Comment by iiordanov** [comment]
Without this commit, the app was crashing on Android 14. I'll need to see how I can get my hands on an older device to test now.

**Comment by 5A52** [comment]
I can confirm on android 13 (oneUI 5.1) when more then one USB device is connected
5.1.6 possible to choice device canceling one by one
5.6.6 only first device can be used
P.S. Is it possible to implement device choicer like in linux virt-viewer?

**Comment by paweljasinski** [comment]
> Without this commit, the app was crashing on Android 14.
I have tested on 14 and it doesn't crash but it also doesn't forward devices.
> I'll need to see how I can get my hands on an older device to test now.
This is so annoying, once you update to 14 there is no way to go back.
