### ISSUE TITLE
Root ADB

### ISSUE THREAD

**Issue by Sonyversion8** [iiordanov/remote-desktop-clients#529]

**Comment by Sonyversion8** [comment]
Can some Body help me please ?

I want Linux on my Android devices (wiko)

**Comment by iiordanov** [comment]
Hey there, I am sorry but this is not a support forum for running Linux on
Android. This issue tracker is for bug reports or enhancement requests for
bVNC, aRDP, aSPICE for both Android and iOS, and Opaque for Android.

**Comment by Sonyversion8** [comment]
Can some Body help me please ?

I want Linux on my Android devices (wiko)


I am sorry i am new in this action,😂
