### ISSUE TITLE
build error,"I-c From Scratch",Command Error: Running ['aarch64-linux-android-ar',

### ISSUE THREAD

**Issue by wyythsl2022** [iiordanov/remote-desktop-clients#536]
Hello, I am compiling according to the steps in "I-c From Scratch" on the ubuntu18.04 operating system
the information on the console：
Running cerbero build for armeabi-v7a in /home/test/spice/remote-desktop-clients-master/remoteClientLib/jni/libs
Install prefix will be /home/test/spice/remote-desktop-clients-master/remoteClientLib/jni/libs/cerbero/build/dist/android_universal
Building the following arches: armv7 arm64 x86 x86_64
Building the following recipes: gnustl libffi zlib proxy-libintl libiconv glib gstreamer-1.0 ca-certificates openssl glib-networking libxml2 pixman libpsl sqlite3 libsoup libpng expat bzip2 freetype fontconfig cairo json-glib libogg fribidi harfbuzz pango libvorbis libtheora libvisual orc opus graphene libjpeg-turbo tremor gst-plugins-base-1.0 speex tiff gdk-pixbuf mpg123 lame wavpack flac taglib libvpx libdv gst-plugins-good-1.0 a52dec opencore-amr x264 gst-plugins-ugly-1.0 libkate openh264 librtmp libsrtp libdca libmms libnice soundtouch vo-aacenc libcroco librsvg openjpeg spandsp webrtc-audio-processing sbc ladspa srt libusrsctp zbar vulkan-android gst-plugins-bad-1.0 ffmpeg gst-libav-1.0 gst-rtsp-server-1.0 gst-devtools-1.0 gst-editing-services-1.0 gst-android-1.0 spice-protocol gtk-doc-lite libjpeg8 pyparsing six liblz4 libusb-1.0 spice-usbredir spice-gtk spiceglue
Building using 4 job(s) with the following job subdivisions: 4 general job(s)
-----> Contents of /home/test/spice/remote-desktop-clients-master/remoteClientLib/jni/libs/cerbero/build/logs/android_arm64/gnustl-compile.log:

Recipe 'gnustl' failed at the build step 'compile'
Command Error: Running ['aarch64-linux-android-ar', 'rc', '/home/test/spice/remote-desktop-clients-master/remoteClientLib/jni/libs/cerbero/build/dist/android_universal/arm64/lib/libandroid_support.a'] returned -1

Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort

I am really looking forward to your help. Thank you！！

**Comment by iiordanov** [comment]
Hi there, I spent a few hours fixing the docker build process this weekend. It now uses Ubuntu 20.04. Please try it and let me know if you experience issues, and I'll reopen the issue.
