### ISSUE TITLE
Error instilling deivedroid

### ISSUE THREAD

**Issue by Viju9373** [iiordanov/remote-desktop-clients#539]
The previliged permission have not been granted to the 
extension!

**Comment by iiordanov** [comment]
What store are you trying to install Opaque from?

**Comment by Viju9373** [comment]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable: General information Android Version And bvnc not install for nethunter

**Comment by Viju9373** [comment]
Bug nethunter installer has been bvnc and all apps
