### ISSUE TITLE
aspice

### ISSUE THREAD

**Issue by littleLam** [iiordanov/remote-desktop-clients#54]
I have git the codes ,and use eclipse to buid it.It have ceated bVNC.apk. but I only want to spice protocal .How to set the project to build aSPICE.apk? Thanks.

**Comment by iiordanov** [comment]
Please refer to the BUILDING file in the repository., and let me know if there were changes needed.thanks!                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: littleLamSent: Wednesday, August 12, 2015 04:22To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsSubject: [remote-desktop-clients] aspice (#54)I have git the codes ,and use eclipse to buid it.It have ceated bVNC.apk. but I only want to spice protocal .How to set the project to build aSPICE.apk? Thanks.

—Reply to this email directly or view it on GitHub.

**Comment by littleLam** [comment]
I hava find it, thank you very much! The Good Life of Peace!
