### ISSUE TITLE
[aRDP Free] I'm having difficulty making a "RDP over SSH" connection

### ISSUE THREAD

**Issue by OneDefauter** [iiordanov/remote-desktop-clients#543]
aRDP Free version: v5.2.9

I'm having difficulty making a "RDP over SSH" connection.
What I'm trying to do is the following: 
I'm attempting to establish a reverse SSH connection from my computer to my VPS so that another device outside the network can make the RDP connection (my internet service provider does not allow port forwarding). 

I watched some videos to understand how it works:
[In this video, I understood that in my case it has to be reverse tunneling](https://www.youtube.com/watch?v=Y2v8Hn11H-s)
[In this other one, he shows a similar example of what I want to do](https://youtu.be/AtuAdk4MwWw?si=QPFtDuj76opxrY4b&t=264)

What I've already done:
I successfully established the reverse SSH connection.
![image](https://github.com/iiordanov/remote-desktop-clients/assets/27703239/e7be1a5a-064a-445f-945c-84c3e47cce1d)

RDP over SSH Configuration (not sure if everything I've put here is correct)
![image](https://github.com/iiordanov/remote-desktop-clients/assets/27703239/6dc38170-7427-4f71-b375-3dee0a8c88f0)

Generate the key and copy (I've set a password).
![image](https://github.com/iiordanov/remote-desktop-clients/assets/27703239/be68af45-011d-4567-bac7-c8f45c1b8905)

On the VPS, I used the command:

```
nano .ssh/authorized_keys
```

to insert the copied key.
![image](https://github.com/iiordanov/remote-desktop-clients/assets/27703239/bb5c801e-f129-457c-aa77-c6cca58150d6)
![image](https://github.com/iiordanov/remote-desktop-clients/assets/27703239/aa8f044e-b72a-4416-aeb6-8aff9747814d)

So, the configurations in aRDP ended up like this
![image](https://github.com/iiordanov/remote-desktop-clients/assets/27703239/d3643354-b3b8-4230-9e6c-a5c08e375554)

When I try to connect, it gives an error.
![image](https://github.com/iiordanov/remote-desktop-clients/assets/27703239/edac024e-b567-44eb-8c74-79bf62fad73f)

Am I doing it wrong?
Did I forget something?
Does it need to be the PRO version?

An addendum, these are the port rules of my VPS
![image](https://github.com/iiordanov/remote-desktop-clients/assets/27703239/7c2f8cba-4008-4e70-a76f-96a502175139)

**Comment by iiordanov** [comment]
The app tells you it cannot connect to your SSH server, so you need to solve that issue first. I am unable to debug specific configuration issues for all my hundreds of thousands of users, apologies!
