### ISSUE TITLE
aRDP: video is slow with eventual lockup.

### ISSUE THREAD

**Issue by andrewc12** [iiordanov/remote-desktop-clients#545]
While using aRDP on an android tv if I ever come across a video the sound plays in real time but the video plays slowly constantly getting further behind.
Mouse inputs get sent in real time still.
Eventually something breaks and nothing gets updated.

I don't know what is happening it seems like something doesn't want to drop frames.

I might be able to get a video in the future.

**Comment by iiordanov** [comment]
Have you tried to enable GFX in Advanced Settings?

Have you tried to lower the resolution?

Thanks!

**Comment by andrewc12** [comment]
I turned on remote GFX it still stutters but it eventually skips frames so that's better
