### ISSUE TITLE
Is it possible to disable the onscreen buttons?

### ISSUE THREAD

**Issue by kaalph** [iiordanov/remote-desktop-clients#546]
Hello, I was wondering if it's possible to disable the onscreen buttons. Unfortunately, I haven't been able to find any settings where I could do this. Thank you for a prompt reply.
![firefox_mBHIrmCBFd](https://github.com/iiordanov/remote-desktop-clients/assets/138721439/a416cada-e1e1-44ed-9bc0-42955bf203f0)

**Comment by iiordanov** [comment]
Yes, you can tap the menu on the toolbar and use the Disable Extra Keys
option.
