### ISSUE TITLE
When aRDP connects to Windows Terminal Server through ChromeOs ...

### ISSUE THREAD

**Issue by OscarLake** [iiordanov/remote-desktop-clients#548]
When aRDP free 5.3.5 connects to Windows Terminal Server 2016 through ChromeOs 114.0.5735.119 64 bits, the keyboard strokes on the ASUS C302C (es-ES keyboard) doesn't match on the server side, normal letter are OK, but accent marks doesn't combine, for example, a plus `, should be à but appears like a``a``a, and é, like -e-e-e-e-, etc, I tried to activate the unicode key sending toggle, but does the same, i think its something like unknown keyboad inputs (ASUS weird kb keybindings)

**Comment by iiordanov** [comment]
Hi there, could you:

1) Confirm what keyboard layout is set in Settings->Device->Keyboard-> Change
language and input settings > Input method and look fof keyboard layout?

2) Confirm what keyboard layout is set on the remote computer?

3) Do you have any other Windows machine to compare to and tell me what is
the situation there? I only have Server 2022 and Windows 10/11.

**Comment by iiordanov** [comment]
@OscarLake I assume my comments helped since I didn't hear back. Please comment if I should reopen and respond to my suggestions.
