### ISSUE TITLE
How to change FreeRDPCore version?

### ISSUE THREAD

**Issue by wlgus9343** [iiordanov/remote-desktop-clients#549]
i download the freerdp version3 to freerdp github and I have overwritten version 3's jni files, but I get an error saying that I need the old version of jni lib files. How can I upgrade to version 3?

**Comment by wlgus9343** [comment]
how to change the freerdp version? where is precompiled binaries

**Comment by iiordanov** [comment]
To change the RDP version, you must build the app from source, including FreeRDP.

     remoteClientLib/jni/libs/build-deps.conf

contains the FreeRDP version

    remoteClientLib/jni/libs/build-deps.sh

is used by 

    bVNC/prepare_project.sh 

which is documented in README.md in the procedure for building from source.
