### ISSUE TITLE
aRDP: Right-Clicking not working

### ISSUE THREAD

**Issue by Valentin-Lill** [iiordanov/remote-desktop-clients#550]
Hey,

I am trying to connect to my Windows Server from my Xiaomi Android Tablet. For this tablet I have the original keyboard/touchpad combo, which works fine for every application except for aRDP. Currently, in aRDP the keyboard and touchpad work perfectly except that for some reason in this application the right-click seems to not register.

What I have tried for right-clicking without success:
- Tap with 2 fingers
- Click with 2 fingers
- Click and hold with one finger

Here is a quick log file I created by enabling "More debug logging", restarting the app, logging into my server and trying some clicking and rightclicking with the methods mentioned above.
- https://pastebin.com/rnWigTRN

Hope you can help me out, I have not changed any settings except for adjusting the screen resolution.

**Comment by iiordanov** [comment]
Hey @Valentin-Lill, I released v5.4.8 to *beta* with a potential fix for your device.

Please join Beta from Google Play and make sure you get 5.4.8 (look in the "star" icon dialog at the bottom).

Let me know how it goes.

**Comment by iiordanov** [comment]
Please comment if I should reopen.
