### ISSUE TITLE
falha na conexão com o termux 

### ISSUE THREAD

**Issue by gregoqz7** [iiordanov/remote-desktop-clients#551]
servidor do termux não está conectando com o kex , e conexão de rede é a melhor (google)

**Comment by iiordanov** [comment]
Hey, I am not one of the KEX developers. I develop bVNC which is a remote desktop application not related to KEX in any way. Apologies and thanks!

**Comment by gregoqz7** [comment]
sorry friend, I made a mistake, I only now realized that 😅

Em qui., 2 de mai. de 2024, 18:01, iiordanov ***@***.***>
escreveu:
