### ISSUE TITLE
Need to associate with .rdp file on android

### ISSUE THREAD

**Issue by donbowman** [iiordanov/remote-desktop-clients#552]
Would like to switch from rdclient to ardp.
Our infrastructure generates a .rdp file (with embedded gateway parameters).
However:
a) when clicking it in the browser, it does not open (downloads)
b) when selecting it from the downloads, and 'open with', it says "none of your applications can open this file"

On the app settings, i have "Open by default", as 'open supported links' (clicked).

How may i open (automatically, or via share-to, or via downloads) an .rdp file i have?

it appears the app might want `application/vnd.rdp` but not `application/rdp`

**Comment by iiordanov** [comment]
The app currently doesn't support .RDP files. Please reach out to us by email at support _at_ morpheusly _dot_ com if your company would be interested in a collaboration with ours.

**Comment by iiordanov** [comment]
aRDP Pro now supports .rdp files!
