### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Guyabson** [iiordanov/remote-desktop-clients#557]
Connection keeps resetting

**Comment by Jisux23** [comment]
Typing time black screen problem 
![Screenshot_20240704_133512_NetHunter KeX](https://github.com/iiordanov/remote-desktop-clients/assets/174036041/7211cc15-78ab-4ba7-9da6-f49d07e3fb4b)

**Comment by iiordanov** [comment]
What app is this?

What (server) are you connecting to?
