### ISSUE TITLE
kex app

### ISSUE THREAD

**Issue by kishor-babu** [iiordanov/remote-desktop-clients#558]
is not working properly how to us

**Comment by 967155** [comment]
![Screenshot_20240621-115909](https://github.com/iiordanov/remote-desktop-clients/assets/173448233/6811d429-42f1-46b7-a24e-e12d674bc8c0)

**Comment by Lowoluwung** [comment]
Masih belum paham bagaimana menggunakannya

**Comment by iiordanov** [comment]
This is not a KEX / Nethunter support forum.
