### ISSUE TITLE
In aspice,cursor channel don't have the action

### ISSUE THREAD

**Issue by freshmanlinux** [iiordanov/remote-desktop-clients#56]
I have a question about the properties of the client mouse cursor.The version of my bVNC project is v3.6.6.My terminal platform is thin client about android system without touch screen,and virtual desktop system is win7.Of course,my thin client has the usb mouse.After thin client connecting to the virtual desktop,I open a dialog.But when I move the mouse to the dialog edge,the shape of mouse cursor don't have the changes.Don't like the phenomenon under win7.I have a look at the sources about aspice,the mouse cursor is the native mouse about android.There are channel-cursor.c and spice-widget.c in the sources of aspice,but they don't have the action.If thin client is under ubuntu system,the native mouse cursor shape will have the changes with the win7.If my thin client is about android system ,what should I do in order to make the native mouse cursor have the same changes with the win7? Thanks!

**Comment by iiordanov** [comment]
This is dependent on the VNC server. There was recently a fix put in place (past v4.0.9 to ensure the local mouse pointer is not masking the pointer changes if the server sends the remote pointer shape).
