### ISSUE TITLE
"Server already started" Nethunter kex

### ISSUE THREAD

**Issue by JametPemula** [iiordanov/remote-desktop-clients#563]
![Screenshot_20240716-130456_Lawnchair~2](https://github.com/user-attachments/assets/5a096de5-66fc-4427-9962-24e007448a71)
![Screenshot_20240716-141759_Lawnchair](https://github.com/user-attachments/assets/26ed1542-979e-4c61-9158-253e269ddc62)
When I want to turn on the KEX server, something like that appears there... I tried to enter the KEX VNC but it got a connection error 
I tried to stop the server but it says "There's no active session".
I've tried reinstalling nethunter but it still doesn't work

**Comment by iiordanov** [comment]
This is not a KEX / Nethunter support forum.
