### ISSUE TITLE
Port 22 not open and not connecting

### ISSUE THREAD

**Issue by Bigdaddy2k25** [iiordanov/remote-desktop-clients#565]
Port 22 on my device isn't opened and getting error![Screenshot_20240718_195059_NetHunter KeX.jpg](https://github.com/user-attachments/assets/d2b1f385-01e1-40e6-865c-a2d82044424e)

**Comment by makombelajob** [comment]
check with " sudo systemctl status ssh " and after you can enable and start it. Or reinstall ssh and make this process to open the port

**Comment by iiordanov** [comment]
Thanks @makombelajob for helping on this issue.
