### ISSUE TITLE
Generate private key in iOS aRDP Pro app

### ISSUE THREAD

**Issue by mevdschee** [iiordanov/remote-desktop-clients#566]
Hi,

Thank you for the great software (aRDP Pro) that you have made. Our customers need to generate a private key on the device (for security reasons) and mail us the public key. In order to do so it would be great if there was a "generate private key" and "copy public key" buttons that generate and copy the ECDSA key. I hope you can add this to the iOS version (AFAIK the Android version already has such functionality). We tried copy-pasting the key, but people create wrong key types and also make mistakes with copy-pasting, leading to rejection of the SSH key.

Kind regards,

Joost and Maurits van der Schee

**Comment by iiordanov** [comment]
Hi @mevdschee this is a great feature request. In the meanwhile, as a workaround, a command like the following:

`ssh-keygen -t ecdsa -f /tmp/keyfile1 -N ""`

Will generate a key without a passphrase whose private part you can paste right into the application.

**Comment by biggestsonicfan** [comment]
Ah, was just trying to figure out where the key generation was and came across this issue. Good workaround.

**Comment by biggestsonicfan** [comment]
I did end up going the refund route and I think it's mainly the 5th gen iPad's fault. I thought it might finally get some use through RDP but it looks like it's too clunky to handle it.

**Comment by iiordanov** [comment]
https://gitlab.com/iiordanov/remote-desktop-clients-ios/-/commit/430b4cc6aa176b0b7d468a43f7a2784a18b9e30b provides functionality to generate an ssh key in-app.

**Comment by mevdschee** [comment]
Thank you very much! I'm looking forward to a much easier on-boarding of iOS users on our RDP over SSH service(s).

**Comment by iiordanov** [comment]
@mevdschee I need help Beta testing version 40 of aRDP that uses a newer library and is compiled for Mac Catalyst Silicon architecture. If you're interested in helping ensure the next version is stable and works for your use-case, please send an email to support _at_ morpheusly _dot_ com.
