### ISSUE TITLE
Connecting problem 

### ISSUE THREAD

**Issue by Anrak-tremux** [iiordanov/remote-desktop-clients#568]
Can couldn't able to see connect button on lobby

**Comment by iiordanov** [comment]
You are trying to connect to Kali / KEX and their documentation is out of
date and I am not a developer on their team.

**Comment by Black7boy** [comment]
O botão Connect não aparece, oq há de errado ?

**Comment by iiordanov** [comment]
You are trying to connect to Kali / KEX and their documentation is out of
date and I am not a developer on their team

**Comment by Bhatbhat** [comment]
Connecting problem

**Comment by parkourmaster464** [comment]
How to fix

**Comment by iiordanov** [comment]
This issue is invalid because it concerns old KEX / Nethunter documentation using an old version of bVNC. That project has forked bVNC and has not updated their docs even though they are no longer valid.
