### ISSUE TITLE
Support fourm bannned

### ISSUE THREAD

**Issue by rimwulf** [iiordanov/remote-desktop-clients#569]
The support form has been banned and I am requesting that it is updated to a new location or removed.

**Comment by iiordanov** [comment]
I've reached out to google and requested instructions on how to appeal a group suspension. The process is as follows for anybody who needs it:

Appeal a group suspension

Requires the Owner role.

If you own a group that’s been suspended, you can appeal the suspension. Google suspends groups that violate the Google Groups content policy in any way. If you remove the inappropriate content or believe the suspension is in error, you can ask Google to review a suspension.

Request a review

    Sign in to Google Groups.
    In the address bar, enter the group’s URLand thenpress Enter or Return.You can only access suspended groups using their URL.
    On the banned content warning page, click Continue Anyway.
    On the left, click Group settings.
    At the top, click Request review and then Submit report.

If the appeal is successful, you and your group members can access and work with the group as usual.
I hope the information helps. If you have further concerns or questions, feel free to reply to this email. I am happy to help.

Within 48 hours of our last interaction, you may receive a short survey via email. We'd love to hear your feedback about our interaction today and your overall experience with Google support.

**Comment by rimwulf** [comment]
So why not a reddit, Facebook group, etc? Just curious.

**Comment by iiordanov** [comment]
This forum is quite old, when the alternatives you mention were not popular
for a support forum.

There are many, many years of work locked up in this forum at present.

Iordan
