### ISSUE TITLE
aRDP: It is exceedingly difficult to accurately submit a right-click

### ISSUE THREAD

**Issue by cemysce** [iiordanov/remote-desktop-clients#575]
I have been using aRDP for a few years (from a phone, not a tablet).  I have tried the various mouse input modes, and I haven't found a way to accurately, effectively, and consistently submit a right-click.  Even when I am able to get the right-click submitted, I often end up also submitting a tap elsewhere on the screen so the cursor moves and something unintended occurs as a result.

Please consider some means of submitting a right-click which does not require a multi-touch gesture.  I used to use Jump Desktop (until they discontinued their Android app) and it had a [fantastic input scheme](https://support.jumpdesktop.com/hc/en-us/articles/216423503-Getting-Started-Jump-Desktop-Controls-and-Gesture-Reference):
|action|gesture|
|-|-|
|click|tap _(i.e. same as aRDP)_|
|**double click**|**double tap**|
|**right click**|**long press**|
|**click + drag**|**double tap, then drag before lifting finger from 2nd tap (like how you'd do it on a laptop trackpad)**|
|scroll wheel up/down|2-finger swipe up/down|
|zoom screen|pinch _(i.e. same as aRDP)_|
|toggle keyboard|3-finger tap|

You may decide to implement some of that differently, maybe you can think of something even better, but I've highlighted in bold the ones I think are really intuitive the way Jump Desktop did it.

**Comment by iiordanov** [comment]
Tey Single Handed input mode.

Long tap, until a virtual mouse pops up on screen. You can reposition the
pointer any number of times now. To send right click, tap the right button
on the virtual mouse.

Simulated Touchpad should also not suffer from stray clicks, since the
pointer stays where it is, but maybe I am not appreciating some difficulty.

**Comment by iiordanov** [comment]
Please comment if my suggestions didn't help and I'll reopen.
