### ISSUE TITLE
aRDP: Please provide offset way to control mouse cursor (to not obscure it with finger)

### ISSUE THREAD

**Issue by cemysce** [iiordanov/remote-desktop-clients#576]
I have been using aRDP for a few years (from a phone, not a tablet), and I've found it challenging at times to accurately position the cursor, not just because I'm controlling a desktop (with finer UI controls) from a phone (with coarser UI controls), but because my finger is obscuring the area on the screen where I am trying to move/place the cursor.

Please consider an offset way of moving the mouse cursor.  I used to use Jump Desktop (until they discontinued their Android app) and it had fantastic mouse controls &mdash; overlaid on top of the remote screen (offset at some configurable position from the mouse cursor) would be a translucent circle, and instead of tapping/dragging directly on the remote machine's screen you'd tap/drag that circle.  That way, your finger would not obscure the mouse cursor at all.

You may decide to implement something a bit different, maybe something even better, but please consider improving the mouse cursor movement controls so one's own fingers don't get in the way.  Thanks!

**Comment by iiordanov** [comment]
Isn't the already present Simulated Touchpad input mode what you are
looking for?

**Comment by cemysce** [comment]
Hmm, I guess that works.  Arguably better than my suggestion because there
isn't a fixed spot to tap/drag , you can tap/drag anywhere.  Okay I think
there isn't much point to this issue report, you may close it.

I think there is still merit to the other issues I submitted.  Sorry for
submitting so many at once!

**Comment by iiordanov** [comment]
Thanks
