### ISSUE TITLE
Could not resolve project :remoteClientLib:jni:libs:deps:FreeRDP:client:Android:Studio:freeRDPCore

### ISSUE THREAD

**Issue by yangtao1992** [iiordanov/remote-desktop-clients#577]
Report this error when clicking to run
<img width="1194" alt="错误1" src="https://github.com/user-attachments/assets/2acc3e2f-1ff5-463b-9002-00ded0f3938e">
<img width="1368" alt="错误2" src="https://github.com/user-attachments/assets/738b58d7-3e89-42ac-bdc2-020211415ef9">

**Comment by yangtao1992** [comment]
Have you all encountered this problem before? How was it resolved?

**Comment by yangtao1992** [comment]
What should I do? Thank you

**Comment by iiordanov** [comment]
Yes, look in the readme for instructions on how to download or build the
project dependencies.
