### ISSUE TITLE
aRDP Pro on Samsung DeX - External Bluetooth Keyboard Arrow keys captured for mouse

### ISSUE THREAD

**Issue by colintoal** [iiordanov/remote-desktop-clients#584]
Hi - aRDP is great - super fast, good work.

I use a Samsung S23 Plus phone as a laptop/desktop replacement. I use it with an external monitor, bluetooth keyboard and bluetooth mosue, and aRDP works great, except it captures the arrow keys on the external keyboard to move the mouse! It would be great if there was a setting that disables that behaviour as it makes it very difficult to use applications on the host that require mouse key input.

Thanks for a great project.

**Comment by iiordanov** [comment]
There is a setting for that in Advanced Settings.

Please don't forget to give us 5-stars!

Cheers!
Iordan

**Comment by iiordanov** [comment]
@colintoal please comment if that didn't resolve your issue. Closing for now.
