### ISSUE TITLE
bVNC: When using a mouse to click the floating tool-bar, clicks are passed through to the toolbar but also to the remote OS

### ISSUE THREAD

**Issue by AtmanActive** [iiordanov/remote-desktop-clients#599]
If I click on bVNC‘s built-in toolbar to open the keyboard or to disconnect, I DON'T want that click to go through to the host.

I'm not sure if this behavior changed recently, but if it did, then please add a global preferences affordance to allow users to choose what works for them.

Thanks.

**Comment by AtmanActive** [comment]
Did you try tapping or clicking with a mouse?

I'm using bVNC pro on Android with a Bluetooth mouse attached.

**Comment by AtmanActive** [comment]
And, just double-checked with a mouse on Android - click through is occurring.

So, the issue is with mouse pointer handling on the overlay menu.

Hopefully, you'll be able to replicate now.

Thanks!

**Comment by iiordanov** [comment]
Yes, it's definitely reproducible with a mouse. Thanks, great find, great bug-report. I'll try to get that fixed as soon as I have time. Cheers!

**Comment by iiordanov** [comment]
Fixed in https://github.com/iiordanov/remote-desktop-clients/commit/d1f811d5c2774787887d28c8e451cdc9c8352dda, released to beta.

**Comment by AtmanActive** [comment]
Thank you for the quick fix. It is working great now.
