### ISSUE TITLE
Nethunter kex Black screen problem

### ISSUE THREAD

**Issue by abidhasansojib** [iiordanov/remote-desktop-clients#604]
Recently I have installed kali nethunter rooted on my mobile.When I start kex and try to connect using nethunter kex it works fine.After I close nethunter kex app or minimize it and again try to connect again it again connect s fine but the screen is black somewhere on the screen like dead pixels.It gone If I drag any program on the black spot.I tried bvnc pro apk.There is no bug like this.But there is a bug in Nethunter KeX app.Please consider fixing it.
![Screenshot_2024-12-23-14-05-34-55](https://github.com/user-attachments/assets/06f95097-97d1-453e-b25b-c6f866d4ae45)

**Comment by iiordanov** [comment]
Nethunter app is a fork of this project and I do not maintain it.

**Comment by abidhasansojib** [comment]
It's ok but thanks for replying.I have found a solution and modded
nethunter app to support bvnc pro.
