### ISSUE TITLE
Mouse acceleration in touchpad mode

### ISSUE THREAD

**Issue by kokoko3k** [iiordanov/remote-desktop-clients#63]
Is there a way to disable mouse acceleration in touchpad mode under bVNC?
The pointer isn't very friendly to me, that way.

Thanks!

**Comment by iiordanov** [comment]
Hi Antonio, This feature has been requested before, and it is on the roadmap.Thanks!iordan                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: Antonio OreficeSent: Thursday, October 29, 2015 05:11To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsSubject: [remote-desktop-clients] Mouse acceleration in touchpad mode (#63)Is there a way to disable mouse acceleration under bVNC?
The pointer isn't very friendly to me, that way.

Thanks!

—Reply to this email directly or view it on GitHub.

**Comment by kokoko3k** [comment]
Thanks
