### ISSUE TITLE
add BROWSABLE to intent filters

### ISSUE THREAD

**Issue by jp-bennett** [iiordanov/remote-desktop-clients#68]
I've hit an issue where it would be extremely useful to be able to launch an Android VNC client from a link in a web page.  bVNC blocks this behavior by not including the "android.intent.category.BROWSABLE" tag in its intent filters.  I'm following the official documentation from https://developer.chrome.com/multidevice/android/intents to try to get this working.

Ideally the intent could specify at least the url, port, and password.

Thanks
--Jonathan Bennett

**Comment by iiordanov** [comment]
Hi Jonathan,

Can you please give me example html code I can test your request with?

Thanks,
iordan

On Tue, Apr 12, 2016 at 3:12 PM, Jonathan Bennett <notifications@github.com>
wrote:

> I've hit an issue where it would be extremely useful to be able to launch
> an Android VNC client from a link in a web page. bVNC blocks this behavior
> by not including the "android.intent.category.BROWSABLE" tag in its intent
> filters. I'm following the official documentation from
> https://developer.chrome.com/multidevice/android/intents to try to get
> this working.
>
> Ideally the intent could specify at least the url, port, and password.
>
> Thanks
> --Jonathan Bennett
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/iiordanov/remote-desktop-clients/issues/68>
>



-- 
The conscious mind has only one thread of execution.

**Comment by oneru** [comment]
From what I can tell, something like `<a href="intent://192.168.1.1:5900/#Intent;scheme=vnc;package=com.iiordanov.freebVNC;end"> launch vnc </a>` should work.

**Comment by iiordanov** [comment]
Hey, I finally had a few minutes to look at some of the issues I had deferred. I've implemented and tested this and it works great, but I have to test whether it didn't break something. So it'll be released in v4.1.1 whenever that comes out. Thanks!

https://github.com/iiordanov/remote-desktop-clients/commit/f4cfaeba4106c129cf02c4e1691710e9bb64cd6b
