### ISSUE TITLE
Amazon Fire HDX8.9 and aRDP keyboard issues

### ISSUE THREAD

**Issue by rec9140** [iiordanov/remote-desktop-clients#69]
Amazon HDX8.9 with Fire OS v5.1.2 aka Android 5 Lollipop with aRDP 3.7.9 Free.

Connecting to a RDP based setup, I kept getting password rejected when using the keyboard in aRDP, logged it in another way, and then when typing on the keyboard in aRDP, it was not sending keystrokes to the remote side. Kept pressing and pressing keys, and then a random key that I had pressed would show up ie: google.com , and . was all that would show up .

Installed and tested on a Galaxy S3, no issues. 

Seems to be some issue sending keystrokes from the keyboard on the Fire HDX tablet.

Please advise what info you might need or testing. Thanks.

**Comment by iiordanov** [comment]
I would first advise using another keyboard on your Amazon HDX8.9. Is one
available from the App Store?

Is the keyboard a swipe type keyboard? Is it possible "space" would make it
send whole strings over? Try typing something and sending space to see if
the characters show up.

Cheers!
iordan

On Wed, Apr 20, 2016 at 6:25 PM, rec9140 <notifications@github.com> wrote:

> Amazon HDX8.9 with Fire OS v5.1.2 aka Android 5 Lollipop with aRDP 3.7.9
> Free.
>
> Connecting to a RDP based setup, I kept getting password rejected when
> using the keyboard in aRDP, logged it in another way, and then when typing
> on the keyboard in aRDP, it was not sending keystrokes to the remote side.
> Kept pressing and pressing keys, and then a random key that I had pressed
> would show up ie: google.com , and . was all that would show up .
>
> Installed and tested on a Galaxy S3, no issues.
>
> Seems to be some issue sending keystrokes from the keyboard on the Fire
> HDX tablet.
>
> Please advise what info you might need or testing. Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/iiordanov/remote-desktop-clients/issues/69>
>



-- 
The conscious mind has only one thread of execution.

**Comment by rec9140** [comment]
>Is the keyboard a swipe type keyboard? Is it possible "space" would make it send whole strings over? >Try typing something and sending space to see if the characters show up

If I type g space, del, o space, del, o space, del, etc. then I can input something using the standard keyboard.

I just tried bVNC via SSH to my normal Linux boxes, and get the same results. Type a char, hit space, it shows, but just typing no joy.

**Comment by rec9140** [comment]
>I would first advise using another keyboard on your Amazon HDX8.9. Is one available from the App >Store?

Using the Klika keyboard via the Amazon Application store, seems to resolve it, so this is a keyboard issue with the standard Fire Keyboard and aRDP/bVNC.

This is a workaround for now.
