### ISSUE TITLE
your app for f-droid

### ISSUE THREAD

**Issue by theScrabi** [iiordanov/remote-desktop-clients#70]
Hello have you considered to put your apps on [f-droid](https://f-droid.org/) it's a store/repository for FLOSS Android apps.

Wed have to change something on your code in order to make your apps work on f-droid since they don't like binary blobs.

**Comment by iiordanov** [comment]
Hi Christian,

Of course I have, however, there are so many libraries that my apps depend
on that unless f-droid allows some functionality where they can be built
and available to me centrally, putting together a build system for all that
would be difficult. I use a lot of LGPL (and similarly licensed) libraries
from the gstreamer project rather than building them all myself. In various
Linux distros, there is either a system to build or download all your
dependencies. For f-droid, my understanding is that if your app requires
one half of an operating system, it's up to you to build and include that :)

Any suggestions are welcome!

Thanks!
iordan

On Fri, Jun 24, 2016 at 4:22 AM, Christian Schabesberger <
notifications@github.com> wrote:

> Hello have you considered to put your apps on f-droid
> <https://f-droid.org/> it's a store/repository for FLOSS Android apps.
>
> Wed have to change something on your code in order to make your apps work
> on f-droid since they don't like binary blobs.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/iiordanov/remote-desktop-clients/issues/70>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABWyV0A4W5BLczVO6p1HwTRZ3mZfpwV_ks5qO5O8gaJpZM4I9j7x>
> .
>



-- 
The conscious mind has only one thread of execution.

**Comment by theScrabi** [comment]
Hm... I'd have to contact the maintainers. Maybe they will accept the libs when we mark in the description where they came from.

**Comment by IzzySoft** [comment]
@iiordanov I had put the app(s) into [my F-Droid compatible repo](https://android.izzysoft.de/repo), but now I cannot find from where to update them. If you'd add the `.apk` files to the corresponding `releases/*` (and make the corresponding tag a release – see [creating releases](https://help.github.com/articles/creating-releases/), it's pretty easy to do and shouldn't take much more than a minute (depending on the amount of details you want to fill in, of course ;)), they could be updated from there automatically.

Please let me know if that'd be acceptable to you (and if so, when the first `.apk` is available there), so I could set that up. Interested users then just had to add my repo to their F-Droid client.

**Comment by corbinlc** [comment]
Can we revive this conversation @iiordanov ?  As you know, UserLAnd is dependent on bVNC, but UserLAnd just got accepted to f-droid and bVNC is not there.  Is it possible to work towards including bVNC now.  If not, is it recommended for people to grab the latest APKs here: https://github.com/iiordanov/remote-desktop-clients/releases

**Comment by IzzySoft** [comment]
While currently bVNC is available [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.iiordanov.freebVNC), I agree that especially in that context it would be much favorable having it in the official repo.

As for libs and what @theScrabi wrote: no binaries are accepted. But you could e.g. include the sources via submodules, so we can build from there. Not sure how many there are and for which modules this could work (I'm no dev), but we could try.

PS: by "we" I mean "F-Droid", where I'm meanwhile one of the maintainers (yes, there's stuff to do for non-devs as well :wink:)

**Comment by IzzySoft** [comment]
@iiordanov is there any chance this will be worked on – or should we rather close [the request opened 5 months ago](https://gitlab.com/fdroid/rfp/issues/815) at F-Droid as we cannot process it anyway? What about the submodule suggestion? Or you could point out where the sources are, and our "integrators" could check if we could set them up as `srclib`.

**Comment by iiordanov** [comment]
Hi Izzy,

The README.md file of the project describes the build procedure for it. Is
that what you are looking for?

I am in the middle of bug fixes and feature development for the project and
have not had time to look at f-droid, apologies all around or all the
delays. I have a few more months of active development left before I can
switch away and look at this.

Releases in app format for the project are indeed available here:

https://github.com/iiordanov/remote-desktop-clients/releases

Thanks!
Iordan

**Comment by IzzySoft** [comment]
Hi Iordan,

I'm no dev nor do I have any build experience. But being one of the F-Droid maintainers (though my part of the work focuses on metadata like descriptions and links), I saw that hanging. Releases in app format are nothing F-Droid can work with – other than my own repo which simply grabs the APKs, F-Droid completely builds from source. And completely also means: no binaries allowed (so for the JARs, we'd need the sources and e.g. set them up as `srclib`s).

I'm only the messenger here. Better discuss the details with those who understand them (@theScrabi might be able to help out, or see in [the RFP mentioned](https://gitlab.com/fdroid/rfp/issues/815)).

Thanks!

**Comment by iiordanov** [comment]
The apps are available at: https://github.com/iiordanov/remote-desktop-clients/releases

**Comment by IzzySoft** [comment]
And [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.iiordanov.freebVNC), should you wish to link there. Not the same "level" as F-Droid itself, but still helpful to folks without PlayStore access. Oh, [aRDP](https://apt.izzysoft.de/fdroid/index/apk/com.iiordanov.freeaRDP) is there, too.
