### ISSUE TITLE
run aSPICE error

### ISSUE THREAD

**Issue by zorahou** [iiordanov/remote-desktop-clients#72]
[bVNC] Installing bVNC.apk ...
[bVNC] Success!
[ZoomerWithKeys] Could not find ZoomerWithKeys.apk!
[PubkeyGenerator] Could not find PubkeyGenerator.apk!
[FreeRDPCore] Could not find FreeRDPCore.apk!

I hava added ZoomerWithKeys,PubkeyGenerator ,FreeRDPCore as libraries project to bVNC project,and installed sqlitegen plug-in as well.

And I have recovered libraries that are distributed with the repository.
Added the libdatabase_sqlcipher.so,libgstreamer_android.so,libspice.so to the armeabi,armeabi-v7a,and x86.

but I still got that error.

dear iiordanov,
please help me.

**Comment by iiordanov** [comment]
There have been many changes to the build system of the project since this issue was opened and it should not longer be an issue.
