### ISSUE TITLE
disabling bvnc filtering?

### ISSUE THREAD

**Issue by irregularisnotrandom** [iiordanov/remote-desktop-clients#75]
Hi

Is it possible to disable  the linear filtering in the scaled mode? Every time I click on the screen the screen flickers because it changes from filtered mode to none filtered mode, It is generally visible araound bright pixels , about one pixel with grayer pixels

thanks

**Comment by iiordanov** [comment]
There does not appear to be any visual effect on my Pixel, please reopen if this is still an issue for anyone.
