### ISSUE TITLE
Problem with setRedirectMicrophone(boolean) setRedirectSound(int)

### ISSUE THREAD

**Issue by russian-studios** [iiordanov/remote-desktop-clients#77]
I have error with Description:
The method setRedirectMicrophone(boolean) is undefined for the type BookmarkBase.AdvancedSettings
The method setRedirectSound(int) is undefined for the type BookmarkBase.AdvancedSettings

This error happened, because I use stable-1.1 version of FreeRDP and this version doesn't support this redirections, how you resolve this problem? Maybe you can give me your FreeRDPCore or workspace with aSPICE... Thanks.

**Comment by iiordanov** [comment]
This is not an issue with the current build system.
