### ISSUE TITLE
Some keys don't work in Guest OS

### ISSUE THREAD

**Issue by givengenius** [iiordanov/remote-desktop-clients#86]
Hi, I connect to my Guest OS with aSpice.But keyboard does‘t work well.Because the keys like ’Shift‘,'Up','Down','Left' and 'Right' don't work in Guest OS.Forgive my poor English,can you help me?

**Comment by iiordanov** [comment]
You need to make sure "Use D-Pad for arrows and D-Pad click for Ctrl" is enabled in Advanced Settings.
